### ISSUE TITLE
Translation: Empty string returned instead of Default value

### ISSUE THREAD

**Issue by mxmtsk** [agentejo/cockpit#1000]
Although this should be fixed (https://github.com/agentejo/cockpit/pull/815#issuecomment-443884445) I still receive the empty string for a translation instead of the default value. I double checked that I have this change in my code.

```javascript
{
_id: "5c5b4e9616199d754a526818",
countryCode: "fr_FR",
name: "",
_mby: "5c5b4a0c16199d7549135692",
_by: "5c5b4a0c16199d7549135692",
_modified: 1549487932,
_created: 1549487766,
children: [ ]
}
``` 

When applying the change from the closed PR (link above) it works.

**Comment by aheinze** [comment]
the string is empty but not `null` that's why it doesn't fallback to default value

**Comment by mxmtsk** [comment]
@aheinze A content editor is not able to reset the value then though? Cause if he deletes the string, it's not set to null but to an empty string.

**Comment by aheinze** [comment]
I see, empty strings are causing also a fallback now - https://github.com/agentejo/cockpit/commit/cbde51bf9a4633cc300b40919683f91a5533e05e

**Comment by mxmtsk** [comment]
Thank you very much
