### ISSUE TITLE
Enhancement - collection entry form fields

### ISSUE THREAD

**Issue by pauloamgomes** [agentejo/cockpit#1001]
The actual UI for editing a collection entry is clean and simple, however, when we have a long list of fields we should have a better visual separation between them. 

My suggestion is to use the same strategy from contentful and prismic with a border on the left like  (blue when the field is focused) below:

![image](https://user-images.githubusercontent.com/102261/52418801-c0fa8900-2ae6-11e9-90e1-9f83b6532200.png)

**Comment by ben-styling** [comment]
To further this idea, it would be nice to add some more separation to "sets" in longer forms as well.
Maybe a slight indentation?

**Comment by aheinze** [comment]
addressed in this commit: https://github.com/agentejo/cockpit/commit/b4da30f34ad40e5b86ab9fcb9cee562677399012

**Comment by pauloamgomes** [comment]
Looks good, only issue can be when we have multiple columns:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/102261/52780883-26003280-3043-11e9-9d1b-c18291c99ecf.png">

but that is probably hard to solve... maybe to minimize the visual impact reducing the border opacity to .1 and to 2px:

<img width="249" alt="image" src="https://user-images.githubusercontent.com/102261/52781077-99a23f80-3043-11e9-8548-f562234d8351.png">
