### ISSUE TITLE
assets cleanup+minify to reduce data transfer on normal usage (currently more than 2MB)

### ISSUE THREAD

**Issue by raffaelj** [agentejo/cockpit#1003]
Cockpit loads a lot of resources and I would love to save some bandwidth (on mobile devices, while testing with disabled cache...).

The login page loads about 1MB, normal usage is about 1.1MB-1.9MB and while using the json editor, it's more than 2MB.

Can we reduce the size of a few scripts?

Suggestions:

* `jsoneditor.min.js` (756KB) - It's possible to reduce the size with a [custom build](https://github.com/josdejong/jsoneditor#custom-builds)
* `codemirror.js` (394KB) - not minified
* `components.js` (182KB) - can be minified or/and be splitted in single (minified) components, which are loaded when necessary
* `riot.js` (120KB) - is not minified
* `jquery.js` (85KB) - I know, there are a few places, where jQuery is used, but most things are done with riot.js or plain javascript. Do we really need it? Custom builds are possible, too.
* `favicon.ico` (81KB) - 4 sizes in one ico file are a nice-to-have. One size (32px x 32px) would be about 10KB.
* `fontawesome-webfont.woff2` (75KB) - Uikit needs it, but do we need the whole font? Maybe a custom build is possible, too...
* `moment.js` (51KB) - I think, it's only used to convert unix timestamps to `MMM D, YYYY`. So 51KB are a bit heavy for this job.

I didn't check the whole list, but dropping some unused code and minifying everything would be a performance boost.

**Comment by aheinze** [comment]
Hi,

I understand your concerns but I have to correct you a little bit here:

Cockpit (if using apache and the deflate module is enabled - see [here](https://github.com/agentejo/cockpit/blob/next/.htaccess#L131-L164)) serves all js and css assets gzipped. This results into different numbers (on the login page):

![bildschirmfoto 2019-02-10 um 02 21 36](https://user-images.githubusercontent.com/321047/52528280-f798f500-2cda-11e9-8e09-85bcde7aa577.png)

As you can see, the load size for all js+css assets are 212KB.

But you're right, there is always room for optimization. I'll try to do some improvements in one of the next releases.

Greets,
Artur

**Comment by raffaelj** [comment]
> if using apache and the deflate module is enabled

Thanks for the hint. It's much faster now on my local machine, but still >500KB on an entry page with codemirror and image-choser. An entry page with text and texteara fields transferred 340KB.

Interestingly, the size of `woff2` and `bmp` increased by a few bytes.

**Comment by pauloamgomes** [comment]
@aheinze, @raffaelj  maybe another improvement would be aggregating the js files, can see something like +60 requests just for js!
