### ISSUE TITLE
boolean field - renderer doesn't detect string "0" as false

### ISSUE THREAD

**Issue by raffaelj** [agentejo/cockpit#1006]
I'm not sure, if there are internal checks for all normal edge cases, but I currently have some data with ones and zeros instead of true/false. The renderer displays "On" for all values, because my zero is a string, which returns true.

The reason: I work on implenting MySQL (InnoDB) as an addon. MySQL has no boolean field and I have to work with tinyint.

**Comment by piotr-cz** [comment]
@raffaelj How is you progress on the addon?
I'm assuming that you decided to use one SQL column per document property/ field?

**Comment by raffaelj** [comment]
@piotr-cz I was very busy and had to pause the project. I'll publish it in a few weeks. Send me a private message if you want to have a look at it earlier.
My addon is no sql driver, like yours. I use Cockpit to manage an existing database with m:n relations and yes, I use one column per field.
