### ISSUE TITLE
Redirected to auth/login with 404 after install, nginx

### ISSUE THREAD

**Issue by GeorgWa** [agentejo/cockpit#1009]
I tried to install cockpit on my nginx server and ran into the same issue #686.
Did you find a solution for this issue on nginx ?

**Comment by gabskoro** [comment]
Found the solution 🎉

It was already discussed about the issue on #19. Also, there is a [link](https://github.com/COCOPi/cockpit-docs/blob/master/tutorials/nginx.md) to the nginx server config which worked for me (hence the `try_files $uri $uri/ /cockpit/index.php?$args;`)
