### ISSUE TITLE
Catastrophic failure if bootstrap.php doesn't exist in an Addon directory

### ISSUE THREAD

**Issue by dlolsen** [agentejo/cockpit#1014]
### Source of the Problem
The `registerModule` function on [line 1281 of lib/Lime/App.php](https://github.com/agentejo/cockpit/blob/243a39eb7db957f8ee41ca68b25839376bd56ecd/lib/Lime/App.php#L1281) doesn't check if `bootstrap.php` exists in the `addonNameDirectory` before assigning it as the bootfile for that specific module. If `bootstrap.php` doesn't exits the whole app fails.

### History
This failure happened to me when I was trying to install the *UniqueSlugs* addon. Since I was running a Docker container for Cockpit, I didn't know exactly the best way to interact with the filesystem (Docker is still new for me). So I thought I'd just use the _Finder_ in Cockpit to create the `UniqueSlugs` directory inside of `addons`, and then planned to create and copy the contents of the `bootstrap.php` and `version.txt` files... I never made it to adding the files because of the following catastrophic errors.

```
Warning: require(/var/www/html/addons/UniqueSlugs/bootstrap.php): failed to open stream: No such file or directory in /var/www/html/lib/Lime/App.php on line 1346

Fatal error: require(): Failed opening required '/var/www/html/addons/UniqueSlugs/bootstrap.php' (include_path='.:/usr/local/lib/php') in /var/www/html/lib/Lime/App.php on line 1346
```
### <a id="steps-to-reproduce"></a>Steps to reproduce:

1. Create new directory inside `addons` via Cockpit's _Finder_ (in my case it was _UniqueSlugs_)
2. An error alert shows up: *"Something went wrong."*
3. Refresh the page => catastrophic failure

### Suggested Solution
Update line 1281
FROM:
```
$module->_bootfile = "{$dir}/bootstrap.php";
```

TO:

```
if(!file_exists("{$dir}/bootstrap.php")){return false;}
$module->_bootfile = "{$dir}/bootstrap.php";
```

Also, update line 1312 (<--line number prior to above changes)

FROM:

```
$this->registerModule($name, $module->getRealPath());
```

TO:

```
if ( $this->registerModule($name, $module->getRealPath()) === false ) continue;
```

### Conclusion
I suppose you may also want to display an error to the user indicating that there is a _bootstrap.php_ file expected.

FYI, this is the first real issue I've ever submitted on GitHub, and I've also never forked a repo and issued a pull request so I wasn't quite ready for that…

I plan to follow the Egghead.io course on _How to Contribute to an Open Source Project on GitHub_, and I may submit a pull request if I feel confident that I'll do it right.

**Comment by raffaelj** [comment]
You're right, a check would be useful.
I added a dummy bootstrap file in the root of all of my addons to prevent this issue in the future.

**Comment by dlolsen** [comment]
@raffaelj Yes, that is probably a good practice. The main point of my issue was that Cockpit's `Finder` allows the creation of an `addon` directory without providing any checks or fallbacks for the `bootstrap.php` file not existing (even temporarily), and thereby causing a catastrophic failure.

Since no immediate solution was apparent, and based on comments it seems non-urgent, I closed the pull request.

I still think this should be left as an issue though.

**Comment by raffaelj** [comment]
> I still think this should be left as an issue though.

Me too. At least to have an answer, if others fall into this trap.

Your fix looks promising (didn't test it, yet).

> I suppose you may also want to display an error to the user indicating that there is a `bootstrap.php` file expected.

While developing an addon, the message `require ... bootstrap.php ... no such file or directory`
 is clear enough. I think, the normal use case is, to copy existing addons into the addons folder instead of creating empty folders by accident.
