### ISSUE TITLE
Thumbs are not working properly

### ISSUE THREAD

**Issue by pauloamgomes** [agentejo/cockpit#1018]
@aheinze not sure if that is happening only on mages using cloudstorage, but when thumbs are generated with output=1 I'm receiving a trashed image (16x16 black)! Didn't have time yet to identify where it is happening, but can confirm that issue started with commit a53d3afe9ff443c689b3af7b148e3d8e13ca624b
Date:   Thu Feb 14 01:40:06 2019 +0100
    some ui improvements - mainly image based fields

Until commit 5f819a0e98e7e8f4e245656769b3a2d672cdcc7d is working fine

**Comment by aheinze** [comment]
I experience transparency turning black when mode is thumbnail ... but only in combination wit php 7.3 ... 7.2 works fine. gdlib 😒

**Comment by pauloamgomes** [comment]
Humm, I tested on 7.2 and 7.1 both on mac and linux and still have the same issue..any ideas!

<img width="832" alt="image" src="https://user-images.githubusercontent.com/102261/52884910-550fc480-3167-11e9-865b-dbb2405b6bc0.png">

<img width="310" alt="image" src="https://user-images.githubusercontent.com/102261/52884958-7ffa1880-3167-11e9-8998-c4344e872dc4.png">

**Comment by pauloamgomes** [comment]
That's quite weird, I only noticed the error since the way you are loading the thumbs (you have now the o=1), so its outputting directly to the browser. The thumbs are generated well so the issue seems on my nginx/php, I confirmed that any image output to browser fails... so the issue seems not be on cockpit.

**Comment by pauloamgomes** [comment]
Closing, thats a fun error, one of the addons that I have was with a php file starting with spaces:

```
  <?php
```

those spaces were the cause of the failure on the file_get_contents output.. 😐
