### ISSUE TITLE
Missing $fn query filter on MongoDB

### ISSUE THREAD

**Issue by pauloamgomes** [agentejo/cockpit#1026]
Handling a complex query with a criteria function (`['$fn' => 'function_name']`) is working well with sqlite, but seems not available when using MongoDB. There is an alternative?

**Comment by aheinze** [comment]
did you try `$where` ? https://docs.mongodb.com/manual/reference/operator/query/where/

**Comment by pauloamgomes** [comment]
Thanks @aheinze , no yet, will have a look.

**Comment by pauloamgomes** [comment]
Ok, closing as can have the same functionality with $where (just required to port the function to js)

**Comment by aheinze** [comment]
never used it before. could you successfully use `$where`? how do you provide the function callback via php?

**Comment by pauloamgomes** [comment]
Yep, it worked well:

https://github.com/pauloamgomes/Cockpit-PublicationPeriod/blob/766c864ddc7d0b62614faf0f1a7d8c6f87c9a178/actions.php#L59
