### ISSUE TITLE
Thumbnails not showing

### ISSUE THREAD

**Issue by karpovsystems** [agentejo/cockpit#1031]
Thumbnails not showing on all pages

<img width="846" alt="2019-02-25 22 16 23" src="https://user-images.githubusercontent.com/15084014/53365964-26ee6980-394b-11e9-8a11-f7502f1bcade.png">

`GET /cockpit/utils/thumb_url` returns blank page with _Content-Type: text/html_

<img width="676" alt="2019-02-25 22 22 13" src="https://user-images.githubusercontent.com/15084014/53366812-2951c300-394d-11e9-99e8-1e2742673cb2.png">

## Technical Details
Ubuntu 16.04
PHP 7.2
Nginx

**Comment by karpovsystems** [comment]
Fixed by adding `$is_args`
```
location / {
    try_files $uri $uri/ /index.php$is_args$args;
}
```
Full nginx config that worked for me
```
server {

        listen 80;
        server_name test.com;

        root /var/www/cockpit;
        index index.php;

        location / {
                try_files $uri $uri/ /index.php$is_args$args;
        }

        location ~ /\.ht {
                deny all;
        }

        location ~ .sqlite$ {
                deny all;
        }

        location ~ \.php$ {
                fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
                fastcgi_index index.php;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
}
```

**Comment by aheinze** [comment]
@karpovsystems  thank you for posting the fix 👍
