### ISSUE TITLE
Get form data entries through API

### ISSUE THREAD

**Issue by xeriuk** [agentejo/cockpit#1037]
I can't find anything related to this in the documentation and I could really use this function for a page i'm making.

Any help is appreciated :)

**Comment by mpartipilo** [comment]
This was added a long time ago after we discussed it here: https://discourse.getcockpit.com/t/forms-do-they-work/158/10

Checking the code I see that an endpoint was added: /api/forms/export/{form_name}?token=xxx

Feel free to update the docs :smile:

**Comment by mpartipilo** [comment]
You should also know that I *think* this endpoint is only available to the admin user.

**Comment by xeriuk** [comment]
@mpartipilo I've just created a custom endpoint to the form API called filter, where I can filter through the entries. :) Thanks anyway for the help!

**Comment by mpartipilo** [comment]
I'd love to use that for an upcoming project. Do you mind sharing it?

**Comment by xeriuk** [comment]
Of course! I'm only using this to filter by email provided so you could edit this to the way you'd like it:

Just place these function the the /modules/Forms/Controller/RestApi.php file

`

        public function filter($form=null) {

                $form = $this->module('forms')->form($form);

                if (!$form) {
                    return $this->stop('{"error": "Form not found"}', 412);
                }
        
                $options = [];
                if (isset($_GET['email'])) {
                    $options['email'] = $_GET['email'];
                } else {
                    return $this->stop('{"error": "Email is empty"}', 412);
                }

                $entries = $this->module('forms')->find($form['name']);

                $filtered = $this->find($entries, $options);

                if(empty($filtered)) return $this->stop('{"error": "No entries found with supplied email"}', 412);;

                return [
                    'entries'  => $filtered
                ];

         }

        public function find($entries, $options) {

                $filtered = array_filter($entries, function($entry) use ($options){
                    if (isset($entry['data']['email'])) {
                        if ($entry['data']['email'] == $options['email']) return true;
                    }
                    return false;
                });

                return $filtered;
        }
`

The endpoint would look like this:
/api/forms/filter/form?token=token&email=email

Hope this is anyway useful!

**Comment by mpartipilo** [comment]
Awesome! This gives me an idea of how to add pagination. Thanks
