### ISSUE TITLE
z-index issue on "Add Item" button while editing a content in a column

### ISSUE THREAD

**Issue by charlyie** [agentejo/cockpit#1047]
Hi,

Thanks for your work, cockpit rocks 👍 

When using a column of content and editing a text, the button "Add Item" in background is visible in foreground. See : https://www.useloom.com/share/ea0640b05f5f4aa4ad315e6ddc0b7699

Cheers,
Charles

**Comment by aheinze** [comment]
This z-index issues are new 🤔 Thanks for reporting, I'll look into that
