### ISSUE TITLE
[Bug] Deleting fields in collections retains data in API

### ISSUE THREAD

**Issue by eternalflamez** [agentejo/cockpit#1050]
Steps to reproduce:

- Add a field to a collection
- Fill in a value for this field for any entry
- Delete the field

Now when making an api request to get all the values of this collection, you will see that the field is being retained.

This is somewhat related to #843, as renaming is kind of like deleting and then adding a new field, in this instance.

**Comment by aheinze** [comment]
this is not a bug but more a feature request. I'll try to find a solution for this in one of the next releases

**Comment by aheinze** [comment]
use the cli tool to remove deprecated fields, eg `./cp collection/removefield --collection posts --field intro`

**Comment by jebner** [comment]
Does such a script also exist for singletons or would it be possible to add one?
