### ISSUE TITLE
Enhancement - Action to delete revisions

### ISSUE THREAD

**Issue by pauloamgomes** [agentejo/cockpit#1051]
On the revisions screen would be useful to have the possibility to delete a particular revision or all revisions:

<img width="250" alt="image" src="https://user-images.githubusercontent.com/102261/54021741-b6d0b680-4188-11e9-936f-020901325adf.png">

That is quite interesting for dev/stage environments as we may end with hundreds of revisions during tests (manual/automated)

**Comment by aheinze** [comment]
I agree, this is already planned ☝🏻

**Comment by pauloamgomes** [comment]
Thanks @aheinze , that works well. I added something that believe is useful in my helpers addon, a configurable limit for the number of revisions to maintain - https://github.com/pauloamgomes/CockpitCMS-Helpers#max-revisions
