### ISSUE TITLE
Image URLs can not load, name resolve error

### ISSUE THREAD

**Issue by ApricumMedia** [agentejo/cockpit#1057]
I'm using Cockpit in a docker container within a docker compose setup. An NGINX process forwards requests from the outside to Cockpit inside its docker container, the container itself is not exposed. In essence, the CMS is reachable at `http://localhost:8090` while — within the docker network, as seen from NGINX — it is reachable at `http://cockpit:80`.

I can reach and use the CMS at `http://localhost:8090`. However, when uploading image assets, Cockpit *can not load them*, hitting an obvious name resolve error. The generated image urls it tries to reach use the *docker-internal server hostname* that is *not available* to the connecting browser. If the paths were specified relative to the actual path, the images could be loaded. See the following resource path I took from the network logs and a simple corrected path.

Used URL: `http://cockpit/storage/thumbs/114b40669bcd06c94af363683a255469_20x20_85_1552645411_bestFit_adb115059e28d960fa8badfac5516667.jpg`

Correct URL: `http://localhost:8090/storage/thumbs/114b40669bcd06c94af363683a255469_20x20_85_1552645411_bestFit_adb115059e28d960fa8badfac5516667.jpg`

**Comment by aheinze** [comment]
Hi,

Cockpit always tries by default to "auto-guess" the url which becomes difficult when it is behind a proxy. For that case you can define/override the public url in the config (config/config.php):

```
'site_url' => 'http://cockpit:80'
```

if you're using docker, you can then use an env variable, e.g `COCKPIT_SITE_URL`:


```
'site_url' => getenv('COCKPIT_SITE_URL')
```

**Comment by ApricumMedia** [comment]
Thank you very much, I had it resolved in an alternate approach by using a proper hostname for cockpit and not using `localhost` and ports. I was only an NGINX and a simple `/etc/hosts` entry away from a functioning setup.

Having the configuration option you posted is great, much appreciated.
