### ISSUE TITLE
Cockpit is not correctly guessing site paths. 

### ISSUE THREAD

**Issue by janoelze** [agentejo/cockpit#106]
Hi!

I have a cockpit instance sitting on a shared hosting environment (good god) and the inevitable happened: the root URL is broken. 

the public URL to the backend is:

`http://preview.xyz.de/cockpit``

$_SERVER:

```
[HOME] => /home81b/sub006/sc44909-HVEW
[HTTP_HOST] => preview.xyz.de
[HTTP_CONNECTION] => keep-alive
[HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
[HTTP_USER_AGENT] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36
[HTTP_ACCEPT_ENCODING] => gzip,deflate,sdch
[HTTP_ACCEPT_LANGUAGE] => de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
[HTTP_COOKIE] => PHPSESSID=ec759051b18572caf902a758fe146ebd; cockpitsession=4b6dae42efc689c53a941577a8281b77
[PATH] => /usr/local/bin:/usr/bin:/bin
[SERVER_SOFTWARE] => Apache
[SERVER_NAME] => preview.xyz.de
[DOCUMENT_ROOT] => /home81b/sub006/sc44909-HVEW/xyz.de/wordpress/dev
[SCRIPT_FILENAME] => /home81b/sub006/sc44909-HVEW/xyz.de/wordpress/dev/cockpit/index.php
[REMOTE_PORT] => 50284
[GATEWAY_INTERFACE] => CGI/1.1
[SERVER_PROTOCOL] => HTTP/1.1
[REQUEST_METHOD] => GET
[QUERY_STRING] => 
[REQUEST_URI] => /cockpit/
[SCRIPT_NAME] => /cockpit/index.php
[PHP_SELF] => /cockpit/index.php
[REQUEST_TIME_FLOAT] => 1404572185.3
[REQUEST_TIME] => 1404572185
```

The site URL that is used for the assets is 

`window.COCKPIT_SITE_BASE_URL  = '/mounted-storage/';`

which is incorrect and leads to the assets not being loaded. :)

the `__DIR__` vars value is `/mounted-storage/home81b/sub006/sc44909-HVEW/xyz.de/wordpress/dev/cockpit`

:(

**Comment by rdomingue** [comment]
I tried to install cockpit on a godaddy shared host on a subdomain.
The server passes the requirements.
After the installation I've got 404 error. 
Looking for help I saw many informations here, most of them talk about "open /cockpit/config.php and replace". But I don't have any config file in the folder. Is it normal. I've tried with nightly and stable version as well.

thanks
