### ISSUE TITLE
How to set repeater Item width

### ISSUE THREAD

**Issue by Escapado** [agentejo/cockpit#1061]
Hey,

I am using the repeater to display sets with an image and some text:
![repeater](https://user-images.githubusercontent.com/5439360/54629509-014f0e80-4a78-11e9-8059-9a5c088ec501.png)

When I add another item to the repeater it positions itself below the first item and is also stretched to full width.
I would like to be able to set the with of the items similarly to how you can set field widths (1-1 / 1-2 etc) so it would look something like this:

![repeater_mook](https://user-images.githubusercontent.com/5439360/54629620-4115f600-4a78-11e9-8a35-256c6b144294.png)

Is there an option to set the width of the items in a repeater? The documentation doesn't mention it.

**Comment by aheinze** [comment]
This is not possible, because it doesn't make sence for most of the use-cases

**Comment by pauloamgomes** [comment]
> This is not possible, because it doesn't make sence for most of the use-cases

Think that would make sense in some scenarios, for example when you have nested elements (e.g. a set with a repeater, and other fields). Not saying that should be supported for all the levels, but at least for the first level of the set would be quite handy.

**Comment by aheinze** [comment]
adding more complexity here doesn't improve anything that much that I would like to always maintain it in the future

**Comment by pauloamgomes** [comment]
That's fair and understand that

**Comment by Escapado** [comment]
Alright, thanks for the swift reply. :)
