### ISSUE TITLE
Suggested Enhancement - "Range" or "Number" field type

### ISSUE THREAD

**Issue by lmlsna** [agentejo/cockpit#1062]
It seems like there are only 2 field types that deal with numeric input, regular old text inputs _(which works just fine with a `([0-9]*)` pattern restriction)_ or the `rating` element _(which rapidly becomes absurd with maximum values over 10 as it displays a star for each number)_.

There are 2 HTML5 native elements that would be more functional and could be implemented with very small modifications to existing field types:

- A [`range`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range) input _(which renders out of the box as an ugly slider on most browsers)_ could be created by cloning the [field-rating](https://github.com/agentejo/cockpit/blob/next/modules/Cockpit/assets/components/field-rating.tag) field and making a few changes (mostly removing stuff).

- A [`number`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number) input field type (a textbox for fallback with a little up/down button next to it) could be implement with a few changes to the standard [field-text](https://github.com/agentejo/cockpit/blob/next/modules/Cockpit/assets/components/field-text.tag) input.

I'm not a big JS guy, otherwise I would have just sent a pull request straight away. I'm sure I _could_ manage a medium shitty pull request if you think this is a useful idea, and no one else feels like doing it.

But I figured someone else who knows the codebase could probably do that about 50x faster than me. Also just wanted to make sure I wasn't missing anything and that this would be useful before spending the time... It's a lot easier to use this than to hack on it lol.

Any thoughts?

**Comment by Blistok** [comment]
@lmlsna The Number field type:
https://github.com/Blistok/CockpitCMS-NumberField

**Comment by aheinze** [comment]
a workaround would be to use a text field with `"type":"range"` in the field options
