### ISSUE TITLE
Form view for large singletons takes extremely long to load

### ISSUE THREAD

**Issue by gryphonmyers** [agentejo/cockpit#1065]
I have a singleton with ~6800 members (including field values for ~10 languages) and it takes roughly 2.5 minutes to load the form view for edits. In this specific case, all fields are basic text fields. Are there any optimizations we could make to this view to reduce the load time for very large singletons?

**Comment by aheinze** [comment]
6800 fields in one singleton!? 😯 maybe you should rethink the data model

**Comment by mpartipilo** [comment]
Curious too

**Comment by gryphonmyers** [comment]
It's a large project, but that's kind of beside the point. Even more reasonably sized singletons suffer from less-than-desirable load times.

**Comment by aheinze** [comment]
what is reasonably to you? I have a collection with 45 fields and don't see any issues. but > 100 or in your case 6800 is another level. did you think about using an object field?

**Comment by gryphonmyers** [comment]
Object fields won't localize the way we need them to. Your CMS supports localization which means that given a normal locale set of 10 locales, your field count is multiplied by 10. 100 fields, sure that means we have 1000 fields, and the interface starts to choke a bit.

**Comment by aheinze** [comment]
Ok, I see one optimization that can be implemented pretty quickly to reduce the parsing time caused by riotjs...give me a sec

**Comment by gryphonmyers** [comment]
Suggestion: use a projection to only fetch the pertinent locale fields (assuming you're not already doing that)?

**Comment by gryphonmyers** [comment]
Another suggestion: projection to only fetch active group / tab?

**Comment by aheinze** [comment]
can you test against the latest next branch?

**Comment by gryphonmyers** [comment]
Well whatever you did certainly helped! My mountain of a singleton went from 2.5min to 1.5min. So do we think this is primarily a front end lockup? That might make sense because the network tab actually looks pretty light. I wonder if we could render components lazily as they scroll into view?

**Comment by aheinze** [comment]
can you share your singleton file definition (via email) so I can do some tests?
