### ISSUE TITLE
Thumbs are not served on https

### ISSUE THREAD

**Issue by imagoiq** [agentejo/cockpit#1066]
Hello,

Just a simple issue which I got when I'm viewing entries in a collection with assets.
Firefox tell me that the connection is not secure because thumbs aren't served with https.

If I force the config with 'site_url' everything works.

Regards

**Comment by aheinze** [comment]
is yout cockpit instance running behind a proxy? If yes, you need to force it via `site_url`

**Comment by imagoiq** [comment]
Yeap. Actually I noticed that when I view an entry Firefox doesn't say that there are elements which aren't secure on the page although there is inside the custom-element.
