### ISSUE TITLE
Version module

### ISSUE THREAD

**Issue by webcliq** [agentejo/cockpit#1067]
Environment is Wampserver latest on Windows 2016 Server

Install Cockpit but it returns an error. After bug hunting, it appears that the versions module is not installed, by default, in latest Wampserver. Enabling the Module removes the problem - which is of course the first lines in .htaccess.

Suggest adding mod_versions inside brackets on your Requirements page within Cockpit Documentation.

**Comment by aheinze** [comment]
will do, thanks for the hint!
