### ISSUE TITLE
Sort by nested field

### ISSUE THREAD

**Issue by pauloamgomes** [agentejo/cockpit#1069]
It's possible to sort by nested fields? something like:

`$options['sort'] = ["date.start" => 1];`

If not, what should be the best approach?

**Comment by aheinze** [comment]
should work if you're using mongodb as datasource 🤔

**Comment by pauloamgomes** [comment]
I am, but seems not work, I tried with a simple nested field and also with a collection link..

**Comment by aheinze** [comment]
according to the docs it should - https://docs.mongodb.com/manual/reference/method/cursor.sort/

I don't have time right now to test this, but keep it in mind to test it later

**Comment by pauloamgomes** [comment]
Yeah, checking in detail works well with a nested element like a set, I was trying something more complicating as using a field of a linked collection and that can't work because the field is not in the document as it has only the collection link structure (link, display)

**Comment by pauloamgomes** [comment]
Can be closed as it seems to work as per expectation for mongodb, however would be interesting on have a solution for sorting based on collection links.

**Comment by aheinze** [comment]
maybe this answer on stackoverflow helps: https://stackoverflow.com/a/42709853
