### ISSUE TITLE
500 on collection entry and singleton form views

### ISSUE THREAD

**Issue by gryphonmyers** [agentejo/cockpit#1070]
Sometime around https://github.com/agentejo/cockpit/commit/917ba5afdcb9e8504fa5fbedc0e4b76563a6c62e a bug was introduced in our environment where all collection entry and singleton form views 500. If I revert to https://github.com/agentejo/cockpit/commit/b76b5556d06fba590983597ff12db882d1737557 it works as normal again. Any ideas of new environment requirements that may have been introduced here causing these errors for an existing installation?

**Comment by aheinze** [comment]
Do you have access to php error log files? I have started to use the memory service which uses SQLite. Maybe your setup is missing the SQLite + pdo extension

**Comment by gryphonmyers** [comment]
This was the only thing the PHP error log turned up, but I'm not sure if this is related: 

```
2019/03/28 22:53:23 [error] 16149#0: *2201 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: endpoint in /var/www/cockpit/addons/CloudStorage/bootstrap.php on line 46" while reading response header from upstream, client: REDACTED, server: REDACTED, request: "GET /cockpit/collections HTTP/1.1", upstream: "fastcgi://unix:/var/run/php71-fpm.sock:", host: "REDACTED", referrer: "http://REDACTED"
```

**Comment by aheinze** [comment]
I can't reproduce it 🤔 And the only thing that was added on the backend side is the "lock ui" for entries. so this is strange. can set `debug` to `true` in the config, so might get more information?

**Comment by gryphonmyers** [comment]
I will try that when I am able! Thanks

Curious - what is the lock UI?

**Comment by aheinze** [comment]
The "Lock UI" prevents two users editing an item at the same time
