### ISSUE TITLE
Filter by Collection-Link property

### ISSUE THREAD

**Issue by filisko** [agentejo/cockpit#1072]
Hi,
None of the existent issues helped.

This works perfectly, but instead of 'display', I would like to filter by any other property of that collection-link. How could I do that? I'm using mongodb.
```json
{
     "populate": 1,
     "simple": 1,
     "filter": {
         "commercialZone.display": {"$eq": "Barcelona"}
     }
}
```

**Comment by pauloamgomes** [comment]
Believe that will work only with the attributes that are stored in the collection, by default on the collection link is `link, display, _id`. Is something that I wanted for sort  #1069 but I'm afraid is not supported.

**Comment by filisko** [comment]
@pauloamgomes , thank you for your reply.

Hmm, but according to the owner it should work with mongodb. I just followed the following installation tutorial of mongodb for Ubuntu: https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/

Do you think it could be the version or something? :S

**Comment by filisko** [comment]
I found a workaround enabling the 'read' permission and writing your own code.

```php
// collection.read.php

$relationship = cockpit()->module('collections')->collection('collectionName');

$relationshipData = cockpit()->storage->find("collections/{$relationship['_id']}", [
    'filter' => [
        'status' => [
            '$in' => ['pending', 'denied'] // you could get these values from GET parameters
        ]
    ]
])->toArray();

$relationshipDataIds = array_column($relationshipData, '_id');

$context->options['filter']['relation._id']['$in'] = $relationshipDataIds;
```
