### ISSUE TITLE
Image path incorrect - Backslash?

### ISSUE THREAD

**Issue by masters1222** [agentejo/cockpit#1073]
I can't seem to find this anywhere... When I upload an image by clicking "Select Image" the below happens.

If I upload an image as an asset, then the path resolves fine.

See the screenshot below. Notice the \favicon.png,

![image](https://user-images.githubusercontent.com/9289570/55563448-fc1ed000-56c3-11e9-9ec0-e2d7869b97bc.png)

I'm testing on XAMP with Windows 7. Is this possibly a Windows related issue?

**Comment by raffaelj** [comment]
I never use image fields, because I had some troubles with them. If you don't have a specific reason, always use assets. Have a look here for some more details:
https://discourse.getcockpit.com/t/select-image-results-in-something-went-wrong-on-asset-field/378/2

And now your Windows problem - I have a symlinked environment and cockpit sometimes has problems with path pattern replacements, especially on Windows with symlinked paths. I wrote a custom `defines.php` in the root of cockpit with this content:

```php
<?php

// Windows environment in subdir: http://localhost/dir/cockpit
// symlink from E:\git\dir to E:\xampp\htdocs\dir
if (strpos(__DIR__, ':\\', 1)) { // is windows environment
    
    $COCKPIT_SITE_DIR = realpath(dirname(dirname(__DIR__)));
    
    if (strlen($COCKPIT_SITE_DIR) == 3) {

        if (!defined('COCKPIT_SITE_DIR')) define('COCKPIT_SITE_DIR', substr($COCKPIT_SITE_DIR, 0, 2)); // E:

    } else {

        if (!defined('COCKPIT_SITE_DIR')) define('COCKPIT_SITE_DIR', str_replace(DIRECTORY_SEPARATOR, '/', $COCKPIT_SITE_DIR)); // E:/git

    }

}
```
I hope, that helps.

**Comment by masters1222** [comment]
> I never use image fields, because I had some troubles with them. If you don't have a specific reason, always use assets. Have a look here for some more details:
> https://discourse.getcockpit.com/t/select-image-results-in-something-went-wrong-on-asset-field/378/2
> 
> And now your Windows problem - I have a symlinked environment and cockpit sometimes has problems with path pattern replacements, especially on Windows with symlinked paths. I wrote a custom `defines.php` in the root of cockpit with this content:
> 
> ```
> <?php
> 
> // Windows environment in subdir: http://localhost/dir/cockpit
> // symlink from E:\git\dir to E:\xampp\htdocs\dir
> if (strpos(__DIR__, ':\\', 1)) { // is windows environment
>     
>     $COCKPIT_SITE_DIR = realpath(dirname(dirname(__DIR__)));
>     
>     if (strlen($COCKPIT_SITE_DIR) == 3) {
> 
>         if (!defined('COCKPIT_SITE_DIR')) define('COCKPIT_SITE_DIR', substr($COCKPIT_SITE_DIR, 0, 2)); // E:
> 
>     } else {
> 
>         if (!defined('COCKPIT_SITE_DIR')) define('COCKPIT_SITE_DIR', str_replace(DIRECTORY_SEPARATOR, '/', $COCKPIT_SITE_DIR)); // E:/git
> 
>     }
> 
> }
> ```
> 
> I hope, that helps.

Hey thanks! I later ended up using an Asset field over an image field and it works like you suggested.

**Comment by raffaelj** [comment]
No problem. If it works, please close the issue.
