### ISSUE TITLE
Provide trigger to login event error

### ISSUE THREAD

**Issue by pauloamgomes** [agentejo/cockpit#1075]
In some scenarios (logging) is desired to have access to login failures (https://discourse.getcockpit.com/t/securing-the-login-page/704).
Having a trigger (using only the username from the data array) would provide the flexibility to handle the error by 3rd parties.

**Comment by pauloamgomes** [comment]
Implemented on #1076

**Comment by pauloamgomes** [comment]
@aheinze , that seems to be reverted after being merged, there is any reason to not have the trigger there?

**Comment by aheinze** [comment]
@pauloamgomes the event trigger moved to the auth controller here https://github.com/agentejo/cockpit/blob/next/modules/Cockpit/Controller/Auth.php#L42

**Comment by pauloamgomes** [comment]
Ok, sounds fine, thanks.

**Comment by pauloamgomes** [comment]
@aheinze , but was checking in detail and it seems that the trigger event can't be captured, if I have:

```
$app->on('cockpit.authentication.failed', function ($user) use ($app) {
// my action
});
```

that code is never executed!
