### ISSUE TITLE
File(s) failed to upload - when uploading anything

### ISSUE THREAD

**Issue by AienTech** [agentejo/cockpit#1078]
Hey there,

so, after trying many times to upload a 180KB picture, I still get this error "File(s) failed to upload".

I tried to check:
 - PHP configurations in `php.ini`
 - webserver log files
 - filesystem permissions (currently set on `www-data` and `777`)
 - network requests (shows the response: `{"uploaded":[],"failed":[{"file":"the-image.jpg","error":0}]}`)
 - cockpit logfiles (under `storage/log` which is empty!)
 - update the project with the latest `cockpit-next` branch

any ideas how can I fix it?

**Comment by raffaelj** [comment]
Maybe your storage folder has no write permissions?

**Comment by AienTech** [comment]
That was the 3rd thing that I've checked for. unfortunately, there's still this problem which I really can't find out why.

**Comment by raffaelj** [comment]
I guess, you use some addons, because you have a log file. Do you use maybe the Groups addon and did you set `allowed_uploads ` without the file extensions, e. g. `.jpg .jpeg`?
