### ISSUE TITLE
Response with html redirection tag for the first time request to CMS

### ISSUE THREAD

**Issue by devron1n** [agentejo/cockpit#1081]
Hello!
I've got a strange issue, i couldn't fix it or find something in the google.. 

I've installed Cockpit a time ago and it worked perfect with no issues.
Then my customer filled Cockpit with his content and implemented some SEO stuff on the front-end.
And now when trying to load content from the Cockpit by simple HTTP GET request ( https://myhost.com/admin/api/collections/get/products?token=xxxtokenxxx ) it responses with:

200 OK

`<html><head><meta http-equiv="Refresh" content="0; URL=https://myhost.com/admin/api/collections/get/products?token=xxxtokenxxx&attempt=1"></head><body></body></html>`

If refresh the page - everything goes OK, so this issue only for the first time website visitors.

First, i've thought that something wrong with the front-end, but when i was trying to CURL https://myhost.com/admin/api/collections/get/products?token=xxxtokenxxx , i've got the same strange response with redirect meta tag..

**Comment by Martynro** [comment]
Hello ! I'm the above customer who faced with this issue...Still waiting for any feedback . Pls help !

**Comment by raffaelj** [comment]
I have no idea, what could cause this issue on cockpit's side. @devron1n, @Martynro Can you provide some more info, like the cockpit version, Apache or nginx, PHP version > 7.0?

You mentioned some changes with SEO stuff... Did you maybe change a redirect from `www.myhost.com` to `myhost.com` with a html redirect instead of a 301 rewrite via .htacces or with nginx settings etc.?

**Comment by Martynro** [comment]
@raffaelj  ,  Thanks for feedback.  Checked  the points you advised . 
Actually you were right  -  no  did  correct redirection   via .htacces or with nginx settings. At the moment We done  it  but the issue  with us again.  Still  we are getting the above non-workable first response . 

As to more info : 
version cockpit  0.8.7
nginx
PHP 7.2..

Probably we have conflict  between  the cockpit server software   settings  (Apache as default)  and  our server (nginx) ?

**Comment by raffaelj** [comment]
I'm not experienced with nginx, so I can't give any advice here. Maybe you find some example settings here in the issues or in the [support forum](https://discourse.getcockpit.com/).

When I saw `<meta http-equiv="Refresh" content="0; ...` my first thought was, that you shouldn't use it. You need a browser to redirect that page. Always use server side rewrite rules or php `header()`.

When you changed it to the correct way - Did you test it with a browser or with a tool like curl or Postman? Maybe everything works, but you have to clear the browser cache or close the browser once...

**Comment by Martynro** [comment]
We tested  with  different  browsers. Clearing the browser cache before
testing every time.
 In any case  thank you for support !  Will try to adjust cockpit
settings.

ср, 8 мая 2019 г. в 10:28, Raffael <notifications@github.com>:

**Comment by Martynro** [comment]
and we  did  with Curl  also . The same respone
<html><head><meta http-equiv="Refresh" content="0; URL=https://myhost.com
/admin/api/collections/get/products?token=775b05fefd29cff52ff64e94ee7ecd&attempt=1
<https://rinprom.com/admin/api/collections/get/products?token=775b05fefd29cff52ff64e94ee7ecd&attempt=1>
"></head><body></body></html>

ср, 8 мая 2019 г. в 12:12, Роман Мартынов <martynro@gmail.com>:

**Comment by raffaelj** [comment]
@Martynro 

**First:**
You should change your api key immediately.

**Second:**
I know, I shouldn't, but I did it - and I don't understand Russian, so I have no clue about your contents and I didn't try any other api endpoints...

First I tried your exposed url `/api/collections/get/products?token=xxtokenxx` in the browser and it redirected me to the api response. Then I tried it with [PostMan](https://www.getpostman.com/) and I got the meta-refresh result with `&attempt=1` at the end. Now I have a cookie and the next response works.

You really have to check your javascript/SEO/webhoster/whatever settings. I don't see, why or where cockpit would ever do such stuff.

**Comment by Martynro** [comment]
Thank you  @raffaelj  !    Next  response not  the first one. Will try  find out the reason.

**Comment by Martynro** [comment]
@raffaelj 
We  found the reason of the issue. It was on the hosting side . As result they corrected some points :   switched-off  a  cachering OPache module  and  adjusted  a cache settings of static files.
Now  it  works  good. 
Thank you for your time and support !
