### ISSUE TITLE
Using Vue w/ Axios to filter and sort posts

### ISSUE THREAD

**Issue by nickpish** [agentejo/cockpit#1084]
I'm using Vue w/ Axios to fetch posts from Cockpit, and I'm trying to figure out how to filter and sort results using parameters (such as `published = true`), instead of filtering the response in the way I have it below:

(I have `Vue.prototype.$http = axios` set in my `main.js`)

```
fetchPosts: function () {
      const baseURI = 'http://cms.com/cockpit/api/collections/get/posts?token=TOKEN'
      this.$http.get(baseURI)
      .then((response) => {
        const posts = response.data.entries
        this.postsPub = posts.filter(post => post.published == true) // filter published posts
      })
      ....
}
```

The above works- but I'd rather filter and sort using something like the following, but I can't seem to get it working:

```
fetchPosts: function () {
      const baseURI = 'http://cms.com/cockpit/api/collections/get/posts?token=TOKEN'
      this.$http.get(baseURI, {
        params: {
          filter: {published: true}
          sort: {[_created]: -1}
        },
      })
      ....
}
```

How can I pass parameters to Axios via a basic GET request to, for example, fetch published posts and sort them by date of creation (or any other field)? Thanks for any assistance here!

*Minor update here- I'm realizing I can, of course, also append a string to `baseURI` along the lines of `this.$http.get(baseURI + '&filter[published]=true'`, but again, I'm wondering how to pass a params object and also include a method of sorting, say by a numeric `sort` field.

**Comment by sa7bi** [comment]
You could filter your collection by adding `?filter[field]=value` to your URL.
For more information, please visit: [Search items by term](https://discourse.getcockpit.com/t/search-itens-by-term/70/5)

**Comment by VishalBty** [comment]
Here's how to do it correctly
`export default {
  data() {
    return {
      posts: [],
    }
  },
  mounted() {
    this.fetchPosts ()
  },
  
  methods:{
    async fetchPosts () {
      const baseURI = 'http://cms.com/cockpit/api/collections/get/posts?token=TOKEN'
      const params = {
        filter: {published: true},
        sort: {[_created]: -1},
        token: MYTOKEN
      }
      const {data} = await this.$http.get(baseURI, {params:JSON.stringify(params)})
      this.posts = data
    }
  }
}`

Also, you should avoid using baseurl variable. Instead, you can set base URL using Axios defaults
like this axios.defaults.baseURL = 'http://cms.com/cockpit/api/collections/get/'

Then your code would look like this
`async fetchPosts () {
      const params = {
        filter: {published: true},
        sort: {[_created]: -1},
      }
      const {data} = await this.$http.get("/posts", {params:JSON.stringify(params)})
      this.posts = data
    }
  }`

You can also set the token in params default but I am not sure if it would for cockpit because you have to stringify first
`axios.defaults.params[ 'token' ] = MYTOKEN; `
