### ISSUE TITLE
group rights are broken after changing any user data

### ISSUE THREAD

**Issue by raffaelj** [agentejo/cockpit#1087]
Steps to reproduce:
* login as a user without admin rights (or without 'cockpit/accounts')
* go to `/accounts/account`
* change your user name

The account is saved correctly, but if I reload the page, I get a `Notice: Undefined index: group in ...\storage\tmp\account.php.0...b.lexy.php on line 134`

I also can't access collection anymore, because my group rights don't exist anymore.

I located the bug in the Accounts controller. Here, the group value is unset, which is fine (`unset($data['group']);`):
https://github.com/agentejo/cockpit/blob/next/modules/Cockpit/Controller/Accounts.php#L114

but then the user data is set without the group `$this->module('cockpit')->setUser($data);`
https://github.com/agentejo/cockpit/blob/next/modules/Cockpit/Controller/Accounts.php#L167

It seems, cockpit tries to get the data from the session and the group value got lost:
https://github.com/agentejo/cockpit/blob/next/modules/Cockpit/module/auth.php#L58

Same experience with Firefox in paranoia mode (privacy settings) and Opera with default settings on Windows.

**Comment by aheinze** [comment]
Thanks for reporting!
