### ISSUE TITLE
[Suggestion] Make adding repeater item more convenient

### ISSUE THREAD

**Issue by dubaua** [agentejo/cockpit#1092]
When you have many repeaters or repeater inside another repeater is easy to mess what item you are adding. I suggest rework 'Add item' to Add field label. I tried to change it myself, but nothing changed. Is there anyway to rebuild riot templates to see changes?

https://github.com/agentejo/cockpit/blob/ed5bb1226310fedef1c02dc2ce608162934e49e4/modules/Cockpit/assets/components/field-repeater.tag#L37
```<a class="uk-button"><i class="uk-icon-plus-circle"></i> { App.i18n.get('Add') item.field.label ? item.field.label : 'item' }</a>```

**Comment by raffaelj** [comment]
You have to rebuild `components.js` with `npm run build-components`. See [package.json](https://github.com/agentejo/cockpit/blob/next/package.json)

For quick tests without rebuilding, you can search for the tag in `components.js` and add a change there
