### ISSUE TITLE
Field binding in 'set'-fieldtype

### ISSUE THREAD

**Issue by StefSmeers** [agentejo/cockpit#1094]
I have an issue in version **0.9.0** and **0.8.11**. (Didn't test other versions)

The fields are not bound correctly. When you have 2 fields which take string input (textarea, text, ...) and you fill out one of them, the second one will be changed to that value as well.

You can simply reproduce this issue by adding a field with fieldtype 'set' and use these options:
```
{
  "fields": [
    { "type": "text", "label": "Title" },
    { "type": "textarea", "label": "Description" }
  ]
}
```

_It might be me who is doing something wrong here, I just started using Cockpit. If so, feel free to call me stupid._ 🙂

**Comment by aheinze** [comment]
```
{
  "fields": [
    {"name":"title", "type": "text", "label": "Title" },
    {"name":"description", "type": "textarea", "label": "Description" }
  ]
}
```

the `name` property does the trick here ;-)
