### ISSUE TITLE
Difficulties with API keys behind a load-balancer

### ISSUE THREAD

**Issue by sergiogcx** [agentejo/cockpit#1104]
I set up a two-container cluster of Cockpit, both containers behind a load-balancer. All working nominally, except for API calls.

When calling API keys behind a load-balancer some requests are dropped as an HTTP "401 Unauthorized"  error every other request.

```
User --> [Load Balancer] ------> [Container 1] / [Container 2] ----> [MongoDB]
```

I am only a beginner with Cockpit, but It looks like the api keys are saved to (and loaded from) disk:

(save) https://github.com/agentejo/cockpit/blob/9506426b1b61b2bcaba68bb226beddd309b48dbc/modules/Cockpit/bootstrap.php#L79

(load) https://github.com/agentejo/cockpit/blob/9506426b1b61b2bcaba68bb226beddd309b48dbc/modules/Cockpit/bootstrap.php#L62

Is there a way to store the api keys elsewhere, preferably in MongoDB or Redis?

Regards,

PS. Related issues:

```
complications when scaling to multiple nodes (or containers)
#992 by imraazrally was closed on Feb 3 
https://github.com/agentejo/cockpit/issues/992

Running on HTTPS behind a load balancer with HTTP
#926 opened on Nov 13, 2018 by kulrich-kwp 
https://github.com/agentejo/cockpit/issues/926
```

**Comment by aheinze** [comment]
Api keys are stored in the main db now. Please try the latest `next` branch
