### ISSUE TITLE
Get image is broken in 0.9.0

### ISSUE THREAD

**Issue by jwlogemann** [agentejo/cockpit#1106]
Hi,
I'm trying to retrieve my uploaded images through the API, but it appears to be completely broken.
I'm POSTing the following JSON against sitename/api/cockpit/image
{
	src: "cockpit/storage/uploads/images-4.png",
	mode: "thumbnail",
	width: 500,
	height: 500,
	quality: 80
}
and it always returns:
{
    "error": "Target width or height parameter is missing"
}
I've tried different values for "src", I also tried the syntax from the documentation:
{
	src: "cockpit/storage/uploads/images-4.png",
	m: "thumbnail",
	w: 500,
	h: 500,
	q: 80
}
But this doesn't work either

**Comment by aheinze** [comment]
I can't verify the issue 🤔

Can you try the api directly via GET:

`/api/cockpit/image?src=cockpit/storage/uploads/images-4.png&w=50&token={token}`

**Comment by jwlogemann** [comment]
Weirdly enough that works. But putting the exact same parameters in a json post doesn't 🤔

**Comment by aheinze** [comment]
can you post the exact code snippet?

**Comment by jwlogemann** [comment]
This is the raw request:

POST /api/cockpit/image HTTP/1.1
Host: vbox2:4061
Content-Type: application/json
Authorization: Bearer 0cae1123088d40b51540904a86a716
User-Agent: PostmanRuntime/7.11.0
Accept: */*
Cache-Control: no-cache
Postman-Token: 24091b8c-5768-4a5a-a721-591635c3d4c0,ae7c29db-cf5e-43a5-bfd9-36c768908e4b
Host: vbox2:4061
cookie: mysession=5fcbaaa8d5a744a01715b023bb2c6a0f
accept-encoding: gzip, deflate
content-length: 52
Connection: keep-alive
cache-control: no-cache

{
	"src": "storage/uploads/images-4.png",
	"w": 50
}

**Comment by aheinze** [comment]
🤷‍♂️

```
curl -X POST \
  http://cockpit.local/api/cockpit/image \
  -H 'Authorization: Bearer b7e6aae549dedc4c7ef026dd6a9a7e' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: bb9d0950-1ffa-4cf3-8850-0967571ff8b2' \
  -H 'cache-control: no-cache' \
  -d '{
"src": "storage/uploads/960.jpg",
"w": 50
}'
```

works for me.

**Comment by jwlogemann** [comment]
I've just destroyed and rebuilt the docker image it was running in, and now it works...
