### ISSUE TITLE
App.assets.getCss creates a second request with image element

### ISSUE THREAD

**Issue by raffaelj** [agentejo/cockpit#1118]
I wanted to load a css file dynamically with

```js
App.$(document).ready(function() {
    App.assets.getCss('/videolinkfield/style.css');
});
```

and I found a weird second request:

```
# cause: stylesheet
http://localhost/cockpit/addons/VideoLinkField/assets/videolink.css?v=0.9.0
# cause: img
http://localhost/cockpit/addons/VideoLinkField/assets/videolink.css?v=0.9.0?v=0.9.0
```

**Comment by aheinze** [comment]
This is by design. This is the only way to check if a stylesheet exists or not, which is important for the assets loader.

**Comment by raffaelj** [comment]
OK, I see the context, even if I don't understand it to 100%. But the second request shouldn't add the version again, since it was added already a few lines above:
https://github.com/agentejo/cockpit/blob/next/assets/app/js/app.js#L237-L245
