### ISSUE TITLE
Can't upload images

### ISSUE THREAD

**Issue by thepurpleblob** [agentejo/cockpit#1123]
Getting this when trying to upload images...

PHP Warning:  move_uploaded_file(): Unable to move '/tmp/phpBKUOHd' to '/var/www/html//horses.jpg'
Unable to move '/tmp/phpBKUOHd' to '/var/www/html//horses.jpg' in /var/www/html/cockpit/modules/Cockpit/Controller/Media.php on line 111, referer: http://ubuntu.local/cockpit/collections/entry/images

The 'root' of my Cockpit install is /var/www/html/cockpit. It's like it's missed some part of the path... but I'm struggling to see why it's gone wrong.

**Comment by thepurpleblob** [comment]
Should have said, I did this using the little 'upload' icon adding an image field in a collection. 

From the actual 'assets' function, it seems to upload fine. So the problem is specific to adding records to a collection.

**Comment by tournevis** [comment]
I run into the same issue, could you find any work around ?

**Comment by aheinze** [comment]
looks like a file permissions issue. closing this for as it pretty old
