### ISSUE TITLE
customElements - dis-/connectedCallback in wrong order (polyfill/Firefox ESR)

### ISSUE THREAD

**Issue by raffaelj** [agentejo/cockpit#1126]
I digged some more in the code to finally fix #940, which is closed, but not fixed yet and I found the reason.

`customElements` were introduced in Firefox 63 ([caniuse.com][1]), so the Firefox 60.7.0esr (Extended Support Release) needs a polyfill. The polyfill from [WebReflection][2] works well, but the elements are connected twice (riot.js?). For some reason, all `connectedCallback`s are called first and the `disconnectedCallback` is called at the end.

[`cp-actionbar.js`][3] is the only file, where the `disconnectedCallback` is used and it breaks the layout.

![cp-customElements-ff-esr-annotations](https://user-images.githubusercontent.com/13042193/58704971-10bed200-83ae-11e9-8e2c-f92471946d00.png)

[1]: https://caniuse.com/#search=customElements
[2]: https://github.com/WebReflection/document-register-element
[3]: https://github.com/agentejo/cockpit/blob/next/assets/app/components/cp-actionbar.js#L12

**Comment by aheinze** [comment]
did you try to enable custom elements in firefox? 

via `dom.webcomponents.customelements.enabled` preference in `about:config?

**Comment by raffaelj** [comment]
I tried it now and it works perfectly. With `dom.webcomponents.customelements.enabled`, it loads in the right order again. But doing changes in `about:config` is not really consumer friendly.

These older browsers are in use and there are good reasons to use ESR, e. g.
* > Mozilla Firefox ESR is meant for organizations that manage their client desktops, including schools, businesses and other institutions that want to offer Firefox. [...] [source](https://www.mozilla.org/en-US/firefox/organizations/)
* using legacy addons, that weren't updated to be compatible with Firefox Quantum
* security: new features can cause new vulnerabilities
* privacy: the Tor browser is based on Firefox 60 ESR

I didn't test other browsers without custom elements, but the current solution might break there, too.

So everything works fine with the polyfill, except the one disconnectedCallback with the body padding. I think, it's better to work without this feature until web components are available by default, which is at the end of October 2019 ([source](https://www.mozilla.org/en-US/firefox/organizations/) --> scroll down to the picture).

Or we could find a fix to preserve the right order with polyfills, but I don't know, where to start. The nice thing about riot.js and polyfills is, that they work out of the box and I don't really want to think about these (edge) cases.

**Comment by raffaelj** [comment]
Tested with Firefox ESR 68.4.2 - Now custom elements are enabled by default.
