### ISSUE TITLE
Using Cockpit with MongoDB causes error while creating collections

### ISSUE THREAD

**Issue by bartlubbersen** [agentejo/cockpit#1134]
Hi Cockpit,

First of all thanks for this product, it looks promising, however I am having some issues.

During the installation I kept getting the error that I needed PDO with sqlite support even though I adjusted my config file to use MongoDB. The requirements said that sqlite or MongoDB would be ok, so it's strange. I circumvented that issue by removing the check from the index.php file in the install folder, this solved the problem and the installation was successful. Although this is not the issue I am raising this issue for, it might be relevant so I wanted to mention it anyway.

Because now I can login to the system, but when I try to create my first collection it throws an error. After some debugging and research I found out that the error is thrown in the lib/RedisLite file, it is trying to setup a sqlite connection via PDO, which it obviously can't do since those are not installed.
I do see I can configure redis as the memory back-end so it doesn't need sqlite/PDO anymore, but it doesn't say anywhere that when using MongoDB Redis cache is required. So I am wondering is it necessary to use Redis when using MongoDB? Or is there some sort of RedisLite variant for MongoDB?

Thanks for you in advance!

**Comment by aheinze** [comment]
Right, cockpit uses sqlite for "memory" (temp) storage. why don't you just enable pdo/sqlite? any special reasons?

greets!
