### ISSUE TITLE
PHP access with latest release

### ISSUE THREAD

**Issue by nebnes** [agentejo/cockpit#1142]
Is it still possible to access the collections, singleton, forms via php with the latest release?
Thanks

**Comment by aheinze** [comment]
Hi!

Yes, just include the `bootstrap.php` and you have all the cockpit api available.

```
<?php

include('cockpit/bootstrap.php');

$posts = cockpit('collections')->find('posts');

```

**Comment by nebnes** [comment]
Ok ! I lost sight of cockit for a while. 
I thought that was no longer available. 

Thank you Arthur for this great CMS ;)
