### ISSUE TITLE
Configuration mongodb system error after config

### ISSUE THREAD

**Issue by noerarief23** [agentejo/cockpit#1146]
application system error 500

![image](https://user-images.githubusercontent.com/5919917/60675204-fe045500-9ea5-11e9-8dd8-86ab95553941.png)

this is my configuration
![image](https://user-images.githubusercontent.com/5919917/60674920-6acb1f80-9ea5-11e9-8a45-4ae85268f98c.png)

![image](https://user-images.githubusercontent.com/5919917/60675025-a960da00-9ea5-11e9-92b5-8184f961f19d.png)

any solution?

**Comment by aheinze** [comment]
add `debug: true` to the config to get a more detailed error message

**Comment by noerarief23** [comment]
> add `debug: true` to the config to get a more detailed error message

![image](https://user-images.githubusercontent.com/5919917/60689649-dfc04880-9ee9-11e9-85de-48edd222bb60.png)

**Comment by aheinze** [comment]
maybe a yam parser issue

try to use a `config.php` instead of a `config.yaml`

```
<?php

return [

    'app.name' => 'Admin',

    'database' => [
        'server' => '...',
        'options' => [
            'db' => 'cockpitdb'
        ]
    ]

];

```

**Comment by noerarief23** [comment]
> maybe a yaml parser issue
> 
> try to use a `config.php` instead of a `config.yaml`
> 
> ```
> <?php
> 
> return [
> 
>     'app.name' => 'Admin',
> 
>     'database' => [
>         'server' => '...',
>         'options' => [
>             'db' => 'cockpitdb'
>         ]
>     ]
> 
> ];
> ```

not working



> > add `debug: true` to the config to get a more detailed error message
> 
> ![image](https://user-images.githubusercontent.com/5919917/60689649-dfc04880-9ee9-11e9-85de-48edd222bb60.png)

**Comment by noerarief23** [comment]
![image](https://user-images.githubusercontent.com/5919917/60709615-13778e80-9f3b-11e9-89e1-bdc13e133a13.png)

ext-mongodb version, it affects?

**Comment by noerarief23** [comment]
it's done, ext-mongodb version must >= 4.0

I need to upgrade the mongodb driver

sudo apt-get install php7.x-dev

Install PECL
sudo apt-get install php-pear

Install MongoDB driver
sudo pecl install mongodb

Finally, add the following line to your php.ini file for php-fpm and cli:

extension=mongodb.so

restart the service php7.x fpm

**Comment by noerarief23** [comment]
it's done, ext-mongodb version must >= 4.0

I need to upgrade the mongodb driver

sudo apt-get install php7.x-dev

Install PECL
sudo apt-get install php-pear

Install MongoDB driver
sudo pecl install mongodb

Finally, add the following line to your php.ini file for php-fpm and cli:

extension=mongodb.so

restart the service php7.x fpm
