### ISSUE TITLE
Collection link issues after latest update - Critical

### ISSUE THREAD

**Issue by pauloamgomes** [agentejo/cockpit#1147]
Believe the latest update (commit 9399f7783cfc02baa0d81b799bd2b681ce1d664b) to support custom display format is causing issues, my collection entries are now displayed with the field name instead of field value, e.g.:

![image](https://user-images.githubusercontent.com/102261/60798168-83b72780-a168-11e9-9c5f-8ca6c54e55c9.png)

on the json:

![image](https://user-images.githubusercontent.com/102261/60798203-95003400-a168-11e9-98fe-90b551f67351.png)

**Comment by aheinze** [comment]
Could you please test again the latest next branch? Thanks!

**Comment by pauloamgomes** [comment]
Thanks @aheinze , seems ok now.
