### ISSUE TITLE
Create collection from REST API

### ISSUE THREAD

**Issue by PatrickSachs** [agentejo/cockpit#1150]
Hello there,

first of all: I really like the project however it really suffers from the absence of proper documentation.

How would I go about creating a collection using the REST API? `/api/collections/newCollection/`,`/api/collections/createCollection/`, etc. all return a 404 error

**Comment by dantheta** [comment]
You can create a collection through the API using:

```
curl -v -H 'Content-type: application/json' -X PUT \
    -d '{"name":"foo","data":{"label":"Foo"}}' \
    http://<server>:<port>/api/collections/createCollection?token=<superadmin api key>
```

Tested with latest docker image.

**Comment by PatrickSachs** [comment]
Thanks for your reply. 
I am no longer using Cockpit and thus can't test if this would have solved the problem, so I'll just take your word and close this issue. :)

**Comment by coderbuzz** [comment]
Just in case anyone still needs it

**Sample field names:**
- name: TEXT
- data: Object

``` js
const options = {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
    'api-key': 'account-xxxxxxxdea2ce008ef5ab239ab47'
  },
  body: '{"data":{"name":"hello","data":{"hello":"world"}}}'
};

fetch('https://yourdomain.com/api/collections/save/<collection-name>', options)
  .then(response => response.json())
  .then(response => console.log(response))
  .catch(err => console.error(err));
```
