### ISSUE TITLE
Form label malformed <input /> tag

### ISSUE THREAD

**Issue by janbiasi** [agentejo/cockpit#1157]
At the moment it isn't possible to edit the `Label` of any form because of a malformed HTML tag (`<inpu` instead of `<input`). Screenshot shows the issue :) 

Cockpit Version: `0.9.2`
PHP Version: `7.2`

Installed Extensions:
- Lokalize
- CockpitQL
- APITester
- Moderation
- SimpleResponseCache

![image](https://user-images.githubusercontent.com/4563751/62402272-3ec7ba80-b587-11e9-8d15-03e0bab665b1.png)

**Comment by aheinze** [comment]
this is already fixed in the next branch.

**Comment by janbiasi** [comment]
Thanks @aheinze for the fast response. So am I supposed to close this issue or keep it as tracker until the next release will be done?
