### ISSUE TITLE
SVG Upload not working in v0.9.2

### ISSUE THREAD

**Issue by Escapado** [agentejo/cockpit#1158]
Hi,

I have a problem with uploading SVG files using the asset manager. I get a 
`POST http://134.209.230.215/cockpit/assetsmanager/upload 500 (Internal Server Error)`
and a small pop up that says "Something went wrong".
Uploading png or jpg files works fine though and proper rights to the folders have been assigned. I am using v0.9.2. Any idea what might cause this?

Edit: I noticed the svgs do get stored in storage/tmp but that's it.

**Comment by aheinze** [comment]
can you share the svg file?

**Comment by Escapado** [comment]
Here you go: https://image.flaticon.com/icons/svg/751/751621.svg

**Comment by aheinze** [comment]
Just tested wit the latest next branch and had no issues 🤔
