### ISSUE TITLE
Set with collectionlink not working with MongoDB, works with sqlite

### ISSUE THREAD

**Issue by DagobertDokate** [agentejo/cockpit#1163]
Hello everyone,

we use the Cockpit CMS for one of our projects. Now we have used sqlite on the development environment. In operation we would like to use MongoDB. But this is not so easy, because there are errors which did not occur under sqlite:

We once tested the MongoDB with AWS (v3.6.0) as well as a locale with 4.0.11, unfortunately without success.

We have a collection release. There is a repeater in this collection. This contains a set, which again contains a collectionlink to another collection.
The field has the following Json:
```
{
  "field": {
    "type": "set",
    "name": "shopLink",
    "label": "Shop",
    "options": {
      "fields": [
        {
          "type": "collectionlink",
          "options": {
            "link": "Shops",
            "multiple": false,
            "display": "Shops"
          }
        },
        {
          "name": "link",
          "type": "text",
          "label": "Shop-Link"
        },
        {
          "name": "time",
          "type": "time",
          "label": "Zeitpunkt der Veröffentlichung"
        }
      ]
    }
  }
}
```

Under sqlite this was no problem and worked. New elements could be added without any problems. With the use of MongoDB this is unfortunately not possible. The error message appears that the key is not valid. If the same collectionlink is used outside the set, it works fine.

Is this a bug? Or is the options-json wrong?

greetings Dagobert

**Comment by aheinze** [comment]
can you provide the exact error message?

**Comment by DagobertDokate** [comment]
WIthout debug flag it was 'system error'. With debug flag i have to ask my colleague. It was something like' invalid key'.

**Comment by DagobertDokate** [comment]
The error message is 'invalid document for insert: empty key'

**Comment by futureco-de** [comment]
We found the issue. The first item in options->link needed a name. that is:
```
"fields": [
        {
          "type": "collectionlink",
          "name": "foo",
          "options": {
              ....
          }
        },
```
