### ISSUE TITLE
How to login into Docker Image

### ISSUE THREAD

**Issue by 00SteinsGate00** [agentejo/cockpit#1170]
Hey there,

I checked the Issues but didn't find anything.

I wanted to try Cockpit on my local machine to see if it fits my needs. So I installed it using docker following the instructions on the cockpit website.

The instructions basically say "use the following docker command, then open localhost:8080 and follow the instructions". When I open localhost:8080 I am prompted with the login page but since I never created an account I cannot login or restore the password. 

How do I create the first account on a new docker instance to actually use Cockpit?

Sorry if this issue was opened before and I didn't find it.

**Comment by alecananian** [comment]
There's further [documentation on this page](https://getcockpit.com/documentation/reference/docker), which notes that you should go to `/install` to complete the setup and get the default login credentials.

**Comment by 00SteinsGate00** [comment]
Oh my bad, I'm really sorry. It worked perfectly and Cockpit seems pretty nice.
