### ISSUE TITLE
High Res image throws "Something went wrong" when uploading

### ISSUE THREAD

**Issue by LuisCRSousa** [agentejo/cockpit#1184]
The image Byte size is not that big, only 1.3M but it have 4961x7016 pixels.

If I reduce the pixel size to half it works.

Cockpit 0.9.3

**Comment by aheinze** [comment]
can you maybe share the photo, so I can do some tests?

**Comment by LuisCRSousa** [comment]
Yes, sorry.

https://www.dropbox.com/s/6wq40koo4cn2nvp/conversa.jpg?dl=0

**Comment by aheinze** [comment]
I had no issues with the upload. what is your memory size?

**Comment by LuisCRSousa** [comment]
I have 128. Will try tomorrow setting it up a little

**Comment by zpike** [comment]
I have PHP7.3 installed, and change memory_limit to 512M and upload_max_filesize to 1024M, but I still cant upload video files around 200M..

**Comment by aheinze** [comment]
@zpike you need also to adjust `post_max_size`

**Comment by hypo-thesis** [comment]
I still got this issue and my post max size is post_max_size = 50M. I can upload otherwise with other scripts and wordpress and such. Where can I see the log?
