### ISSUE TITLE
wysiwyg field breaks if language file is in separate COCKPIT_ENV_ROOT config dir

### ISSUE THREAD

**Issue by raffaelj** [agentejo/cockpit#1186]
I tried the new `COCKPIT_ENV_ROOT` and I really like that feature to keep my changing files separated. But it fails with the path detection when calling `App.route()`. That behaviour breaks the wysiwyg field when it tries to load the language file.

`App.route('/config/cockpit/i18n/tinymce/'+lang+'.js')`

https://github.com/agentejo/cockpit/blob/next/modules/Cockpit/assets/components/field-wysiwyg.tag#L68

**My setup**

defines.php:

```php
define('COCKPIT_ENV_ROOT', str_replace(DIRECTORY_SEPARATOR, '/', realpath(__DIR__.'/../data/cp')));
```
```
cockpit
data/cp    # COCKPIT_ENV_ROOT
other_files.php
```
So it is parallel to Cockpit and all storage, config etc. files are in `/data/cp`.

I found a quick and dirty workaround. Add this snippet to `/data/cp/config/bootstrap.php`:

```php
// reroute files from config dir if they are requested via app.js - App.route()

// single file
$app->bind('/config/cockpit/i18n/tinymce/de.js', function () {

    if ($path = $this->pathToUrl('#config:cockpit/i18n/tinymce/de.js', true)) {
        $this->reroute($path);
    }

});

// generic solution for other files
$app->bind('/config/*', function ($params) {

    if ($path = $this->pathToUrl('#config:'.$params[':splat'][0], true)) {
        $this->reroute($path);
    }

});
```
It helps for the moment, but it feels dirty.

**Comment by aheinze** [comment]
I see, I'll try to find a solution

**Comment by raffaelj** [comment]
Some thoughts...

Loading files from `/config/tags` works, because the paths are generated via php.
https://github.com/agentejo/cockpit/blob/next/modules/Cockpit/views/layouts/app.php#L233-L235

I fiddled a bit and with this branch it's possible to use paths with
`App.route('#config:cockpit/i18n/tinymce/de.js')`

https://github.com/raffaelj/cockpit/commit/e803562d231ea020fb79390e8467d7cb71bde0c0

All paths are now visible in the source code - I'm not sure, if that might be a problem.
```js
App.$data = {"user":{"...":"..."},"...":"...",
"paths":{"#root":"\/cockpit","#storage":"\/cockpit\/storage","#pstorage":"\/cockpit\/storage","#data":"\/cockpit\/storage\/data","#cache":"\/cockpit\/storage\/cache","#tmp":"\/cockpit\/storage\/tmp","#thumbs":"\/cockpit\/storage\/thumbs","#uploads":"\/cockpit\/storage\/uploads","#modules":"\/cockpit\/modules","#addons":"\/cockpit\/addons","#config":"\/cockpit\/config","assets":"\/cockpit\/assets"},
"...":"..."};
```
```js
App.$data = {"user":{"...":"..."},"...":"...",
"paths":{"#root":"\/CpMultiplane\/cockpit","#storage":"\/CpMultiplane\/data\/cp\/storage","#pstorage":"\/CpMultiplane\/data\/cp\/storage","#data":"\/CpMultiplane\/data\/cp\/storage\/data","#cache":"\/CpMultiplane\/data\/cp\/storage\/cache","#tmp":"\/CpMultiplane\/data\/cp\/storage\/tmp","#thumbs":"\/CpMultiplane\/data\/cp\/storage\/thumbs","#uploads":"\/CpMultiplane\/data\/cp\/storage\/uploads","#modules":"\/CpMultiplane\/cockpit\/modules","#addons":"\/CpMultiplane\/data\/cp\/addons","#config":"\/CpMultiplane\/data\/cp\/config","assets":"\/CpMultiplane\/cockpit\/assets","site":"\/CpMultiplane\/data\/cp"},
"...":"..."};
```

And it won't work, if the config folder is above the web root. In this case, loading files from `/config/tags/*.tag` wouldn't work either.

What do you think?

**Comment by aheinze** [comment]
this is not an easy topic ... I'm still searching for the most elegant solution here. But it is on my todo-list ☝️

**Comment by raffaelj** [comment]
I know... this is complicated. Take your time. I have working workarounds and I found another edge case, where the current javascript path detection breaks.

When I try to keep my root folder clean, it's nice to use Cockpit as a library

`~/html`:

```
data/
     addons
     config
     storage
lib/
    cockpit
.htaccess
bootstrap.php   // define: COCKPIT_DOCS_ROOT, COCKPIT_BASE_URL, COCKPIT_BASE_ROUTE, COCKPIT_SITE_DIR
defines.php     // define('COCKPIT_ENV_ROOT', __DIR__ . '/data');
index.php       // define: COCKPIT_ADMIN, COCKPIT_ADMIN_ROUTE, run app
```
and I use this workaround in `~/html/bootstrap.php`:

```php
// fix broken assets paths when loaded via App.base()
$cockpit->on('app.layout.header', function() {
    echo '<script>';
    echo 'App.base_url = (App.base_url + "/lib/cockpit/").replace(/\/$/, "");';
    echo 'App.env_url = "'. $this->pathToUrl(COCKPIT_ENV_ROOT) .'";';
    echo 'App.base = function(url) {
      return url.indexOf("/addons") === 0 || url.indexOf("/config") === 0 ? this.env_url+url : this.base_url+url;
    };';
    echo 'App.route = function(url) {
      if (url.indexOf("/assets") === 0) return this.base_route+"/lib/cockpit"+url;
      if (url.indexOf("/addons") === 0 || url.indexOf("/config") === 0) return this.env_url+url;
      return this.base_route+url;
    };';
    echo '</script>';
});
```
