### ISSUE TITLE
'site_url' not work

### ISSUE THREAD

**Issue by masaki-takano** [agentejo/cockpit#1190]
Cockpit is my best CMS.

but `site_url` is not work.

```
$configs['site_url'] = 'http://localhost:8080/cms';
```

* nginx `http://localhost:8080`

```
    # cms
    location /cms {
      rewrite /cms/(.*) /$1 break;
      proxy_pass http://cms;
    }
```

* cockpit `http://cms` is work by docker.  working good.

![スクリーンショット 2019-10-16 19 21 47](https://user-images.githubusercontent.com/12701053/66910814-40633380-f04a-11e9-9cb3-dd863fb10ab8.png)

**Comment by Drobniac** [comment]
How did you fix this issue?

**Comment by masaki-takano** [comment]
@Drobniac 

Sorry,
I gave up specifying the path.


config.php
```
$configs['site_url'] = 'http://cms.mydomain.com';
```

nginx.conf 
```
    # cms
    location / {
      proxy_pass http://cms;
    }
```
