### ISSUE TITLE
Do we need "show raw json"?

### ISSUE THREAD

**Issue by blistok** [agentejo/cockpit#1193]
@aheinze [This commit](https://github.com/agentejo/cockpit/commit/72368dd733aab0f40041c60424aad84ed781f43d) introduces option to display JSON, but we already have this functionality (and the option to update the data directly by editing JSON) through [this addon](https://github.com/pauloamgomes/CockpitCMS-Helpers#json-previewlive-edit-of-collection-entries-and-singletons-data).

I think that this functionality makes more sense to be brought in as a plugin vs. being part of the core. But if it's decided to stay in the core, can we please make it optional/configurable?

**Comment by aheinze** [comment]
show raw json is the first step ... editing will come next

**Comment by blistok** [comment]
Got it. 
In that case @pauloamgomes can we consider making the plugin version optional (via config) or even deprecate it once there is a feature parity?

**Comment by pauloamgomes** [comment]
@blistok , sure, that make all sense.
