### ISSUE TITLE
wrong path detection in /media/api Controller with COCKPIT_ENV_ROOT

### ISSUE THREAD

**Issue by raffaelj** [agentejo/cockpit#1200]
affected:
* `/settings/edit` --> can't open config file
* Finder --> can't navigate above `COCKPIT_ENV_ROOT` (as admin, didn't test with non-admin user)

Steps to reproduce:
* copy existing config and storage folder into `/tests/cpdata`
* `define('COCKPIT_ENV_ROOT', str_replace(DIRECTORY_SEPARATOR, '/', __DIR__) . '/tests/cpdata');` in `defines.php`
* login and open settings

**Comment by aheinze** [comment]
> Finder --> can't navigate above COCKPIT_ENV_ROOT (as admin, didn't test with non-admin user)

this is the correct behaviour. every env root should be seperated from other envs. need to check the settings issue

**Comment by raffaelj** [comment]
> need to check the settings issue

It seems to be a Windows or a subfolder problem... It works on a CentOS7 host (tested right now).

My local dev setup is in `localhost/subfolder` with Xampp for Windows... When Microsoft drops the support for Windows 7 in 2 months, I will switch to a *nix system and I won't have these problems anymore :wink:
