### ISSUE TITLE
how to close app-panel-dropdown isn't obvious

### ISSUE THREAD

**Issue by raffaelj** [agentejo/cockpit#1204]
Steps to reproduce:
* click on the site logo at the top left --> the system menu appears

Users have to guess, that they have to click in the empty area of the app panel dropdown to close it and

1. It is impossible to close the dropdown without a mouse (accessibility).
2. Closing fails if a user clicks in the empty area of a `<ul>`
3. Even if it is not necessary, a close icon would be a visible helper.
4. I would like to close it via Escape key, but that's not so important.

**Comment by aheinze** [comment]
Commit fixed 1,2 + 4 ... I don't like the close icon idea. I think implementing close on esc is also intuitive

**Comment by raffaelj** [comment]
OK. Thanks for the fix.
