### ISSUE TITLE
Security issue in collections fields

### ISSUE THREAD

**Issue by isaac-gros** [agentejo/cockpit#1208]
First of all thanks for the work you're doing for Cockpit. I plan to use it on my portfolio in PHP because of it lightweight platform.

Now the thing is whenever you add any text field to your collection entry (like text, code, textarea...), you can actually send Javascript code to those fields. The browser will read it. Example below :

![cockpit-issue-1](https://user-images.githubusercontent.com/43828409/69495904-8d012080-0ecc-11ea-9730-9dbf3d20c3c7.png)

![cockpit-issue-2](https://user-images.githubusercontent.com/43828409/69495905-8d012080-0ecc-11ea-9b22-f2379427138a.png)

As a temporary solution, I check each of my fields through a Regex. I share it there if some people needs to use it  : 
``((<(no)?(script|iframe)(\s?.*)>.*)(<\/(no)?(script|iframe)>)*) ``

I didn't test the same thing with Forms and Singletons, but I guess the problem is the same. Adding a security check while submitting a entry form could be nice. I hope it will be added in the future realeases.

**Comment by aheinze** [comment]
Cockpit just stores values. E.g. code can of course contain a script depending on the use-case. You're responsible to sanitize/escape the data before rendering.
