### ISSUE TITLE
uikit sortable - items move on mousedown when trying to scroll with middle click

### ISSUE THREAD

**Issue by raffaelj** [agentejo/cockpit#1210]
affected:
* dashboard widgets
* fields in `cp-fieldsmanager`
* repeater fields while reordering is active
* layout field
* collection with custom sortable entries
* ...?

steps to reproduce:
* hover with your mouse over a sortable item
* use a mouse with a scroll wheel and click on it (middle click)
* hold the click and move your mouse
* the item (e. g. dashboard widget) moves

expected behaviour:
* left click can trigger the sortable event
* middle click is ignored and I can scroll on the page

solution:
https://github.com/raffaelj/cockpit/commit/6a61bc913524f91a95a384caa692b4e4c4f9ae5c

Should I open an issue in the UIkit repo?

**Comment by aheinze** [comment]
instead of `e.which != 1`, wouldn't be `(e.which == 2 || e.button == 4 )` more correct?

**Comment by raffaelj** [comment]
Maybe ;-) I'm not very familiar with touch devices or with mouses, that have more than three buttons...

**Comment by raffaelj** [comment]
Thanks for the fix. Now I can continue with my custom dashboard.
