### ISSUE TITLE
[Proposal] add Single Sign On

### ISSUE THREAD

**Issue by beasteers** [agentejo/cockpit#1218]
This might be best done via an addon (I'm not sure), but being able to sign in through another centralized identity provider would be very useful.

**Comment by juliosouza-pushstart** [comment]
Try the official plugin [Auth0](https://github.com/agentejo/Auth0)

**Comment by beasteers** [comment]
Oh werd. I'll need to dig into it more. It seems like it's currently non-operational (https://github.com/agentejo/Auth0/issues/1), but it looks like it's mostly there. Thanks for the link!
