### ISSUE TITLE
Can't upload svg images anymore

### ISSUE THREAD

**Issue by nilsborg** [agentejo/cockpit#1226]
Hi everyone,

I just discovered that i cannot upload svg files anymore in the assets manager.

Every other file is fine, only svgs affected.

Also had an older cockpit installation (0.9.0) which still accepted svgs. Now updated to 0.9.3 which says "something went wrong" on both installations (which are now both upgraded to 0.9.3).

Any ideas? Thanks!

**Comment by tommueller** [comment]
I have the same issue, but with jpgs! I can upload png, svg etc. but no jpgs ...

**Comment by pozylon** [comment]
Same here.

**Comment by raffaelj** [comment]
@nilsborg The svg upload problem might come from the implementation of a svg sanitizer to prevent xss attacks from malicious svg files.

commit:
https://github.com/agentejo/cockpit/commit/817ad23151da76cd391245d4cfb6f3ff63fd4e4c

Do you have a sample file to check, if it fails the test or if it fails only on your machine?

**Comment by raffaelj** [comment]
@tommueller The jpg upload issue is not related to this one.

Possible solutions:

You specified allowed uploads extensions and allowed `.jpg`, but not `.jpeg`.

You ran into your memory limit because of a high resolution picture.
Detailed answer: https://discourse.getcockpit.com/t/image-upload-fails-because-of-high-picture-resolution/844/12

**Comment by pozylon** [comment]
Downgrading to 0.9.3 solves the issue for me, I guess it's linked to Docker-based deployment and PHP version

**Comment by aheinze** [comment]
@pozylon updated the docker images which should solve the jpeg issue

**Comment by aheinze** [comment]
@nilsborg do you have the dom-extension installed? Or did you check the php error log?

**Comment by tommueller** [comment]
@aheinze I also switched to 0.9.3 to avoid the jpeg issue. Is 0.10.0 supposed to be the latest version with the fix from 10 days ago?

**Comment by ejdaly** [comment]
You may need to install php-xml to allow SVG upload (DOMDocument is used by SVGSanitizer.php)

**Comment by nilsborg** [comment]
> You may need to install php-xml to allow SVG upload (DOMDocument is used by SVGSanitizer.php)

Thanks man that totally resolved my issue! 👍
