### ISSUE TITLE
[Feature Request] "Update Many" Endpoint

### ISSUE THREAD

**Issue by beasteers** [agentejo/cockpit#1227]
Looking through the source, it looks like `api/collections/save/` only takes one row at a time. It would be useful to send multiple rows to update instead of 50 individual ones.

**Comment by raffaelj** [comment]
This should be possible by default. Instead of sending

```json
"data":{"_id":"entry_id_1","title":"new title 1"}
```

send an array of entries:

```json
"data":[{"_id":"entry_id_1","title":"new title 1"}],[{"_id":"entry_id_2","title":"new title 2"}]
```

**Comment by beasteers** [comment]
Hmmm,,, I guess you're right!

I swear I tested doing it *exactly* that way when I posted the issue and remember it not working until I changed back to single responses. 

But it seems to work now so now I'll just have to find out what I was doing wrong. 🤷🏼‍♀️
