### ISSUE TITLE
Redirecting after login to a specific route

### ISSUE THREAD

**Issue by patricksebastien** [agentejo/cockpit#1240]
How hard would it be to implement a redirection to a specific route after the login. Currently if I link a collection from an external system, I can send the url to the author ie:
https://cockpit.mydomain.com/collections/entries/MYCOLLECTION

Right now, he will get the login screen and then the dashboard, I would like for him to get the login screen and then the page MYCOLLECTION.

Thanks

**Comment by raffaelj** [comment]
Exactly this was implemented 5 days ago:
https://github.com/agentejo/cockpit/commit/08709873e1e06e2412a65d76a669c96935c84dab

**Comment by patricksebastien** [comment]
Top!
