### ISSUE TITLE
Issue with cockpit running on https behind nginx proxy

### ISSUE THREAD

**Issue by BlindDespair** [agentejo/cockpit#1242]
Hi, thank you for a great CMS, so far everything works great, except that when I uploaded my assets it failes to display thumbnails for them because of this:
![image](https://user-images.githubusercontent.com/15785773/74092931-5e5a1580-4acb-11ea-828b-e78a28707961.png)
I found out that my constants in javascript are not set up correctly:
```
        // App constants
        var SITE_URL   = 'http://cockpit';
        var ASSETS_URL = 'http://cockpit/storage/uploads';
        var PUBLIC_STORAGE_URL = '/storage';
```
Those values are cockpit's address in my docker network. I saw that I need to change `site_url` somehow, but when I set `define("COCKPIT_SITE_DIR", "https://cockpit.mysite.com");` cockpit completely fails to load. What and where should I set in order to make it work? Please help me, I've spent way too much time on this already. :(

This is what I get when I set in `config.yml` this:
 ```
paths:
  site: https://cockpit.mysite.com
```
![image](https://user-images.githubusercontent.com/15785773/74093008-81d19000-4acc-11ea-8fa1-fe4626f5c00b.png)

**Comment by aheinze** [comment]
Hi! Plase take a closer look here: https://getcockpit.com/documentation/reference/configuration

**Comment by BlindDespair** [comment]
@aheinze thanks for quick answer. Can I use yaml config for it? Or creating `config.php` is required?

**Comment by aheinze** [comment]
you can use yaml but I would recommend using `config.php`

**Comment by BlindDespair** [comment]
@aheinze I would like to stick to yaml, because we already use it as a source controlled config. By the way thank you very much. Putting next line in `config.yml` worked `site_url: https://cockpit.mysite.com`.
 I am pretty sure I put it there before, but probably the issue was that I was putting it with a `/` at the end like `site_url: https://cockpit.mysite.com/` and cockpit didn't like that.
