### ISSUE TITLE
Editing content for Repeater of Set 

### ISSUE THREAD

**Issue by radar1975** [agentejo/cockpit#1259]
Hi,

This is my options for a repeater
`{
  "field": {
    "type": "set",
    "label": "content",
    "options": {
      "fields": [
        {
          "type": "text",
          "label": "title"
        },
        {
          "type": "text",
          "label": "link"
        },
        {
          "type": "html",
          "label": "content"
        }
      ]
    }
  },
  "display": null,
  "limit": null
}`

When editing content all three Set element take the same value ... see atteched screenshot
![cockpit](https://user-images.githubusercontent.com/1986318/75287878-336d0280-57e9-11ea-845c-7682b23d48e8.PNG)

**Comment by aheinze** [comment]
you need to define a name property for each field:

```
{
    "field": {
        "type": "set",
        "label": "content",
        "options": {
            "fields": [{
                "type": "text",
                "label": "title",
                "name": "title",
            }, {
                "type": "text",
                "label": "link"
                "name": "link",
            }, {
                "type": "html",
                "label": "content"
                "name": "content",
            }]
        }
    },
    "display": null,
    "limit": null
}
```

**Comment by radar1975** [comment]
Thanks for the fast response 

it's all good now
