### ISSUE TITLE
filtering in range

### ISSUE THREAD

**Issue by jokopain** [agentejo/cockpit#1269]
Hi everyone I have a case:
In collection "items" I have field price, and i have search on frontend with fields "max-price" and "min-price".

For example I have:
```json
items [
 {"price": 250},
 {"price": 300},
 {"price": 600},
 {"price": 126}
]
```
 and user typed min-price: 100 and max-price: 500
How can i get only items with price in range between 100 and 500?

frontend: reactjs+redux and axios

**Comment by aheinze** [comment]
```

"filter": {
   "$and":[{"price":{"$gte":100}}, {"price":{"$lte":100}}]
}
```

**Comment by jokopain** [comment]
> ```
> 
> "filter": {
>    "$and":[{"price":{"$gte":100}}, {"price":{"$lte":500}}]
> }
> ```
Thank You very much!!!
