### ISSUE TITLE
_created output problem

### ISSUE THREAD

**Issue by jokopain** [agentejo/cockpit#1273]
Hi everyone.
I`m not sure is it my problem, server problem or in cms config problem.

So I need to output _created field by js but when I try do it like this:
```js
new Date(1583277880);
```
it returns "Mon Jan 19 1970 11:47:57 GMT+0400" for all my entries. 

But in Cockpit`s UI created and modified shows normal, mb i something missing?

Info:
Cockpit is installed on hosting
front-end ReactJS

**Comment by aheinze** [comment]
```
new Date(1583277880 * 1000);
```

**Comment by jokopain** [comment]
> ```
> new Date(1583277880 * 1000);
> ```
Thank you very much, but I myself have solved this problem with exactly the same method, but I still do not understand why it is necessary to multiply by exactly 1000?

**Comment by maerzhase** [comment]
@jokopain because js uses ms internally, while normal UNIX timestamps are usually in s.
