### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by The224** [agentejo/cockpit#1285]
I get an error when accessing any `/api` path, but the api return a http code `200`:

```
curl --request GET \
  --url https://{{base_url}}/api/collections \
  --header 'authorization: Bearer {{token}}'
```

```
Warning: preg_match(): Compilation failed: quantifier does not follow a repeatable item at offset 0 in /var/www/html/modules/Cockpit/rest-api.php on line 77
```

I use the latest version (as today) of the docker image [`agentejo/cockpit`](https://hub.docker.com/r/agentejo/cockpit/). I also created one collection and one entry.

**Comment by aheinze** [comment]
did you define any rules for the api key?

**Comment by The224** [comment]
Yes (For testing):

```
*
/api/collections/get
/api/forms/post/contact
```

**Comment by The224** [comment]
I think having both `*` and some path define cause the compilation error. Removing `*` or the paths fix the compilation issue!

**Comment by aheinze** [comment]
`*` doesn't make any sense, as this would allow any route
