### ISSUE TITLE
Rest API specs

### ISSUE THREAD

**Issue by mxrlkn** [agentejo/cockpit#130]
Hi. I'm considering using cockpit as a backend for a frontend javascript framework and communicate through cockpit's REST API.

I have noticed you can put &limit=5 after:
GET /cockpit/index.php/rest/api/collections/get/{collectionname}?token={yourtoken}

Is there any other properties cockpit supports?
What I would really like is to search and filter by fields in a collection.

**Comment by beasteers** [comment]
In the API documentation, you should make it more apparent where the query syntax is coming from. I dug and finally found that both the `fields` and `filter` payloads are in mongolite syntax (or mongodb if you have it set up that way), but you should link to those docs pages and point to instructions so we know how to construct every part of the json body
