### ISSUE TITLE
Fatal error: require(): Failed opening required '/var/www/html/addons/icons/bootstrap.php'

### ISSUE THREAD

**Issue by hsnyc** [agentejo/cockpit#1314]
Hi, I installed Cockpit using [Docker](https://getcockpit.com/documentation/reference/docker).

Everything was going smooth until I tried creating a folder in the Media Library. When I tried to save I got this error 

```
Warning: require(/var/www/html/addons/icons/bootstrap.php): failed to open stream: No such file or directory in /var/www/html/lib/Lime/App.php on line 1150

Fatal error: require(): Failed opening required '/var/www/html/addons/icons/bootstrap.php' (include_path='.:/usr/local/lib/php') in /var/www/html/lib/Lime/App.php on line 1150

```

Re-started the container to see if it would clear but no luck.

**Comment by raffaelj** [comment]
Every addon/module folder **must** have a file `bootstrap.php`. There were discussions about that behaviour multiple times and the simple answer to not check for the existence of this file is performance.
See also: https://github.com/agentejo/cockpit/pull/1019#issuecomment-466158368

**Comment by aheinze** [comment]
Fixed here https://github.com/agentejo/cockpit/commit/9dd6b4c726e4eec19ca217ff77d70501b32be97c
