### ISSUE TITLE
_created value wrong

### ISSUE THREAD

**Issue by wlfnkls** [agentejo/cockpit#1315]
Hey,

is it just me, or is the date value set in "_created" key/value pair incorrect?
For me it gives "1593704209", which leads to:
```
new Date(1593704209)
Date Mon Jan 19 1970 11:41:44 GMT+0100 (Central European Standard Time)
```
But the entry has been created today, somewhere around July 2nd 2020 @ 05:36:49 pm.

Key/value pairs from recent request
```
 "_modified":1593724249,
 "_created":1593704209,
```

Thanks!

**Comment by aheinze** [comment]
```
new Date(1593704209 * 1000);
```

**Comment by wlfnkls** [comment]
Yes, for sure! My fault, thanks for your blazing fast help!
