### ISSUE TITLE
login loop

### ISSUE THREAD

**Issue by buzztnt** [agentejo/cockpit#1318]
I've installed cockpit on shared hosting site domain.com - I'm getting a loop whereby every time I login it returns to the login page.

It's located in a sub domain 'cms.mysite.com' - If I navigate to to this url I get "You don't have permission to access / on this server."

I've tried entering this code on my login.php and got no response:

```
<?php
echo "<pre style='position:absolute;top:0;left:0;'>";//avoid pre to get centered (body CSS)
print_r($_SERVER['DOCUMENT_ROOT']); // may differ from __DIR__
echo "\r\n";
print_r(get_defined_constants(true)['user']); // list all user constants
print_r($app->config['paths']); // list all config paths
echo "</pre>";
?> 
```

I've also tried the following defines.php:

```
<?php
define('COCKPIT_BASE_URL', '/cms');
define('COCKPIT_BASE_ROUTE', '/cms');
define('COCKPIT_DOCS_ROOT', dirname(__DIR__));
?>
```

Any help would be appreciated.

**Comment by raffaelj** [comment]
Did you try to uncomment `RewriteBase /` or e. g. change it to `RewriteBase /cms`?
https://github.com/agentejo/cockpit/blob/next/.htaccess#L38

**Comment by buzztnt** [comment]
Hi @raffaelj yes this sorted my issue.
