### ISSUE TITLE
Assets folder trigger options

### ISSUE THREAD

**Issue by sainf** [agentejo/cockpit#1320]
Using trigger "cockpit.assetsfolders.find.before" works well on the asset list.

But in the asset page, in the right info, the folders list doesn't uses the trigger.
![image](https://user-images.githubusercontent.com/1210947/88019799-76c26780-cb22-11ea-9ef9-12d074418abe.png)

Please check if this patch is acceptable: https://github.com/sainf/cockpit/commit/1fbd328f5e517d272e274e5146d01aeedc45d7ab
(updated link)

**Comment by aheinze** [comment]
Thanks 👍
