### ISSUE TITLE
Allow the use of lexy for page creation.

### ISSUE THREAD

**Issue by nblackburn** [agentejo/cockpit#134]
I am not sure if this is currently possible but it sure would be nice if we could use Lexy to build the website pages with as its's much nicer than combining PHP and HTML together which gives me shudders.

**Comment by amdad** [comment]
```php 
return $app->view('views/article.php', ['article' => $article]);  // WORKS.

return $app->render('views/article.php with template/template.php', ['post' => $post]);  // WORKS.without Lexy

return $app->view('views/article.php with template/template.php', ['post' => $post]); // NOT WORK AT ALL
```
How to add Lexy to $app->render? Or any other way to do this mixed template view?
