### ISSUE TITLE
 Clicking , in any language, closes the tag

### ISSUE THREAD

**Issue by activizator** [agentejo/cockpit#1352]
Clicking , (comma) in any language, closes the tag, when edditing an entry.
But on some layouts, this key does not have a comma, but a letter. And there is no way to write a tag word with this letter (only Ctrl + C & Ctrl + V).

**Comment by fredrikkarlsson-pervanovo** [comment]
I think I solved your issue with #1360 .
What keyboard layout are you using?

**Comment by activizator** [comment]
I use the Russian layout, where the letter "б" is instead of a comma
