### ISSUE TITLE
[BUG] Tags

### ISSUE THREAD

**Issue by desvu** [agentejo/cockpit#1363]
The key with the code 188 is used as comma and RUSSIAN LETTER "Б".
This problem does not allow to enter a Russian word with letter "Б", for example: "Обои".

Please change
`if (e.type=='keydown' && e.keyCode != 13 && e.keyCode != 188) `
to
`if (e.type=='keydown' && e.keyCode != 13) `

**Comment by Raruto** [comment]
Fixed in: https://github.com/agentejo/cockpit/pull/1360 (it should be released in upcoming next version after 0.11.2)
