### ISSUE TITLE
Stored XSS in some areas

### ISSUE THREAD

**Issue by wiedaw** [agentejo/cockpit#1472]
Hello.

After secutiry audit in CMS there are some places where you can inject some javascript code.
For example in fileld like date picker, assets. Could you take a look of this and help me to fix this?

Below is screenshot from API request and response which opens alert by javascript injected code.

![cockpit-cms](https://user-images.githubusercontent.com/27772431/139410664-59e9cf2a-e379-4011-82e9-7bfe24d12716.png)

**Comment by ronaldaug** [comment]
I guess this XSS injection isn't executed in Cockpit dashboard, isn't it? 
And it seems this is correct, the API should return what we posted.
