### ISSUE TITLE
Get unpublished collection items

### ISSUE THREAD

**Issue by adiba** [agentejo/cockpit#1500]
In the API playground below the response text field `GET /content/items/{model}`, the description "Get list of published model items" made me realize that this list is pre-filtered.

How can I get the *entire unfiltered list*, i.e., including unpublished items (i.e., items with `_state=0`)?

Even with `filter={_state:0}`, the result list didn't change (still only published items).

**Comment by aheinze** [comment]
You're at the wrong repository. Please crete your issue here: https://github.com/Cockpit-HQ/Cockpit/issues
