### ISSUE TITLE
UX Suggestion: Dismiss confirmation modal with ESC

### ISSUE THREAD

**Issue by mountainash** [agentejo/cockpit#1501]
When flicking between the different top level menus, the exploration flow is stopped on the "Deploy" section with the forced mouse only interaction with the "Do you want to re-deploy the Website" modal.

<img width="376" alt="Screenshot of the related modal" src="https://user-images.githubusercontent.com/27637/197484743-e3ba3bfc-d089-4356-8494-45632a4bd446.png">

### Suggestions
- [x] allow the "cancel" flow to be actioned by pressing the <kbd>esc</kbd> key
- [x] allow <kbd>tab</kbd> key presses to focus the front-most buttons (currently it tabs through the greyed out content

**Comment by aheinze** [comment]
Hey 👋 You're referring to Cockpit v2 - Please create your issue / suggestion here: https://github.com/Cockpit-HQ/Cockpit

Thanks!

**Comment by aheinze** [comment]
Btw, now fixed here https://github.com/Cockpit-HQ/Cockpit/commit/48ff14341ef7e8018cc153727e37580bb1e8ebf8

**Comment by mountainash** [comment]
Awesome @aheinze  ... Can I suggest [adding a `CONTRIBUTING` file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors#adding-a-contributing-file) to this repo to suggest issues are created on the new repo?

It might save you some comment repition?
