### ISSUE TITLE
Collection links

### ISSUE THREAD

**Issue by nblackburn** [agentejo/cockpit#151]
Not sure when this happened or how but collection links are not loading any more and simply showing...

```
 Linking 53edcdd66c761doc1253542951
```

Even if there is no page linked or upon creating a new one, any ideas?

**Comment by aiamk** [comment]
I am facing the same issue with linked only.

![cockpit-cl-error](https://cloud.githubusercontent.com/assets/10895607/10189747/00ac723a-6771-11e5-9bcd-5b6bee1c956b.PNG)
