### ISSUE TITLE
REST regions show page not found

### ISSUE THREAD

**Issue by michaelkaaring** [agentejo/cockpit#157]
Example:
GET /cockpit/index.php/rest/api/regions/get/info?token=3a5ff07f26f87079dc2bacbd

Then only returns Page not found, instead of region.
And region name is correct.

On latest 0.10.0 (didn't work on previous eather)

BTW, FANTASTIC PROJECT! keep up the good work!

**Comment by iulas** [comment]
Same problem, any request to api/regions/ returns a 404.
