### ISSUE TITLE
way to define the default language

### ISSUE THREAD

**Issue by dospuntocero** [agentejo/cockpit#16]
at the moment the language is defined inside the cockpit folder in config, but there must be a way to define that outside that folder, that way will be easier to update the code without overwritting stuff.

maybe a good way to do that is to define a folder structure like this:

```
/
  cockpit-folder
  mysite
    config - cockpit config that extends/modifies the base configuration (like 18n)
    storage - cockpit database
    media-files - mediamanager base folder
    ...
    all your other site files
```

that way storage is not dependant of cockpit but the site itself

**Comment by mglantz** [comment]
@aheinze as Cockpit defaults to browser language, when you roll out Cockpit in an international setting, you end up with users having very different experiences, as the status of the translations differs a lot. Looking at my languages, Swedish, Danish and German, the state of translations is lacking. 
Would it perhaps make sense to default to english and then allow users to select something else via the account setting?
