### ISSUE TITLE
Limit how many entries in collection?

### ISSUE THREAD

**Issue by peterbrinck** [agentejo/cockpit#250]
Is it possible to limit how many entries there can be in a collection?

Like for a menu, let's say the website only support up to 6 menu items, else its get ugly and buggy.
The menu is linked up with a collection so it's easy to add new pages and menu items, but you can add more entries than the website supports..

I would love a feature that allows me to limit entries.
I could do it when I make the loop, but then the entries are still in the system, but just not shown.. And in my opinion its bad and not good for a normal user/customer

**Comment by aheinze** [comment]
why don't you just limit the output on the front-end to 6?

**Comment by AC10** [comment]
As I said, I think that is a bad way of doing it. Then if I deliver the website to my customer they still can add 6+ entries in the collection, and wonder why nothing is showing up on the front-end

It's not that customer friendly, and especially not if they're not that much into IT

**Comment by aheinze** [comment]
I think this is an edge case...I think about it

**Comment by adaniello** [comment]
+1

**Comment by lukeliasi** [comment]
+1
I think this will be a good feature, I have a case where the user should only enter x amount of items.
