### ISSUE TITLE
Slug updated when editing collection/field

### ISSUE THREAD

**Issue by ghost** [agentejo/cockpit#262]
When editing a collection (or any other item with a slug) the slug will also be updated. Shouldn't a slug be left as is by default since it's a reference to something (URL, place in code, ...)?

Which comes to my next point, why is a collection by default searched for by name and not by slug?

**Comment by florianletsch** [comment]
Hm. Thinking of a slug as a UUID might be the right approach for some applications. But thinking of applications like a blog, I think the current behaviour is fine. A slug will automatically represent the normalised form of a selected field, i.e. the post title. When you've found a typo in the title, you'll want the slug to update automatically.

If you need a field that doesn't change that way, you are still free to add a custom text field that you update manually.

**Comment by piotr-cz** [comment]
I use slug in building URI and so it's helpful to change it. But I believe there could be something like ID that's immutable (ie. for selecting blog posts)
