### ISSUE TITLE
Store Leading Zero in field - error

### ISSUE THREAD

**Issue by thinkink** [agentejo/cockpit#283]
I'm trying to store ids like this 0046546. I suppose cockpit internally converts this value to number, but i need to arrangethis to store as String. 

Which is the best way to solve this?

**Comment by malles** [comment]
I think you'll have to create a string field apart from the actual id. The id must be a integer.

**Comment by thinkink** [comment]
But i create a text field, called for example REFERENCE and when i store a  number like this 0046546, cokcpit remove automatically the two leading zeros. 

It's a bug, i think

**Comment by telekommander** [comment]
This is a bug.
I am trying to use a workaround and stored a number with a leading dot.   **.**
But it gaves me a stored decimal number like **0.01127**

**Comment by jhesgodi** [comment]
We do notice the same. If you have a text field when you add a number as string Eg. `01`  cockpit cast it into `1`. And if you check the API response for the text field, you will get a number, not a string.

In the meantime, our workaround was to add an empty space after. Eg. `01 `

**Comment by thinkink** [comment]
This error persist in **next branch**. The problem i think is in mongolite driver

Add empty spaces after the number sometimes is not a good solution. For example if you store a **SKU** like ``` 00.5464 ```, the result is (as well said @jhesgodi) ``` 0.5464``` .

Some ideas for arrange this.
