### ISSUE TITLE
Can't login when langauge changed

### ISSUE THREAD

**Issue by peterbrinck** [agentejo/cockpit#291]
When the language of the default admin account is changed, I can't login
Even if I through another admin account change the language back to English, I can't login

But if I create another user, and change the language, I can perfectly login with that account
<br><br>

The problem occurs only when the language is changed for a specific account. Because when I change the language through `config.php` it still works.

**Comment by timaschew** [comment]
Ho you were able to change the language via the browser?
I'm trying to do that, but I can only choose English.
