### ISSUE TITLE
How to filter multiple items with Cockpit rest api

### ISSUE THREAD

**Issue by arlg** [agentejo/cockpit#297]
Hi, I want to filter multiple collection items with The Cockpit Js api.
 What i have now : 

```
     Cockpit.request('/collections/get/collection-name', { filter: { "id" : [1, 4, 5] } } ).success(function(item){

        // Stuff

    });
```

It doesn't work like this so I think i am missing something.

**Comment by loick** [comment]
"_id" instead of "id" ?

**Comment by ntdb** [comment]
I was receiving a 404 using this code (with `_id`). Here's the correct code (for Cockpit 0.13.0, note the `$in`):


    Cockpit.request('/collections/get/collection-name', { filter: { '_id': { $in: [1, 4, 5] } } }).success(function(item) {
        // Stuff
    });
