### ISSUE TITLE
Media Path not saving in groups

### ISSUE THREAD

**Issue by gazsp** [agentejo/cockpit#322]
I'm using the master branch and MongoDB, and the following gets saved each time to the `cockpit_settings` collection:

``` json
{
    "_id" : "...",
    "key" : "cockpit.acl.groups.settings",
    "val" : {
        "admin" : [],
        "users" : []
    }
}
```

I think it's a problem on the Javascript side, as `admin` and `users` should be objects, not arrays (I assume).

**Comment by toish** [comment]
I'm having this problem also, an empty array is being sent to saveAci, so it's a JS thing.
<img width="964" alt="screen shot 2016-02-09 at 5 47 53 pm" src="https://cloud.githubusercontent.com/assets/8439945/12933305/672ba250-cf55-11e5-8787-5b7d97797e5d.png">
