### ISSUE TITLE
Multilanguage region field

### ISSUE THREAD

**Issue by crealx** [agentejo/cockpit#325]
Hello,
I'm using with a real pleasure the multilanguage feature.
But I have a little issue : I want to display a specific translated field of a region :

```
echo cockpit('regions:region_field', 'faq', 'seo_title', 'value', 'fr');
```

But it doesn't works. I tried others : I can't have my translation.
Can someone help me ?

Thank you!

**Comment by adis-me** [comment]
Indeed, I cannot find documentation about rendering regions in a specific locale. Looking in the source code I only saw that the `$locale = null` is removed from the `render` [signature](https://github.com/COCOPi/cockpit/blob/next/modules/Regions/bootstrap.php#L146) in **Next**.
