### ISSUE TITLE
[Cockpit REST API] get everything with one call

### ISSUE THREAD

**Issue by loick** [agentejo/cockpit#329]
Hi everyone, 

I'm currently trying to get my datas from cockpit with the javascript API. This is working very well but when I have a field which get the datas from another collection, i only get an id from the call. I wanted to know if there is a way to get the name of this collection with the initial get call.

For exemple  

I have an article collection and a category collection. My article collection as a field to be linked to a collection. But when i try to get every articles with the get API, i only get the category id, or I would like to get the title of this category. 

Any ideas ?

**Comment by aheinze** [comment]
not via js, sorry. you can make your own module to proxy the request and return the desired result. 
to attach linked collection items, take a closer look at https://github.com/aheinze/cockpit/blob/master/modules/core/Collections/bootstrap.php#L82

```php

// get all posts with linked collections resolved
$linkedresult = cockpit('collections')->populate('posts', cockpit('collections')->find('posts')); 

```

**Comment by loick** [comment]
Okay good to know, thanks for your response :)
