### ISSUE TITLE
Unable to use layout

### ISSUE THREAD

**Issue by rachael-pe** [agentejo/cockpit#345]
Hello, I am having problems with the index file. I am able to get a simple function (Hello World) to work properly, but can not get anything else to work. I have gotten styles to work by using php include, but when that works, any functions do not. It is like either styles work or functions work, not both collectively.

I saw another question similar, and tried a different method that this user used; this "layout" call, and having the styles in another file to be called with this. Running this code, the "Hello World" function works, but the layout does not render. I am not getting any errors in my error log file. My code is below, if you could please tell me how to get this working with either includes, or this method, or some other method I am unaware of, I would really appreciate it!

<?php
//include cockpit
include_once('../bootstrap.php');
//app-function
$app = new Lime\App();
$app->layout = "includes/head.php";
$app->bind("/", function() {
return "Hello World!";
});
$app->run();
?>

**Comment by rachael-pe** [comment]
Tried something else, displays "Path not found." No errors. Please help : )

<?php
//include cockpit
include_once('../bootstrap.php');
//app-function
$app = new Lime\App();
// bind routes
$app->bind("/", function() use($app) {
$app->layout = "user/layout.view.php";
});
$app->run();
?>

**Comment by manudurgoni** [comment]
I don't really understand what you want to do.

But to start with Cockpit, take a look at this tutorial : http://getcockpit.com/docs#!tutorials/simple_blog

**Comment by findborg** [comment]
I think what you need to do is use regions.  Then you can create your Header Region - Footer Region and so on.
