### ISSUE TITLE
Lime attempts to load .svn directories as modules

### ISSUE THREAD

**Issue by charkes** [agentejo/cockpit#348]
I prepared a site with Subversion.  When I checked out the site on the production server, I had an error about Lime attempting and failing to load modules in cockpit/modules/addons/.svn and cockpit/modules/core/.svn.

The loadModules code checks if the directory item is a file or a dot (. or ..) directory.  Perhaps it needs to also block "hidden" dot-directories?

https://github.com/aheinze/cockpit/blob/master/vendor/Lime/App.php#L1224

**Comment by piotr-cz** [comment]
I'm not using SVN anymore, but shouldn't the folder be located rather within module folder (in `cockpit/modules/addons/[mymodule]`)? At least this is where I plan to put my .git.

**Comment by aheinze** [comment]
@charkes is right. svn puts ```.svn``` in **every** folder. I didn't thought that anybody uses it these days :-D

**Comment by charkes** [comment]
I'm still learning git -- as seen from the extra commits sprinkled in my pull requests from me keeping up with master commits from @aheinze.  The commands seem to flow in a different 'direction' from svn.
