### ISSUE TITLE
Can't acces /rest/api-js on digital ocean server

### ISSUE THREAD

**Issue by TimRoussilhe** [agentejo/cockpit#350]
Hello,

First thanks for the work on cockpit really enjoy my first experimentation with it.

On local i don't have any issue and it's really pleasant to use.

I tried to deploy on a digital ocean droplet. Here again no specific issue. I can acces the cms and manage my datas.

The only issue is when i try to connect the API to my front-end i get a 404 issue.

/cms/rest/api-js?token={} won't work
But /cms/ is working fine and dispay the admin panel.

The project is hosted here : var/www/htlm

Do you think there is a document root issue or something to set up ?

**Comment by malles** [comment]
It has to do with the mod_rewrite setting, or the correct detection of it. 
Try setting `$_SERVER['COCKPIT_URL_REWRITE'] = 'On';` by pasting it on line https://github.com/malles/cockpit/blob/master/index.php#L9, see what that does.
