### ISSUE TITLE
Captcha for forms

### ISSUE THREAD

**Issue by crealx** [agentejo/cockpit#352]
Hello,

I saw that we can create a custom form validation.
But I can't make recaptcha from google working.
Is there someone who already done a captcha validation form with Cockpit ?
Thank you !

**Comment by peterbrinck** [comment]
@malles made this fantastic module/plugin for Cockpit!

https://github.com/Bixie/cockpit-recaptcha

**Comment by crealx** [comment]
Awesome !
I will check this one, thank you

**Comment by malles** [comment]
@peterbrinck Thanks!
@crealx If you need any help, hook up on the cockpit (gitter)[https://gitter.im/aheinze/cockpit], you can find me there.

**Comment by folusuk** [comment]
Hi can you please tell me where i can change the language of the recaptcha thank you

BTW fantastic Plugin thank you for all your work

**Comment by peterbrinck** [comment]
@folusuk 

I think it's a long stretch since the plugin is 3 years old and was build for the legacy version of Cockpit

**Comment by folusuk** [comment]
I appreciate that however my client is using all legacy and doesn’t want to upgrade, an I just need change recaptcha v2  from en-US to ru-RU

**Comment by peterbrinck** [comment]
I think it's possible by editing `bootstrap.php`

https://github.com/Bixie/cockpit-recaptcha/blob/master/bootstrap.php#L38
Just add `?hl=ru` after `api.js`

**Comment by folusuk** [comment]
that worked great thank you so much

**Comment by jimmytricks** [comment]
Late to the party but if anyone else is struggling with adding recaptcha, I created a PHP/cURL workaround. Have shared the files here in case it's useful to anyone else:

https://github.com/jimmytricks/Cockpit-with-cURL-and-ReCAPTCHA

Cheers :)
