### ISSUE TITLE
Form not working on a server

### ISSUE THREAD

**Issue by arlg** [agentejo/cockpit#359]
Hi,

I am using Cockpit to generate a form with a user name and an e-mail input.

It works locally : the form validates. In my remote server I get a 500 error when I submit the form.

I use the same .htaccess and configuration. What could I have missed ?

**Comment by peterbrinck** [comment]
Does the form send and email to you, or does it just store the information in Cockpit?

**Comment by arlg** [comment]
It just stores the user data in the Admin

**Comment by peterbrinck** [comment]
Then I don't know..
If it was send as an email, it probably would be the email configuration

But you can joins us on the [Gitter chat](https://gitter.im/aheinze/cockpit), it's a bit faster support

**Comment by arlg** [comment]
I managed to find the problem, it comes from my validation : 

users.php : 

    if ( !empty( $app->param('form/name') ) && !empty( $app->param('form/email') ) ){

	    return true;

    }

Is there something wrong in this code ?
