### ISSUE TITLE
[Collections] Entries filter in the Cockpit backend works only on the first field of the collection

### ISSUE THREAD

**Issue by franza83** [agentejo/cockpit#364]
HI!

Filtering collection entries in the Cockpit backend by using the search field, I get almost always "No entries found" ... 

It seems that queries return entries ONLY IF the typed string matches the contents of the FIRST field (in the order defined by the sortable list in the collection editor) of the collection.

I checked "entries.js" in /modules/core/Collections/assets/js/ folder and the 'loadmore' function seems to collect ALL the text/code/html/wysiwyg fields (I've added also "select" type...) of the collection for generating the search criterias of the query. It shoud be something like this:

{"$or":[
{"field>":{"$regex":"searchkey"}},
{"field2":{"$regex":"searchkey"}},
...
{"fieldN":{"$regex":"searchkey"}}
]
}

I think that the bug is on a server-side component...
I tried to check functions in Collection Api.php and Mongolite components but I don't understand so much.... :( 
Can anyone help me?

**Comment by nailliK** [comment]
I'm looking for a solution to this as well. Any luck?

**Comment by webcliq** [comment]
Implementing the Cliq alternative Collections module solves all of this.

**Comment by nailliK** [comment]
Thanks, @webcliq. Do you have a version that works for the original Cockpit?

**Comment by nailliK** [comment]
@webcliq: I tried implementing your alternative collections module, but it appears to be missing some files?
