### ISSUE TITLE
Territory specific locales

### ISSUE THREAD

**Issue by jorrit** [agentejo/cockpit#383]
A typical locale definition contains a language and a territory (see [this](https://en.wikipedia.org/wiki/Locale)). Cockpit only supports languages which means that I can't have separate content for American English and British English. I'd like to request this feature.

**Comment by Tails** [comment]
+1

**Comment by gryphonmyers** [comment]
In NEXT you can specify your own arbitrary languages as an array in the config file, so you could theoretically create en-US and en-GB as separate "languages." I plan on using the feature in this way.
![image](https://cloud.githubusercontent.com/assets/5785304/15752414/d513d7be-28a2-11e6-980d-d48be9a53fb1.png)

**Comment by woutervddn** [comment]
Does this mean we can close this now @aheinze ?
