### ISSUE TITLE
Usage of API in "next" branch? 

### ISSUE THREAD

**Issue by amtmolecule** [agentejo/cockpit#387]
Hi, how can i generate a token and use the API in the "next" branch?

**Comment by aheinze** [comment]
API requests are not implemented yet for the next-branch

**Comment by jbcoder** [comment]
If I'm not mistaken, I believe this has been taken care of by now. You can head over to <yoursite>/restadmin/index to generate one now.

**Comment by gryphonmyers** [comment]
I can confirm that REST API does work, but the URL has changed: cockpit/api/collections/get/{{collectionName}}?token={{apikey}}

**Comment by nebnes** [comment]
The api work also to get thumbnails ?

**Comment by jobsturm** [comment]
It doesn't work for thumbnails am I correct?
