### ISSUE TITLE
Bug: Boolean Field Doesn't Change

### ISSUE THREAD

**Issue by che-wf** [agentejo/cockpit#401]
I added a boolean field in one of my collections. When I went to fill out the entry, the field doesn't turn "on". It just stays on "off" when I click on it. 
![screen shot 2016-03-25 at 16 02 31](https://cloud.githubusercontent.com/assets/1719239/14055893/ea9293fe-f2a2-11e5-8f12-9bf5fbf2fce3.png)

**Comment by aheinze** [comment]
Thanks, I will check this
