### ISSUE TITLE
Bug: multiple field does not work with collection link field

### ISSUE THREAD

**Issue by gryphonmyers** [agentejo/cockpit#405]
If I add a multi field to my collection and choose the "collection link" as an allowed field type, I would expect to be able to specify which collection is a valid selection for the multi field.

![image](https://cloud.githubusercontent.com/assets/5785304/14393486/19f9b206-fd7c-11e5-9b87-03277d4d304f.png)

Instead, when I add collection link as an allowed field type and then go to add an entry to this collection, I am able to choose from all field types except collection link:

![image](https://cloud.githubusercontent.com/assets/5785304/14393536/5610c18a-fd7c-11e5-9086-1ae5b7eeabc4.png)

I would be willing to attempt a fix for this with some general direction of where to look. Thanks

**Comment by LiamMartens** [comment]
I kind of believe collection link is somwhat broken in the latest version of Next

**Comment by gryphonmyers** [comment]
Liam - this issue is particular to the legacy version. If you noticed a bug
with the next branch you should create a new issue describing it in as much
detail as possible. Thanks!
