### ISSUE TITLE
Post by using REST API

### ISSUE THREAD

**Issue by utamir** [agentejo/cockpit#425]
I saw an outdated topic about it, however, it seemed that it is still impossible to post data by using REST API, even for tests. 
Am i missing something? I am looking to migrate large website into Cockpit and i see no real way of doing it in batch mode.

**Comment by aheinze** [comment]
Do you use Cockpit Next or Cockpit Legacy?

**Comment by utamir** [comment]
I am using master from archive. So i am assuming it's legacy

**Comment by aheinze** [comment]
yepp, I'm working on an importer tool for collections in Cockpit Next. For the Legazy version you maybe should try https://github.com/piotr-cz/cockpit-import.

**Comment by utamir** [comment]
thank you. However, i am not sure it will work with the large number of entries.  Is this solution will workable http://getcockpit.com/blog/import-data-into-cockpit-collections#disqus_thread ?
Also this is not really clear to me what to do with _uid and _id fields.
