### ISSUE TITLE
Request header field Content-type is not allowed by Access-Control-Allow-Headers in preflight response

### ISSUE THREAD

**Issue by wiven** [agentejo/cockpit#427]
When I try executing the code
`Cockpit.request('/collections/get/xxx').success(function(items){
        console.log(items);
    });`
in JavaScript I get an error saying `XMLHttpRequest cannot load https://mydomain.com/admin/rest/api/collections/get/xxx?token=yyy. Request header field Content-type is not allowed by Access-Control-Allow-Headers in preflight response.` The JS file has been included from another domain. Is there a way I can work around this?

**Comment by JesperWe** [comment]
This is configured in the web server settings. If you are running behind Apache2 you can modify the .htaccess file to add the `access-control-allow-content-type` header. Behind nginx it is more difficult. I would recommend running Cockpit behind Apache unless you are very familiar with nginx configuration.
