### ISSUE TITLE
Error on new server: No input file specified.

### ISSUE THREAD

**Issue by peterbrinck** [agentejo/cockpit#435]
I recently moved to a new server, with a new setup (very similar to the old), but now pages, on some of my older Cockpit installations doesn't work and gives me this error: `No input file specified.`
But every page on the backend/admin works, it's just the frontend that doesn't work

I have no idea what the problem is or what could cause it.

It's Cockpit 0.13.0

**Comment by aheinze** [comment]
which webserver do you use? ist it apache? did you enable mod_rewrite?

**Comment by peterbrinck** [comment]
Yes to both

I'm using Webmin with Virtualmin to control the server, and Webmin installed the PHP environment etc.
And then I've installed some modules, like SQLite

The old Cocopi starter package works just fine

**Comment by peterbrinck** [comment]
@aheinze

**Comment by aheinze** [comment]
can't say anything without looking at it on the server ... maybe you can send me the credentials, so I can investigate the issue

**Comment by peterbrinck** [comment]
Sure
I'll just email you

**Comment by n30nl1ght** [comment]
Hi i have an problem like this.

I have installed Cockpit 0.13.
I have the cockpit folder in the root, but when i try to open come an error.

![Error : No input file specified.](https://cloud.githubusercontent.com/assets/15847494/19432774/4290ecba-945e-11e6-8886-221280af1b5d.png)

its an clean install of cockpit like the documentation.
![Install](https://cloud.githubusercontent.com/assets/15847494/19432816/6fb6a676-945e-11e6-8c9e-dc10f7b35f74.png)


And the other question.
How i can use the cockpit API with angular.
Everytime come the error
![Api error](https://cloud.githubusercontent.com/assets/15847494/19432918/cf63529a-945e-11e6-9ad2-8f9fb62093ad.png)

The code 
![code](https://cloud.githubusercontent.com/assets/15847494/19432932/e09454b0-945e-11e6-8c8a-6563b45ea4af.png)

Thx for help
