### ISSUE TITLE
[Next] Fields nested within repeater are not localizable 

### ISSUE THREAD

**Issue by gryphonmyers** [agentejo/cockpit#453]
Field specifications in the repeater options object do not appear to use the localize flag. I tried two versions:

```
{
  "fields": [
    {
      "type": "set",
      "options": {
        "fields": [
          {
            "type": "text",
            "name": "key"
          },
          {
            "type": "text",
            "localize": true,
            "name": "value"
          }
        ]
      }
    }
  ]
}
```

```
{
  "fields": [
    {
      "type": "set",
      "localize": true,
      "options": {
        "fields": [
          {
            "type": "text",
            "name": "key"
          },
          {
            "type": "text",
            "name": "value"
          }
        ]
      }
    }
  ]
}
```

Neither of these swapped the content out when changing languages. 

Note: this is different (subtly so) than localizing the repeater field itself (which DOES currently work). Use case for this feature: say I have a "dictionary" repeater field that I want to localize into different languages. I add three words to the repeater and fill in English values. With the localize flag set on the repeater, when I switch to German I have an empty slate - if I want to translate the same words I added in English, I have to add them over again. In this particular case, it would be better if I could instead add the localize flag to the field within the repeater: it would keep the fields I had previously added when I switch languages, but would allow me to swap the values only.

**Comment by aheinze** [comment]
this is one use/edge case, but it is a pretty complicated topic. as you described there is a possible way to handle it. for now, there are more important issues to solve ;-)

**Comment by gryphonmyers** [comment]
Agreed! I hope you don't mind me leaving issues like this around - reminders for later

**Comment by aheinze** [comment]
Sure, suggestions are always welcome 👍

**Comment by JesperWe** [comment]
Just like to +1 this for a use case like this: Building a localizeable "Page" entry where a page consists of a few fixed fields (title, route etc) plus a "Content" repeater with all the content blocks for that page. Again, if the entire Content is localized, the editor needs to add all the blocks to the page for each language, instead of just translating the fields that need localization.

**Comment by gryphonmyers** [comment]
That is pretty much exactly what I need it for! It is already a really
great setup but that extra piece would make data entry so much better

**Comment by mcapu** [comment]
Are there any plans to add this feature? Did anybody find a workaround for it?

**Comment by JesperWe** [comment]
@mcapu There is no "workaround" really. What we do is I help my editors by manually copying one language to the other in MongoDB when they create new complex pages :-P

**Comment by gryphonmyers** [comment]
Yeah I haven't found anything better than what @JesperWe suggests, unfortunately.

**Comment by JesperWe** [comment]
Actually, now that I think about it, having a UI command to do that copy (Copy the `Content` from one language to another) would be rather nice... ;-)
