### ISSUE TITLE
After auth, dont redirect to dashboard

### ISSUE THREAD

**Issue by bartmanskyi** [agentejo/cockpit#457]
Hi
After fresh install and typing admin admin i have not redirected to dashboard. 
I must manually go to this page

**Comment by JesperWe** [comment]
If you want good help from the community you need to provide more specific information:

- What Cockpit version (master or next branch)?
- What webserver are your running behind?
- Have you checked your browser console for error messages?

**Comment by bartmanskyi** [comment]
i found where problem is.
just set `always_populate_raw_post_data = -1` in php.ini
you need set this info in the Cockpit requirements, because latest version xampp go without this option
