### ISSUE TITLE
No input file specified. & API without PHP

### ISSUE THREAD

**Issue by n30nl1ght** [agentejo/cockpit#479]
Hi :-)

I have installed Cockpit 0.13.
I have the cockpit folder in the root, but when i try to open come an error.

![Error : No input file specified.](https://cloud.githubusercontent.com/assets/15847494/19432774/4290ecba-945e-11e6-8886-221280af1b5d.png)

its an clean install of cockpit like the documentation.
![Install](https://cloud.githubusercontent.com/assets/15847494/19432816/6fb6a676-945e-11e6-8c9e-dc10f7b35f74.png)

**Info. I use Homestead!**

And the other question.
How i can use the cockpit API without php?
Everytime come the error
![Api error](https://cloud.githubusercontent.com/assets/15847494/19432918/cf63529a-945e-11e6-9ad2-8f9fb62093ad.png)

The code 
![code](https://cloud.githubusercontent.com/assets/15847494/19432932/e09454b0-945e-11e6-8c8a-6563b45ea4af.png)

Thx for help

**Comment by aheinze** [comment]
which php version do you use?

**Comment by n30nl1ght** [comment]
PHP 7.0
