### ISSUE TITLE
Cockpit Next: I get a 404 when I call the JS library the documented way.

### ISSUE THREAD

**Issue by jobsturm** [agentejo/cockpit#488]
If I use the documented
```
    <script src="/cockpit/rest/api-js?token={api_token}"></script>﻿
```
an 404 occurs.

**Comment by davidprati** [comment]
The same thing for me, and can't access to localhost:8888/cockpit/rest/api/collections/get/collectioname?token=tokenID

**Comment by davidprati** [comment]
The same for me. Is there another syntax or url to specify ?

**Comment by julienchazal** [comment]
Hello. Same here. @jobsturm @davidprati did you get this working ?

**Comment by jobsturm** [comment]
I did not.
