### ISSUE TITLE
Cockpit Next: JavaScript API, how to create thumbnails?

### ISSUE THREAD

**Issue by jobsturm** [agentejo/cockpit#489]
I can't get the basic example that is used in the tutorial to work:
```    
   Cockpit.request('/mediamanager/thumbnails', {
        images: ['site:image1.jpg', 'image2.png'],
        w: 50, h:50,
        options: {
            quality : 80,
            mode    : 'crop'
        }
    }).success(function(items){
        // array of thumbnail urls
    });
```
It just returns a 404: "Path not found."

**Comment by pozylon** [comment]
Before commit https://github.com/COCOPi/cockpit/commit/557d6ada3dc75bda95287691f04b9743f82f4945 it was /api/image instead of /mediamanager/thumbnails, now it's gone completely i think.
