### ISSUE TITLE
Fatal error: Class 'LimeExtra\App' not found in C:\wamp\www\portfolio-2017\build\cockpit\bootstrap.php on line 93

### ISSUE THREAD

**Issue by jobsturm** [agentejo/cockpit#496]
I am running Cockpit on Wamp, windows 10. The repo works fine on another machine, but on my desktop I get this error.

**Comment by wondergiant** [comment]
Did you ever have any luck fixing this? I get the same issue. Works fine locally, but on my server it throws that error.
