### ISSUE TITLE
Read-only API Tokens and data security

### ISSUE THREAD

**Issue by salvatorecriscioneweb** [agentejo/cockpit#500]
Hi,

thanks for wonderful work btw i have an issue and coudn't find any question everywhere ( g+ community, past issues, etc... )

API Tokens generated by backend are strictly read only? Could someone post or delete something by using JS Api Rest interface?

It's just a question and not real issue, because for mine project i need high level of security.

I found 2014 post about read only tokens, and v13 release support it but can't found anything about it.
I saw there's no documented post method using rest api, am i right?

Thanks alot

**Comment by aheinze** [comment]
Hi,

yes, the api is read-only.

Greets,
Artur

**Comment by peterbrinck** [comment]
Will it be possible, in the future, to post something to a collection etc.?

**Comment by aheinze** [comment]
Hi Peter,

I'm not sure for now, because this comes with security concerns. I'm still looking for a secure way to implement this.

**Comment by peterbrinck** [comment]
Yes, of course

I haven't worked that much with API's, so I don't have any ideas on how it could be added in a secure way
A simple solution, I guess, would be to generate multiple tokens, and give them different access rights?

**Comment by salvatorecriscioneweb** [comment]
> Will it be possible, in the future, to post something to a collection etc.?

You can always create custom php code for workaround that work like js api, in php it is possible add. You need to manage security aspect btw.

> I'm not sure for now, because this comes with security concerns. I'm still looking for a secure way to implement this.

> I haven't worked that much with API's, so I don't have any ideas on how it could be added in a secure way. A simple solution, I guess, would be to generate multiple tokens, and give them different access rights?

The only "secure" mode that i can think is manage cockpit to support one-time authentication tokens, with good definited access rule.

Example: You have user that need to add post to collection "test"

1. User A login with user / passwd to your site, on login server create and provide new token.
2. Ui handle request and post data using one time generated token and check if user that is doing request is the same that request token to post api
3. Handle request
4. Tokens was destroy after session ends.( logout / disconnect from your site )

I don't think it's secure enought and i know it's not easy to implements, so it's just my thought :)

**Comment by iamso** [comment]
@aheinze according to this https://getcockpit.com/documentation/modules/collections it is apparently possible to post to the API. Can you please show how this can be disabled/prevented? I think this is somehow related to #589.

Thanks.
