### ISSUE TITLE
Unique slugs (next)

### ISSUE THREAD

**Issue by ineentho** [agentejo/cockpit#501]
As far as I can see, there's no way to enforce an unique slug in cockpit next. This forces us to use URLs such as /news/58541375423d3doc1761310462/my-slug instead of a much more clean /news/my-slug.

What are your thoughts on this? Should we create a separate slug field in addition to the existing {slug: true} option available on text fields, or should we somehow make the slug provided with text fields editable?

**Comment by aheinze** [comment]
Hi,

yes you're right the slug functionality is pretty simple. What you can do is to create a custom bootstrap.php in the config folder and hook into ```collections.save.before.{$collectionname}``` event and make sure that your slugs are unique.

Greets,
Artur

**Comment by ineentho** [comment]
Thanks, that's a pretty good solution, I will probably go with that for now. Still, it's not a complete solution for some (edge)cases like if I want two posts with the same title but different slugs.

Is that something that you want fixed by a separate slug field that auto generates slugs based on a specified field (like the title) until the slug field is edited (maybe a flag is set slug_field_name_custom = true)?

**Comment by BenRoe** [comment]
I am new. Can some post an example how to use urls like this /news/my-slug

**Comment by BenRoe** [comment]
Can someone @ineentho @aheinze post a example bootstrap.php

**Comment by aheinze** [comment]
create a file ```bootstrap.php``` in the config folder with the following code:

```php
<?php

$app->on("collections.save.before.{$collectionname}", function($name, &$entry, $isUpdate) {
  // custom code to modify $entry before saving
});
```

hope this helps.

**Comment by BenRoe** [comment]
Thanks @aheinze but it does not help. I am Front-End guy and have rudimentary php knowledge.

**Comment by gryphonmyers** [comment]
Correct me if I'm wrong, but wasn't there a "unique" flag for fields in the legacy version of Cockpit? What is the thinking behind removing it? You are right that the hooks are there to do it ourselves, but it does seem like fundamental functionality for a CMS.

**Comment by aheinze** [comment]
@gryphonmyers there was no unique option, just a slug option for text fields which behaved like in Next

**Comment by piotr-cz** [comment]
I've added a functionality to set flag on slug to be unique within selected collection in previous version here https://github.com/COCOPi/cockpit/pull/338 and here https://github.com/COCOPi/cockpit/pull/341.

However since PRs have been merged there was no new release.

**Comment by gryphonmyers** [comment]
THAT is where I saw it, I knew I wasn’t crazy!

**Comment by piotr-cz** [comment]
No, you are not.

**Comment by fabianmu** [comment]
Here's a solution which works fine for me to create slugs automatically: https://gist.github.com/fabianmu/5f73a6c2303e08add4e00dc2e548ef2d
You just need to replace the name of the collection `aktuelles` and the entry's field which you want to base your slug on, `name` in my case.

In case you create an entry with `name` = `test` it would store `test` as slug for the first creating, another entry with the same `name` will have `slug` = `test-1`.

**Comment by raffaelj** [comment]
@fabianmu I modified your script with the annotations from Artur and I rewrote it to make it more flexible.

https://github.com/raffaelj/cockpit-scripts/blob/master/unique-slugs/bootstrap.php

**Comment by gabrielnvg** [comment]
> Here's a solution which works fine for me to create slugs automatically: https://gist.github.com/fabianmu/5f73a6c2303e08add4e00dc2e548ef2d
> You just need to replace the name of the collection `aktuelles` and the entry's field which you want to base your slug on, `name` in my case.
> 
> In case you create an entry with `name` = `test` it would store `test` as slug for the first creating, another entry with the same `name` will have `slug` = `test-1`.

Changes with @aheinze suggestions:

(Just change the "XXX" occurrences with your collection name and "YYY" occurrences with the entry you want your slug to be based on)

```php
<?php

// this is in the `/config` folder

// collection: XXX
// slug is created bt reading this field: YYY

$app->on("collections.save.before.XXX", function($YYY, &$entry, $isUpdate) use ($app) {

    // generate slug on create only or when an existing one is empty
    if (!$isUpdate || ($isUpdate && trim($entry['slug']) == '')) {
        // generate slug based on defined entry
        $slug = $app->helper('utils')->sluggify($entry['YYY']);

        // count existing entires in collection with given $slug
        $entries = $app->module('collections')->count('XXX', ['slug' => $slug]);

        // if slug is existing already, postfix with incremental count
        if ($entries > 0) {
            $slug = "{$slug}-{$entries}";
        }
        $entry['slug'] = $slug;
    }
});

```
