### ISSUE TITLE
[Next] Display values not updated when collection link value changed

### ISSUE THREAD

**Issue by gryphonmyers** [agentejo/cockpit#506]
1) Create a collection with a collection link field that is set to display on the entries view. Create an entry in this collection and link to an entry. Note the value that appears in the list as you add the entry reference.
2) Go to linked entry and change the field referenced by the display value. 
3) Go back to original entry.
4) Note that the value in the list is now outdated.
5) Go the entries view - the value in the column is also outdated here.

**Comment by merizoto** [comment]
+1

**Comment by macmacs** [comment]
Sadly, this is still an issue. Would be great, if there was a possibility to fix this. It would reduce the clients load if the data was returned by the API and not dependend on another API call.
