### ISSUE TITLE
[Next] Use of custom sort order feature corrupts data in collection

### ISSUE THREAD

**Issue by gryphonmyers** [agentejo/cockpit#508]
1. Create a collection with "sortable entries" checked.
2. Create some entries in this collection
3. On the entries view, drag to reorder them. It displays a notification informing you that the entries have been reordered.
4. Refresh the page. Note that all entries are now completely blanked out with no data. Upon checking entries in database (MongoDB in this case) they no longer have data for the appropriate schema.

**Comment by gryphonmyers** [comment]
Yes I just reproduced again using latest from next branch

**Comment by gryphonmyers** [comment]
```javascript
// result of /find call before reordering
{
    "entries": [
        {
            "_id": "5acbea32d8aa88f94f8b4569",
            "field1": "asgadg",
            "field2": "gadfg",
            "field3": "asd",
            "_mby": "57d07cfbd8aa887b468b4567",
            "_by": "57d07cfbd8aa887b468b4567",
            "_modified": 1523313202,
            "_created": 1523313202
        }
    ],
    "count": 1,
    "pages": 1,
    "page": 1
}

// result of /save call after reordering
{
    "result": [
        {
            "_id": "5acbea32d8aa88f94f8b4569",
            "_order": 0,
            "_modified": 1523313272
        },
        {
            "_id": "5acbe8d5d8aa8812508b456d",
            "_order": 1,
            "_modified": 1523313272
        }
    ]
}

//result of /find call after subsequent /find call
{
    "entries": [
        {
            "_id": "5acbea32d8aa88f94f8b4569",
            "_order": 0,
            "_modified": 1523313272
        }
    ],
    "count": 1,
    "pages": 1,
    "page": 1
}
```

**Comment by gryphonmyers** [comment]
This may be a MongoDB-specific bug, have you tried it using a MongdoDB installation?

**Comment by aheinze** [comment]
yes, I tried v3.6.3 🤔

**Comment by gryphonmyers** [comment]
We are on 2.6.11 maybe that's why

**Comment by aheinze** [comment]
Which php mongodb driver version are you using? - https://github.com/mongodb/mongo-php-driver

**Comment by gryphonmyers** [comment]
php55u-pecl-mongo-1.6.14-1.ius.centos7.x86_64

**Comment by aheinze** [comment]
so you're using the deprecated mongo lib instead of https://pecl.php.net/package/mongodb ?

**Comment by gryphonmyers** [comment]
Apparently so! Unfortunately CentOS / RHEL has all kinds of way outdated software as default. I can push devops guys to upgrade us if we are using unsupported software. I'll start with asking them to upgrade our mongodb driver and see if that addresses the issue.

**Comment by gryphonmyers** [comment]
Updating the mongo driver fixed it! Thanks for your help on this
