### ISSUE TITLE
Collection Field of type Reference (to another collection, multiple) not able to do the entry

### ISSUE THREAD

**Issue by mKadiyan** [agentejo/cockpit#527]
Release : cockpit-0.13.0

I have created a collection field of type reference (to another collection, multiple), but when i try to do the entry, Referenced collection list not coming. Not sure , how to add the reference.

**Comment by gryphonmyers** [comment]
I would need a little more to go on to help you debug. Perhaps a screenshot of the options you're passing to the field?
