### ISSUE TITLE
[Next] Boolean fields not queryable on REST API

### ISSUE THREAD

**Issue by gryphonmyers** [agentejo/cockpit#529]
Steps to reproduce: 
1) In a Cockpit instance using MongoDB (perhaps SQLite as well, this was not tested there though), create a collection with a boolean field.
2) Create at least one entry for each boolean state.
3) Attempt to query these entries on the REST API, something like: http://mycockpitinstance/cockpit/api/collections/get/myCollection?token=myToken&simple=1&filter[myBooleanField]=true
4) Note that 'true', 'false', '0' and '1' in the URL all yield no results. 

Expected results:
In the past, I believe 0 and 1 were correctly coerced to boolean values. I think 0 and 1 encoding of bools in URLs is pretty standard, so that is probably the desired / expected way to query these entries.

**Comment by aheinze** [comment]
Hi Gryphon,

this is why I would never recommend to query the api with GET parameters (it works by accident but was never planned). Instead use a request as ```application/json``` with a json object containing your filter params (e.g. curl):

```
curl -H "Content-Type: application/json" -X POST -d '{"filter":{"myBoolean":true},"simple":true}' http://mycockpitinstance/cockpit/api/collections/get/myCollection?token=myToken
```

Greets,
Artur

**Comment by gryphonmyers** [comment]
Oh, I see. That's disappointing as the (unintentional) support for GET parameters made the REST API very versatile. Are there concerns beyond parsing of bools? I wonder if supporting this would be as simple as changing a === to a == somewhere...?

**Comment by gryphonmyers** [comment]
I am coming back to this issue and I must say I think it is a mistake to not officially support GET requests. Reasoning:

- It seems like a semantic misuse of HTTP protocol. POST is intended for updating data, but filter / sort / skip are query params. I am not updating anything on the server when I use them.

- POST requests are typically uncacheable. If I, let's say from the front end, request a resource with my query params in the body, my browser does not now how to cache that differently from another resource on the same server, with different query params. 

- CORS preflight overhead. If I make a CORS request to a resource from my Cockpit server, a POST request is treated differently than a GET request. POST requests are required to go through a preflight step which is slow and wasteful, considering all I want is to make one request to GET some data. 

Generally, it just makes no sense for me to do an AJAX POST when all I want to do is GET data from the server.

**Comment by aheinze** [comment]
Hi Gryphon,

I think I could find a way to solve this, please checkout the current codebase of the next branch.

Thanks!

**Comment by gryphonmyers** [comment]
Oh wow, OK so that does work but only if the param is in fact passed as a query param. If you pass a bool-like string as a POST var it will not coerce the value. Maybe that makes sense since only GET vars suffer from this problem of all being encoded as strings...

**Comment by aheinze** [comment]
also POST vars if they are `application/x-www-form-urlencoded` (e.g. submitting a form) but I don't think it makes sense to address this too 🤔

**Comment by gryphonmyers** [comment]
Oh right that's true. Personally, I think it might make sense to support `application/x-www-form-urlencoded` IF there was an actual payload being delivered / written to db. Main strength I can see of supporting it would be ease of use with HTML forms that utilize FormData API (i.e. rather than having to gather all my data from my inputs and encode to JSON, I can just submit the FormData object). It is not an implementation I personally use, but might make sense to support at some point!

In any case I'll mark this closed since the issue I brought up has been addressed
