### ISSUE TITLE
[Next] New collection link populate algorithm is not reverse-compatible with legacy DB entries

### ISSUE THREAD

**Issue by gryphonmyers** [agentejo/cockpit#533]
I am not sure how much action you want to take on this one, but I noticed that the recent changes to the way collection links are populated on the REST API have broken the feature for DB entries created by older versions of Cockpit. So, a user who upgrades to the new version will suddenly not be able to populate any of their data. 

I would suggest some sort of DB maintenance / updater tool to solve problems like this going forward. It should be able to detect out of date DBs (perhaps via version stamp?) and run necessary upgrades on them.

**Comment by aheinze** [comment]
you're right on the breaking change. but the change does simplify the (recursive) population a lot.
I agree that a DB updater tool would be handy, but it would take too much time right now that I would like to invest in more important things. I hope you didn't have to much trouble with the change.

greets,
artur

**Comment by gryphonmyers** [comment]
FYI to anyone affected by this, the required change to make in your db records is to add the name of the entry's collection to each entry under the "link" property. So for example,

```
{
  "_id": xxxxxxxx,
  "display": "My Data"
}
```
Becomes
```
{
  "_id": xxxxxxxx,
  "display": "My Data",
  "link": "myCollection"
}
```
