### ISSUE TITLE
Cockpit Next: Where can I find docs and tutorials?

### ISSUE THREAD

**Issue by jrlmontejo** [agentejo/cockpit#538]
Where can I find docs and tutorials for Cockpit Next? AFAIK the docs at https://getcockpit.com/docs are outdated.

Great CMS btw.

**Comment by aheinze** [comment]
Hi, 

I hope to get the new docs online by the end of this month.

**Comment by flayks** [comment]
…Or not 😅

**Comment by aheinze** [comment]
@flayks well, they are in the making...the site re-design also takes its time 😔

**Comment by MichelChouinard** [comment]
I do like the new one but would really like having the doc ;)

**Comment by chrisbenjamin** [comment]
Hi there, are the current available docs the final docs? Because I don't find any deeper information.  
In general I need to know some use cases for regions and forms. Further I need specifications for building different API accesses, like post and update. 
Can someone provide me these information as long the documentation is in progress?

**Comment by aheinze** [comment]
@chrisbenjamin no, they are in an early stage to be honest but will get updated on a daily basis.

**Comment by Blemming** [comment]
Things that should be prioritized IMO : 
Custom Config YAML options - List all the available options and things we can do with this.
The custom JSON config for the fields - List all the available options and things we can do with this.
API parameters - List all the available params and what they do. Until recently I didn't know there was a populate param so my frontend had to do multiple requests and put everything together ( not using php ) 
I figure most of the custom configs/custom field configs are things you want to add to the interface, but meanwhile it would be very nice to have documentation on them.

**Comment by chrisbenjamin** [comment]
Thanks for your reply and I really appreciate your work. 
As long as the docs are still not complete, could someone please tell me how a POST request should look like?
I have a simple collection with just two fields (id, name). GET request is as simple as documented. But I am wondering how I could post an entry from another application.
Thanks

**Comment by justrealmilk** [comment]
@Blemming please share all of your API knowledge! 💯

**Comment by russellhutsonmicro-p** [comment]
I'm adding things to https://github.com/agentejo/cockpit/wiki when I can

**Comment by amitca71** [comment]
I'm trying to install, using: /cockpit/install, however, i get redirected to /auth/login before even creating the 1st user. any idea?

**Comment by tomdupont** [comment]
Hi @amitca71,

Maybe one of two thing happens:

- Install already happend, can you login with u: admin p: admin?
- Are you sure that /cockpit/install is the correct path to the root of your cockpit directory? Have you tried /install

**Comment by amitca71** [comment]
thanks alot tomdupont!!! it was the 2nd... 
i use the docker, and in docker its /install without /cockpit (as presented in the documentation)

**Comment by fzerman** [comment]
I am writing new documentation for Cockpit CMS. It is in development now. However, I am updating it daily. In the future, I am going to create tutorials and more content. 
- https://cockpit.stingydeveloper.com/
