### ISSUE TITLE
[Next] Rest Api syntax

### ISSUE THREAD

**Issue by yumyo** [agentejo/cockpit#549]
Hi, 
I've tried all of the possible variations found here but none seems to work:

`[domain]/cockpit/api/collections/get/[collection]?token=[token]`   
this returns `Path not found.`

`[domain]/cockpit/rest/api/collections/get/[collection]?token=[token]`
This returns `404`

To exclude any permission issue I've temporarily set folder and files to 777

$_SERVER['DOCUMENT_ROOT'] exists and is set to the domain folder (not `/cockpit/`).

Ubuntu 14.04 on Digital Ocean
Nginx
Cockpit Next
php5.5.9-1ubuntu4.21
php-fpm

**Comment by pozylon** [comment]
Hi Yumyo

Using the docker image it's /api/collections/get/collection?token=account-token

Be aware that the collection name is case sensitive and that it will return "Path not found" if the token is invalid.
