### ISSUE TITLE
[Next] When saving collection, browser freezes.

### ISSUE THREAD

**Issue by Laurensvdmaas** [agentejo/cockpit#554]
Hi,

Whenever i try to save an collection, it pretty much freezes the browser. Since i would like to try cockpit out and move 1 of my projects from Wordpress to Cockpit i do really need the repeater field (Only available in Next).

Is anyone else experiencing this issue, and maybe knows an quick fix?  No errors shown in the logs so not quite sure where the problem is located.

Reproduction steps:

[1] Clone cockpit, (Next branch).
[2] Install cockpit
[3] Create an collection & try to create one.

**Comment by aheinze** [comment]
Hi,

could you please give more details about which browser, os etc?

Thanks!

**Comment by Laurensvdmaas** [comment]
Just checked only happens in Chrome, safari / firefox are fine.

Browser: Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)
OS: Mac El Capitan 10.11.6
NPM: 4.0.5
