### ISSUE TITLE
How can i upload image through form input?

### ISSUE THREAD

**Issue by sisaurora** [agentejo/cockpit#558]
i was using cockpit stable(0.13) and using a plugin called AdvancedForms i was able to upload files/images. is possible to do that using next? if yes, How?

**Comment by aheinze** [comment]
sorry, this is not possible, just plain data.

Greets
Artur

**Comment by aidanayala** [comment]
Could you store the image as base64 encoded?

**Comment by lesaff** [comment]
Is this possible now?
