### ISSUE TITLE
[NEXT] select and multipleselect inside set fields

### ISSUE THREAD

**Issue by jokmontoya** [agentejo/cockpit#561]
I have tried this in a set field:
`{
  "fields": [
    {
      "name": "name",
      "type": "text"
    },
    {
      "name": "choose",
      "type": "select",
      "options": "Option 1, Option 2, Option 3"
    },
    {
      "name": "choosemore",
      "type": "multipleselect",
      "options": "Option 1, Option 2, Option 3"
    }
  ]
}`

The `select `field only shows an empty option and the `multipleselect` field only shows the name.

**Comment by aheinze** [comment]
correct definition should look like:

```
{
  "fields": [
    {
      "name": "name",
      "type": "text"
    },
    {
      "name": "choose",
      "type": "select",
      "options": {
        "options": "Option 1, Option 2, Option 3"
      }
    },
    {
      "name": "choosemore",
      "type": "multipleselect",
      "options": {
        "options": "Option 1, Option 2, Option 3"
      }
    }
  ]
}
```

**Comment by jokmontoya** [comment]
Ok, That was my mistake.  Thank you very much for everything.
I've just started trying your CMS, I think it's a great idea.
