### ISSUE TITLE
Saving layout entries with sections in collections

### ISSUE THREAD

**Issue by ling1726** [agentejo/cockpit#562]
**Using v 0.4.2 on docker**

**How to reproduce:**

1. create a new layout entry
2. create a new section inside the entry
3. add a header component to the entry
4. modify the text, tag, class, id
5. save
6. make a modification to any of the above properties
7. save
8. changes not saved, revision number also does not increase

**Workaround:**

everytime this happens refreshing the page will resolve the issue. However, this happens pretty often so in the end I am refreshing the page for every single change I make.

Otherwise this is an amazing headless CMS!

**Comment by aheinze** [comment]
should be fixed after updating the docker image

**Comment by Blemming** [comment]
Having the same problem on the master branch
