### ISSUE TITLE
Searching and Indexing

### ISSUE THREAD

**Issue by robwent** [agentejo/cockpit#564]
Apologies if this has been asked before but I couldn't find anything specific in issues and the documentation seems a little sparse.

I have created a collection called 'places' and searched through issues to find a reference on how to list them through the api (There doesn't seem to be any documentation about endpoints?).
I can access the list of entries but I can't find any way to search them.

How do you search for specific entries or get a single entry? I can only seem to get a list of everything.

Is it possible to search by location data in a similar way to using a mysql point field and request all items within a radius of a specific point?

**Comment by robwent** [comment]
I've just had a look at the database structure and it seems like everything is stored as actual json, so I'm guessing that nothing is indexed in the database and searching either isn't possible or is compiled and cached with php.

**Comment by Blemming** [comment]
/cockpit/api/collections/get/{collectionName}?token={generatedToken}&populate=1&filter[{fieldName}]={whatYourAreLookingfor}

replace the info between the {} with your info

**Comment by aheinze** [comment]
I don't recommend to query via the GET parameters but doing an `application/json` request as the parameters might get messed up due to url encoding.

Recommended (js):

```
fetch('/cockpit/api/collections/get/{collectionName}?token={generatedToken}', {
  method: 'post',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({
    populate: 1,
    filter: {field:'query'},
  })
}).then(res=>res.json()).then(res => console.log(res.entries));
```

**Comment by robwent** [comment]
How is cockpit indexing this information though, is it all cached in static files?
If so, what's the number of records it can work with before querying becomes problematic?
It doesn't look like there is any indexing going on in the database.

Do you have an example of querying a number of objects within a certain radius of a lat/lng point?

**Comment by DeHekOnline** [comment]
> /cockpit/api/collections/get/{collectionName}?token={generatedToken}&populate=1&filter[{fieldName}]={whatYourAreLookingfor}
> 
> I just found this:
> /cockpit/api/collections/get/?{fieldName}={whatYourAreLookingfor}
> Apparently searches all your collections
> 
> replace the info between the {} with your info

This isnn't working anymore I guess ... (?). Is there a way to search a field in all collections?
