### ISSUE TITLE
Copy collections and entries from one Cockpit Next installation to another

### ISSUE THREAD

**Issue by zontarian** [agentejo/cockpit#569]
Hello,
sometimes I write some data on one (local) installation on Cockpit and I'd be able to replicate everything (collections and data in the collections) to another remote server.

At the moment what I do is:
1. install Cockpit
2. check that it works
1. crete cockpit/storage/collections on the remote server
1. copy cockpit/storage/collections/*.php to the second server
1. copy cockpit/storage/data/collections.sql to the second server

when I check cockpit again I can see the collections with fields etc.. and I can see the entries, but if I try to edit an entry, I can see the entry but somehow my whole web browser (Chrome or Safari on Mac) freezes. IT spins forever on the "revisions" number, and I cannot do anything save kill the tab.
If I, on the other hand, delete all the entries in a collection, and create from scratch, it works.

Any idea on what I am missing, or a workaround? 
Thanks
Walter

**Comment by aheinze** [comment]
maybe some wrong file permissions on the second server?

**Comment by zontarian** [comment]
Nice idea, sometimes I forget about simplest things, but no.. it's now 777 but it's almost the same.
Or.. sometimes it works and some other times (most) it does not.

When I cannot, it means I cannot d/click anything, and the "Revisions" and "Last update by" have both a spinning wheel below them. And after a while Chrome complains and asks me to kill the tab.
I've even tried the inspector to look at the JS console but there is nothing..it hangs before..

BTW it hangs also on Safari and Opera.. and it's really hard to debug without a console..
Thanks anyway

**Comment by aheinze** [comment]
do you have access to the php error log?

**Comment by zontarian** [comment]
yes. At the moment I'm testing this on my Mac. But there is nothing in the log. 
I can confirm the log works since if I ho to my cockpit addon I can see my logs. 
.. :(

**Comment by aheinze** [comment]
then could you maybe look in the network panel what the ajax request respond from the server after saving an item?

**Comment by zontarian** [comment]
Good idea..
It's the find and revisionCount that seem hanged

![screen shot 2017-09-13 at 14 30 49](https://user-images.githubusercontent.com/2872433/30377511-424d0f86-9890-11e7-8cf2-ff8fbb69e365.png)

**Comment by aheinze** [comment]
do you have the project online?

**Comment by zontarian** [comment]
Hi, no but I can share with you the zip of the relevant files. Basically the collections php and the collections.sqlite.

Besides the files are related to a public web site, so no big deal of privacy.

Thanks
