### ISSUE TITLE
Can I expect this project to replace WordPress?

### ISSUE THREAD

**Issue by edirpedro** [agentejo/cockpit#570]
I'm a developer and build things, apps using WP, not only simple themes. I tried to simulate some UI concepts from WordPress, but I missed many features on Cockpit and I need to know if this tool can, one day, replace the WP panel. For now I can list some features I use frequently and I couldn't find in this tool.

From WordPress

- Bulk edition
- Quick edition
- Fluid table list
- Sortable columns in this list
- Option to customize some column in this list
- Filters and search in this list
- Relate content inside the same collection, like in Pages

From Advanced Custom Field plugin

- Conditional logic for each field
- Better field group “tab” organization when building the form
- Better repeater field
- Better image gallery
- I can build my own field type
- The hooks are very useful
- I can render a form on the front end
- I can build one form and indicate where to use it instead of replicate

**Comment by gryphonmyers** [comment]
It depends what you need. Personally, I find Cockpit to be far more versatile than Wordpress in that you can define arbitrary schemas (collections) and you aren't forced into a "Blog" or "Page" mentality. It also doesn't require clunky plugins nor suffer from the performance issues of ACF to make arbitrary "field types" - just nest sets and repeaters ad infinitum. It is also headless, so makes zero effort to render any data - just consume your data over the REST API.

Based on your list of missed features, I'm wondering if you might be using the master branch. The next branch has a lot of bugfixes and new features, and  a better interface overall.

**Comment by edirpedro** [comment]
No, I was testing using the master version. I was checking if I could build some of my projects using this tool, how much work I have to do to creating an UI easy as WP and some custom ideas I've built in some projects. Most of the features I missed are related to the UI and in this case WP and ACF are more friendly to users.

**Comment by gryphonmyers** [comment]
Definitely try out the next branch then. When making a new collection, you may find this (incomplete) reference helpful, as field specifications are done with JSON and otherwise undocumented: https://github.com/agentejo/cockpit/wiki/Collection-Field-Types

**Comment by edirpedro** [comment]
Sorry, you told NEXT branch, I'll check that.
