### ISSUE TITLE
Collection/field relationships

### ISSUE THREAD

**Issue by mrjcgoodwin** [agentejo/cockpit#571]
Just assessing Cockpit for a new project and can't see answers in the docs. Does Cockpit handle relationships between collections and can fields be re-used in multiple collections/regions?

Can a collection have one->many relationship with another collection?

**Comment by aheinze** [comment]
yes you can. create a field with the type Collection-Link and add the following in the field settings:

```
{
  "link": "{name of the collection you want to link}",
  "multiple": true
}
```

**Comment by mrjcgoodwin** [comment]
Ok fantastic - will check it out then :-)

**Comment by jhesgodi** [comment]
@aheinze 
Thanks for the CMS is really fantastic.

I was wondering if there is a way to allow a `collectionLink` field to have more than just one collection type linked?

```javascript
{
  "link": [
      "collection-one-name", 
      "collection-two-name"
   ],
  "multiple": true
}
```
