### ISSUE TITLE
Feature: Media finder should have pagination

### ISSUE THREAD

**Issue by jrlmontejo** [agentejo/cockpit#572]
I personally think the media finder should have pagination. The problem is if a folder contains many files, the finder loads slow.

**Comment by aheinze** [comment]
About how many files are we talking (I want to reproduce it)?

**Comment by jrlmontejo** [comment]
If there are say, around 500 files inside a directory, the finder component won't show until all files are loaded.

As an effect of this issue, I won't be able to upload a file immediately since I have to wait for the finder component to load all the files in the current directory.

**Comment by johnhorsema** [comment]
Can use a scroll-to-load solution! How do I contribute to Cockpit?
