### ISSUE TITLE
[Next] Duplicating Entries in Sortable Collections

### ISSUE THREAD

**Issue by ehaeusler** [agentejo/cockpit#574]
If I enable "Sortable Entries" in a collection, it removes the possibility to duplicate entries. Is there any specific reason for that? Or was ist just an oversight in the **entries.sortable.php** partial?
It seems to work, if I just add the corresponding block from **entries.php**.

**Comment by aheinze** [comment]
I'll look into it

**Comment by mkalus** [comment]
Apparently this was resolved in commit 6f0bebcf33b172b61ea1430cf40d10b6822bf6f4.

**Comment by ehaeusler** [comment]
@mkalus only partially, it seems. If the collection view is in Grid Mode, I can see the menu item to duplicate, but not in list/table mode :)

See: [Partial](https://github.com/agentejo/cockpit/blob/9d6de27cea0058583af11321d4ca10a3ba11fae3/modules/Collections/views/partials/entries.sortable.php#L103)
