### ISSUE TITLE
[NEXT] Cannot create new account

### ISSUE THREAD

**Issue by honzabilek4** [agentejo/cockpit#576]
Hi,
It's not possible to create new account while on the top of `next` branch. 
It's giving me blank page with header only.

![screen shot 2017-10-03 at 20 41 30](https://user-images.githubusercontent.com/7890555/31142804-a4a78e2c-a87b-11e7-813f-63c4e9dda156.png)

The console shows some errors in riot.js library:

![screen shot 2017-10-03 at 20 45 40](https://user-images.githubusercontent.com/7890555/31142884-dd5cdf60-a87b-11e7-8724-3e38d2d6def4.png)

Could you point me to the right direction, so I can try to fix it?
I'm pretty new to cockpit, so It might need some time to get my way around.
Thanks,
JB

**Comment by aheinze** [comment]
I can't reproduce the issue. Could you please provide more details about your dev environment? (php version, browser etc.)? Thanks!

**Comment by honzabilek4** [comment]
Hi,

I'm on:
macOS Sierra (10.12.6)
PHP v7.1.7
PHP built-in Development Server
Browser:
Neither Firefox 56.0 nor Chrome 61.0.3163 are working for me.
I've also tested with Safari 11.0 - with the same result.
Cockpit: 
Top of the `next` branch (a8dc84be)

Let me know if you need anything else.
JB
