### ISSUE TITLE
[STABLE] Create Account Page Blank. 

### ISSUE THREAD

**Issue by Riddeller** [agentejo/cockpit#577]
Hi, 

The issue that is happening on issue #576. Is happening on the stable branch. It's the same error and looks to be caused by this code:

`
URL\modules\Cockpit\views\accounts\account.php
Line 184.

        this.account   = {{ json_encode($account) }};
        this.languages = {{ json_encode($languages) }};

        this.tabs      = [];
        this.tab       = 'general';
        this.fields    = {{ json_encode($fields) }} || {}; // <-- Code Causing Errors. If you change to empty object it eliminates error.. 
        this.meta      = {};
`

As I have never used Riot.js my knowledge is limited with this library. But the {{ json_encode($fields) }} is null if you look in JS console. I presume this is filled at run-time for when fields are already populated such as edit account?!

**Comment by aheinze** [comment]
I can't reproduce the issue. Could you please provide more details about your dev environment? (php version, browser etc.)? Thanks!

**Comment by Riddeller** [comment]
@aheinze

**Comment by jfdelarosa** [comment]
Both of the issues are fixed by changing:
`this.fields    = {{ json_encode($fields) }} || {};`
to
`this.fields    = {{ (isset($fields)) ? json_encode($fields) : "null" }} || {};`

As you can see on #588
