### ISSUE TITLE
Error in Mongo connection 

### ISSUE THREAD

**Issue by afzali** [agentejo/cockpit#578]
**First at all, Thank you. cockpit is great for me ;)**

I have problem when set mongo config (like doc) and boom:

"Fatal error: Uncaught Error: Class 'MongoDB\Driver\Manager' not found in C:\xampp\htdocs\cockpit\lib\MongoDB\Client.php:81 Stack trace: #0 C:\xampp\htdocs\cockpit\lib\MongoHybrid\Mongo.php(15): MongoDB\Client->__construct('mongodb://local...', Array, Array) #1 C:\xampp\htdocs\cockpit\lib\MongoHybrid\Client.php(16): MongoHybrid\Mongo->__construct('mongodb://local...', Array) #2 C:\xampp\htdocs\cockpit\bootstrap.php(113): MongoHybrid\Client->__construct('mongodb://local...', Array) #3 C:\xampp\htdocs\cockpit\lib\Lime\App.php(263): {closure}(Object(LimeExtra\App)) #4 C:\xampp\htdocs\cockpit\lib\Lime\App.php(1330): Lime\App->Lime\{closure}(Object(LimeExtra\App)) #5 C:\xampp\htdocs\cockpit\lib\Lime\App.php(1316): Lime\App->offsetGet('storage') #6 C:\xampp\htdocs\cockpit\modules\Cockpit\webhooks.php(8): Lime\App->__get('storage') #7 C:\xampp\htdocs\cockpit\modules\Cockpit\bootstrap.php(465): include_once('C:\\xampp\\htdocs...') #8 C:\xampp\htdocs\cockpit\lib\Lime\App.php(1311): require('C:\\xampp\\htdocs...') #9 C:\xampp\htdocs in C:\xampp\htdocs\cockpit\lib\MongoDB\Client.php on line 81"

how can solved it.
thank you.

**Comment by afzali** [comment]
sorry, it's my bad. Every things ok.

**Comment by lesaff** [comment]
For people left wondering about similar error message. This is how I fixed it.

1. Install `mongodb` PHP extension (`sudo pecl install mongodb`)
2. Restart PHP
