### ISSUE TITLE
Documentation on REST API

### ISSUE THREAD

**Issue by riyaz-ali** [agentejo/cockpit#579]
Hey there! Thanks for the great tool. It's just been a day and I'm already starting to like this :heart:

My question is where can I find more details / reference / link / tutorial about the REST API specs so that I can integrate my front-end with Cockpit ?

I've already browsed through issues [#130, #564] but cannot seem to find some reference. Can anyone point me in the right direction here.

**Comment by peterbrinck** [comment]
There is documentation on the website, if you scroll down to the bottom.
https://getcockpit.com/documentation

**Comment by sleroy** [comment]
Sorry the endpoints are not documented.

https://getcockpit.com/documentation/api/token

Don't you use a technology like swagger for the API Docs ?

**Comment by peterbrinck** [comment]
If you go to a page like Collections and scroll down all the endpoints is there.
https://getcockpit.com/documentation/modules/collections

**Comment by sleroy** [comment]
Thank you, the page navigation is confusing. I did not see it. Perhaps a Page "REST API" indicating that the information is stored on each page could help ?

**Comment by riyaz-ali** [comment]
Also, some links, like `/api/collections/save/posts`, just doesn't work. They result in a `404`. Maybe this is some configuration issue on my side or some bug in cockpit itself!

P.S. I'm not a PHP-guy so having trouble setting things up, although the setup is much simpler than any other CMS out there!

**Comment by williamespindola** [comment]
I have the same problem, route to save collections doesn't work.

**Comment by aheinze** [comment]
because of security reasons you need an account token to save collection entries.

![c9a49ed6-9045-4b94-b7c6-8d417d2e3c96](https://user-images.githubusercontent.com/321047/32894240-839f991c-cadc-11e7-83fb-a2bd2f2ddd81.png)

**Comment by williamespindola** [comment]
Thanks @aheizen I'm using token from api access settings. By the way why settings token works for get collection but not for save?

**Comment by fabianmu** [comment]
I have the same 404 issue when attempting to save hit `/api/collections/save/{collection}`.

My request (via guzzle):
```
$cmsClient->request('POST', "http://localhost:8080/api/collections/save/rede?token=$cmsKey", [
    'headers' => [
        'Content-Type' => 'application/json'
    ],
    'data' => ['name' => 'test']
]);
```

results in `Path not found.` I also see `"POST /api/collections/save/rede?token=account-b27c838862d8aa2c5678849d8a796a HTTP/1.1" 404 701 "-" "GuzzleHttp/6.2.1 curl/7.52.1 PHP/7.2.1"` in the log of the CMS-Webserver

I am using an account based token. Please advice, thanks :)

**Comment by fabianmu** [comment]
Update: Solved my issue by sending the following request:

```
$cmsClient->post("http://localhost:8080/api/collections/save/rede?token=$cmsKey", [
    'headers' => [
        'Content-Type' => 'application/json'
    ],
    'body' => json_encode(["data" => $rede])
]);
```

This may be helpful for someone having a similar issue.

**Comment by johnabelardom** [comment]
![image](https://user-images.githubusercontent.com/20322702/35759278-a397b2e4-08b3-11e8-8f84-ba9116fd3c18.png)

I can't save any entry @fabianmu I copied every instruction here why?
Do you know why?

**Comment by fabianmu** [comment]
@johnabelardom maybe you're not providing a valid json encoded body?

**Comment by johnabelardom** [comment]
@fabianmu yeah you're right, since postman is just sending data that is not json encoded. And I do really pass the values to save inside the "data" key and "data" must be json encoded. Thanks @fabianmu 

`fetch('/api/collections/save/user_collector?token=account-somethinghere', {
    method: 'post',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
        data: {
			id: '12',
			username: 'nyeam',
			website_domain: 'http://nyeam.com'
		}
    })
})
.then(res=>res.json())
.then(entry => console.log(entry));`

**Comment by tsp-sayan** [comment]
Hi, I am not a PHP guy so I am finding it difficult to comprehend the endpoints, is there any filter / findOne sort of endpoint builtin?

**Comment by RoelantStegmann** [comment]
With @tsp-sayan here, would be nice to have

**Comment by natemate90** [comment]
I really can't figure out why the following is not working. I created a "poster" user and copied its api  token to the url.

I also have the following yaml file setting:

```
# Cockpit settings
i18n: en
languages:
  en: English
  de: German
  cn: Chinese
# Authors
groups:
    author:
        $admin: false
        $vars:
            finder.path: /storage/upload
        cockpit:
            backend: true
            finder: true
        collections:
            manage: true
        singletons:
            manage: true
    poster:
responseCache:
  duration: 60
```

Next, I set the permissions in the "testimonials" collection to "create" in the "poster" group. The collection has 5 optional fields, and I tried to post into the tite field an example text.

What else do I need to do, in order not to get a 404 error? Is there something wrong with my syntax below?

```
    formSubmit() {
      axios({
        method: "post",
        url:
          "https://api-testing.some-domain.com/api/collections/save/testimonials/?token=account-f2086b0c57e8c586de97fac681537b",
        headers: { "Content-Type": "application/json" },
        data: JSON.stringify({
          title: "hello world"
        })
      })
        .then(response => {
          response.json();
        })
        .then(entry => {
          console.log(entry);
        })
        .catch(error => {
          console.log("failed");
        });
    }
  }
```

I would appreciate any help very much.

**Comment by natemate90** [comment]
Finally, I resolved this on my own with the following syntax:

```
      axios
        .post(
          "https://api-testing.some-domain.com/api/collections/save/testimonials?token=account-f2086b0c57e8c586de97fac681537b",
          {
            headers: { "Content-Type": "application/json" },
            data: {
              title: "hello world"
            }
          }
        )
```

Apparently, there were two syntax problems. 1) there is no need for json.stringify, whereas 2) axios should post directly instead of using options.

**Comment by xsonic** [comment]
As I stumbled upon this via google:
If you use **postman**, you need to set the `body` to `raw` and add the data like this:
`{"data": {"title":"A new item"}}`

![Postman_X6UEoAZVoU](https://user-images.githubusercontent.com/1257407/58490667-db2ba600-816d-11e9-830d-f575f7ab3c83.png)

**Comment by beasteers** [comment]
In the API documentation, you should make it more apparent where the query syntax is coming from. I dug and finally found that both the `fields` and `filter` payloads are in mongolite syntax (or mongodb if you have it set up that way), but you should link to those docs pages and point to instructions so we know how to construct every part of the json body
