### ISSUE TITLE
How to populate all tree in a GET request collections

### ISSUE THREAD

**Issue by renatomattos2912** [agentejo/cockpit#580]
Hi, Great tool man,

Is it possible to populate all the collection correlated ? I have a two level deep relation in my cockpit and i want to get all the childrens populates but it is only happen on the first level children, but not happening in the third level and above. Bellow you can see a print of the collection that is not populated:

![screenshot--2017-10-13-17-42-34-547](https://user-images.githubusercontent.com/2312835/31565748-635425fa-b03e-11e7-97b4-584f750ad721.png)

**Comment by aheinze** [comment]
Try `populate=2` ... The number tells how many levels deep Cockpit should resolve the linked items

**Comment by renatomattos2912** [comment]
Thanks for the reply, but it is not working for me, i put the number 2 but i get the same result, i tried other numbers too, no success.

![screenshot- 2017-10-17 11-34-04-275](https://user-images.githubusercontent.com/2312835/31667855-607de674-b32f-11e7-916b-44967c1c1947.png)

**Comment by peunoir** [comment]
I have the same issue.

**Comment by aheinze** [comment]
can you email me login credentials so I can have a closer look?

**Comment by renatomattos2912** [comment]
@aheinze i send you an email in hello@agentejo.com. Thanks for your help.

**Comment by aheinze** [comment]
This should be fixed in 0.4.4 - https://github.com/agentejo/cockpit/releases/tag/0.4.4

**Comment by renatomattos2912** [comment]
I update the files in server and use the same config.yaml file, but my database was not loaded, how can i inform my new instalation to use the same data of the previsous instalation?
Ps: The users was loaded, but collections not.

**Comment by renatomattos2912** [comment]
I solved the question above, i just put my old storage folder back on the new instalation and works.

**Comment by renatomattos2912** [comment]
And the problem is solved, thanks man, you can see the result in the print bellow:
Ps: i put `?populate=3` in this case.

![screenshot- 2017-10-20 13-30-36-668](https://user-images.githubusercontent.com/2312835/31829091-10ae9bc0-b59b-11e7-88a2-41e44d5de76a.png)

**Comment by RoelantStegmann** [comment]
This works super well; just had one additional related question. Can you also populate inversely? So I have two collections: pictures and products. Each picture is related to one or more products. I would prefer to specify this when saving a picture. 

Picture: {text: title, related-field: product(s)}
Products: {text: title} 

However, when I request a product I want to also retrieve the links of the pictures associated. So kind of 'inverse-populate'. What would be the way to approach this? :)
