### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by dnkls** [agentejo/cockpit#581]
Debian 9 

This is error wich i see when i try install ((((

`Fatal error: Uncaught PDOException: SQLSTATE[HY000] [14] unable to open database file in /var/www/html/cockpit/lib/MongoLite/Database.php:42 Stack trace: #0 /var/www/html/cockpit/lib/MongoLite/Database.php(42): PDO->__construct('sqlite:/var/www...', NULL, NULL, Array) #1 /var/www/html/cockpit/lib/MongoLite/Client.php(75): MongoLite\Database->__construct('/var/www/html/c...', Array) #2 /var/www/html/cockpit/lib/MongoLite/Client.php(63): MongoLite\Client->selectDB('cockpit') #3 /var/www/html/cockpit/lib/MongoHybrid/MongoLite.php(27): MongoLite\Client->selectCollection('cockpit', 'webhooks') #4 /var/www/html/cockpit/lib/MongoHybrid/MongoLite.php(47): MongoHybrid\MongoLite->getCollection('webhooks') #5 [internal function]: MongoHybrid\MongoLite->find('cockpit/webhook...') #6 /var/www/html/cockpit/lib/MongoHybrid/Client.php(420): call_user_func_array(Array, Array) #7 /var/www/html/cockpit/modules/Cockpit/webhooks.php(8): MongoHybrid\Client->__call('find', Array) #8 /var/www/html/cockpit/modules/Cockpit/bootstrap.php(465): incl in /var/www/html/cockpit/lib/MongoLite/Database.php on line 42`

Im trying solve this all night , now is morning (((

**Comment by dnkls** [comment]
Uff i install it , i dont know how but it run now)))
But another issue i cant update Latest stable 0.4.3 and in github i dont see this version..

**Comment by aheinze** [comment]
Seems like a file based permission issue ... die you make sure, that the storage folder and its subfolders are writable?

**Comment by dnkls** [comment]
Yes i set premission 777 in /storage/backups  
                                                        /cache
                                                       /data
...but "Couldn't download 0.4.3 release!"

Screenshot: https://i.imgur.com/a5AdcW0.png

**Comment by dnkls** [comment]
Yes i set premission 777 in /storage/backups
/cache
/data
...but "Couldn't download 0.4.3 release!"

Screenshot: https://i.imgur.com/a5AdcW0.png

**Comment by dnkls** [comment]
Plz ppl help me update to 0.4.3

**Comment by aheinze** [comment]
sorry there is no auto-update from 0.13 to 0.4.x. Cockpit >= 0.4.x is a almost a complete rewrite.
