### ISSUE TITLE
Assets api

### ISSUE THREAD

**Issue by twistedjoe** [agentejo/cockpit#583]
Is there an api to get the list of assets?  I see there is an internal one, but can't find the equivalent working with an api token.

**Comment by aheinze** [comment]
No, there is no api to get a list of assets ... can you describe a use case?

**Comment by twistedjoe** [comment]
My setup of cockpitcms is not on the end server. I got a static site generator that would build the end result. I would like to put the assets in cockpit and have the static site generator download them and bake them in the output of the static site generator.

**Comment by aheinze** [comment]
you can create a custom api entry point to get all assets.

Therefore create a file `config/api/public/getAssets.php`:

```php
<?php


$options = [
    'sort' => ['created' => -1]
];

$assets = cockpit()->storage->find("cockpit/assets", $options);

return $assets;

```

Then do a request against `/api/public/getAssets`

**Comment by twistedjoe** [comment]
Thanks!
Some example like this could help in the documentation.
