### ISSUE TITLE
403 Forbidden on server when login

### ISSUE THREAD

**Issue by Muini** [agentejo/cockpit#584]
Hello,

I've tried to install Cockpit on my server. All the requirements are good, i've checked them on my phpinfo.
I followed the install process, set /storage folder (and children) to 707 (even tried 777) write access. I went on /url/to/cockpit/install, no problem, it's saying me that everything is good, then it redirects me to login. I enter the default login and nothing happen. In the console I have this error :

`POST https://url.com/auth/check 403 (Forbidden)
(anonymous) @ app.js?ver=0.4.3:71
request @ app.js?ver=0.4.3:30
(anonymous) @ VM80:12
handleEvent @ riot.js?ver=0.4.3:1175
login:1 Uncaught (in promise) null`

`Promise rejected (async)
(anonymous) @ VM80:12
handleEvent @ riot.js?ver=0.4.3:1175`

I guess it's some kind of permission issue but I can't figure which one...

**Comment by aheinze** [comment]
what are you using as your webserver?

**Comment by Muini** [comment]
Its an OVH server, shared one (not dedicated), apache.

**Comment by aheinze** [comment]
Sorry, don't have any experience with the hoster. maybe you need to adjust the rewrite base

https://github.com/agentejo/cockpit/blob/master/.htaccess#L20

(also make sure, that the apache module mod_rewrite is enabled)

**Comment by Muini** [comment]
mod_rewrite is supported & enabled. I tried to set the rewritebase, same issue, no change :(

**Comment by aheinze** [comment]
I can offer you to have a look if you mail me the url and any sftp access
