### ISSUE TITLE
Unable to select multiple images in the fileselector of a Gallery field

### ISSUE THREAD

**Issue by xanderberkein** [agentejo/cockpit#585]
When I want to add multiple images to a gallery, and I select "File", I'm unable to add multiple images at once to the gallery. Although I can select multiple files by shift-clicking, only the first selected item gets added to the gallery.

### Steps to reproduce:
- Add "file" to the gallery field:
![image](https://user-images.githubusercontent.com/10937632/31775889-2c3f71ae-b4ea-11e7-9b66-91e118523ef4.png)

- Select multiple by shift-clicking:
![image](https://user-images.githubusercontent.com/10937632/31776019-935107c2-b4ea-11e7-9743-a9e797599d42.png)
(notice the "Select: 1 item(s)" on the button in the right-bottom)

- Only the first selected item gets added:
![image](https://user-images.githubusercontent.com/10937632/31776077-ba3f7de6-b4ea-11e7-9544-3e73ccc88d48.png)

### Expected result
When selecting multiple files, I expect them all to be added to the gallery. Selecting 1 by 1 is a very tedious task for large galleries. Adding multiple assets at once works, but it doesn't work for files.

**Comment by aheinze** [comment]
I see, selecting multiple files with shift seems to be broken (cmd seems to work)

**Comment by xanderberkein** [comment]
Didn't think to try cmd yet, that's a good workaround for now. Thanks!

**Comment by xanderberkein** [comment]
Hi, just a quick follow-up question, what would be the recommended way to upgrade cockpit to a new version? I'm running the project on an apache webserver.

**Comment by aheinze** [comment]
override everything except the `config` and storage `folder`

**Comment by xanderberkein** [comment]
Worked like a charm, thanks! I'm really loving cockpit as a headless cms!
One last question, if you don't mind. How would one add an entry to a form via api call?

**Comment by xanderberkein** [comment]
Oh, I see someone made an issue just now with exactly the same question 😛
