### ISSUE TITLE
More information on the Access Rules ?

### ISSUE THREAD

**Issue by bensonshaji** [agentejo/cockpit#589]
I am starting to love the concept of cockpit being a headless CMS. Kudos to you and your team for this amazing project. 

Could you please help me pointing out more info the documentation. I did quite a digging but unfortunately i couldn't more information on the documentation section and google. Some of the information is missing.. for example Access Rules (Api Key) , Build In security features.. , Collections (Database relationships - how to create one to many or many to many relations) and so on..

Thanks in advance

**Comment by iamso** [comment]
@aheinze It seems that although a lot has been updated in Cockpit, the API access rules still haven't been documented. 
I've asked for this a few times before and I'm asking it again. Please document how to create access rules for API tokens!

Thanks.

**Comment by aheinze** [comment]
@iamso In general it is pretty simple. In `Settings > Api Access` you can create additional custom api keys.

then in rules you can define which api entry points (one per line) you can access with the token.
so let's say you just want to allow the collections get api. for that enter the rule 

`/api/collections/get`

in the rules textbox.

If you just want to allow to query the posts collection with the token, then the rule for this:

`/api/collections/get/posts`

Or `/api/collections/get/(authors|posts)` for multiple options.

**Comment by bensonshaji** [comment]
@aheinze Thanks for the reply.. Its really helpful.. 

Are POST requests supported in the current version ? Because I tried to make posts requests to "/api/collections/get/posts" It simply returns Unauthorized. Is this the default behavior or Am I doing something wrong ?

**Comment by Lukewh** [comment]
@bensonshaji I think you need to POST to `api/collections/save/posts` as per https://getcockpit.com/documentation/modules/collections
