### ISSUE TITLE
[Next] Fields named "link" break entries on REST API

### ISSUE THREAD

**Issue by gryphonmyers** [agentejo/cockpit#590]
Steps to reproduce:
1) Create a collection with a field named "link" (type probably irrelevant, but mine was text).
2) Create at least one entry with data in this field.
3) Look at collection on REST API. Note that all entries are returned as false.

Expected behavior:
What is probably happening here is that it is trying to populate a collection link based on the "link" option and obviously not finding a collection match. If "link" is a reserved name, it should give some kind of warning in the collection editor.

**Comment by aheinze** [comment]
Thanks for reporting Gryphon! I'll investigate it.
