### ISSUE TITLE
Asset upload not showing

### ISSUE THREAD

**Issue by elin** [agentejo/cockpit#591]
The files get uploaded into /storage/uploads/2017/10/26 - but the call assetsmanager/listAssets doesn't seem to show any output (I'm getting the response {"assets":[],"count":0}).

**Comment by aheinze** [comment]
ok, this is strange. could you give more details about the files (type, size), browser, os?

Thanks!

**Comment by elin** [comment]
I have tested different jpg and pdf with different sizes, and get the same result. I'm on Mac with Chrome browser - also tested on Firefox, same result - see screenshots! 
I have a "clean" install on latest stable version of Cockpit Next - no settings changed! (Path problem?)
![cockpit-upload](https://user-images.githubusercontent.com/195579/32212977-9aff29f8-be19-11e7-9702-8f33504d5cda.png)
![cockpit-listassets](https://user-images.githubusercontent.com/195579/32212994-b3cee072-be19-11e7-933a-17492bbd47a9.png)

I also get an 500 server error on /cockpit/utils/revisionsCount - but not sure if that's related.

Thank you.

**Comment by aheinze** [comment]
maybe a file permission issue. is the folder storage/data writable?

**Comment by elin** [comment]
Yes, probably permission problem! I noticed that cockpit.sqlite and collections.sqlite had different users - so I changed:
`chown www-data:www-data cockpit.sqlite`
- that did the trick!

Thanks a lot.
