### ISSUE TITLE
Unauthorized when making POST request with ajax

### ISSUE THREAD

**Issue by VojtechKlos** [agentejo/cockpit#592]
Hey, didnt find anything on this so Im asking.

The documentation says that in order to save data (or to get filtered data) you should use this:
`fetch('/api/collections/save/posts?token=xxtokenxx', {...`
However I am getting `{error: 'Unauthorized'}` even though the supplied token is valid. I tried with the general token you find in the settings and admin api account token as well.

Im using the master branch.

Any insight on this is welcome. Thanks

**Comment by VojtechKlos** [comment]
OK it works now when I created new user and used its token. I feel like this is a "bug"? I will keep the issue open in case it is in fact a bug.

Cheers.

**Comment by VojtechKlos** [comment]
Also just for the record there is a typo in the docs it says when retrieving filtered data the url is `/api/collections/save/posts?token=xxtokenxx` when in fact there should be GET instead of SAVE so: `/api/collections/get/posts?token=xxtokenxx` is correct.

**Comment by adithwip** [comment]
You are a life saver. Why on earth is the docs get us the wrong API endpoint 😂

**Comment by sebastianks** [comment]
@adithwip Because the DOCS is for the old Cockpit - you're probably using the Next branch :)

**Comment by NMonst4** [comment]
Ok after wasting my time with checking keys i luckily  find your post and that with a new user make no sense.

**Comment by gxvr** [comment]
> Also just for the record there is a typo in the docs it says when retrieving filtered data the url is `/api/collections/save/posts?token=xxtokenxx` when in fact there should be GET instead of SAVE so: `/api/collections/get/posts?token=xxtokenxx` is correct.

This solved it for me..Thanks. Doc should be updated
