### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by a-marionette** [agentejo/cockpit#594]
OS: OS X (El Capitan)
Apache: Server version: Apache/2.4.18 (Unix)
PHP: PHP 5.5.36 

Steps:

1. Transfer contents of Cockpit to web root
2. View Cockpit at http://127.0.0.1/install

Issue:

I am instantly redirected to the success page after navigating to "install/". When I go to login, I get directed to "auth/login" which is a 404 as it doesn't exist in the web root.

**Comment by adamkiss** [comment]
From [Getting Started / Requirements page](https://getcockpit.com/documentation/getting-started/requirements):

> Requirements:
> * PHP >= 5.6

**Comment by a-marionette** [comment]
Thank you for pointing this out.

I have upgraded and still am getting the same error.

PHP:  PHP 7.0.25

**Comment by arslan-akh** [comment]
Try to check apache configuration file the Apache mod_rewrite module must be enabled

**Comment by a-marionette** [comment]
Mod_rewrite was not enabled. Ty

**Comment by WebShapedBiz** [comment]
I have the same issue with the latest cockpit-next (04.12.2017), 404 error for /auth/login URL, with all requirements set.
PHP 7.1.12
Mod_rewite enabled

**Comment by teamgroove** [comment]
same here

**Comment by arismarko** [comment]
I had the same issue when i upgraded the version to >7 it worked
