### ISSUE TITLE
NEXT: Access Markdown, Thumbnail & other bootstrap functions

### ISSUE THREAD

**Issue by flayks** [agentejo/cockpit#595]
Hey there,
I'm trying the Next version of Cockpit but I come to the point of using thumbnails (image sizes) using the `thumbnail()` function like in the older version (0.13.0) but I just get this error:
```
Fatal error:  Uncaught Error: Call to undefined function thumbnail() in /portfolio/index.php:56
Stack trace:
#0 [internal function]: Lime\App->{closure}(Array)
#1 /portfolio/cockpit/lib/Lime/App.php(1051): call_user_func(Object(Closure), Array)
#2 /portfolio/cockpit/lib/Lime/App.php(972): Lime\App->render_route('/', Array)
#3 /portfolio/cockpit/lib/Lime/App.php(955): Lime\App->dispatch('/')
#4 /portfolio/index.php(99): Lime\App->run()
#5 {main}
  thrown in /portfolio/index.php on line 56

Notice:  ob_end_clean(): failed to delete buffer. No buffer to delete in /portfolio/cockpit/lib/Lime/App.php on line 934
```

I did require the file at the top of my index.php file but no luck:
`require_once("cockpit/bootstrap.php");`
```
    /* ==========================================================================
       PAGE:
       -> HOMEPAGE
    ========================================================================== */
    $app->bind("/", function(){
        global $projects;

        echo "<pre>"; print_r(thumbnail(array())); echo "</pre>";

        return $this->render("views:homepage.php", array(
            "pagetitle" => SITE_TITLE.SITE_TITLE_SEP.SITE_DESC,
        ));
    });
```

Same with the `markdown()` functions etc, that were very useful in the past!
Due to a crucial lack of documentation I'm a bit lost, so any help would be appreciated :)
Thanks!

**Comment by aheinze** [comment]
they are still there:

`cockpit('cockpit')->markdown($text)`
https://github.com/agentejo/cockpit/blob/next/modules/Cockpit/bootstrap.php#L21

and

`cockpit('cockpit')->thumbnail($options)`
https://github.com/agentejo/cockpit/blob/next/modules/Cockpit/bootstrap.php#L88

**Comment by flayks** [comment]
Oh, thanks!
I saw the functions in the code but couldn't figure out how to call it.

**Comment by flayks** [comment]
@aheinze after some tests I can't figure out a way to get it working… Not really any error though, just nothing happening.

```
$image = (!empty($project->thumb)) ? $project->thumb->path : null;
$image_x1 = cockpit("cockpit")->thumbnail(array(
    'src' => $image,
    'mode' => 'thumbnail',
    'height' => 333,
    'quality' => 80,
));
```

No thumbnail created in `cockpit/storage/thumbs` or any other folder if I specify the `cachefolder` option. Do you have any idea?
