### ISSUE TITLE
413 Payload Too Large on asset upload

### ISSUE THREAD

**Issue by Lukewh** [agentejo/cockpit#596]
Using the docker image I'm receiving a 413 for any file over 1mb.
Looking at phpinfo():

Directive | Local Value | Master Value
--- | --- | ---
memory_limit | 128M | 128M
post_max_size | 256M | 8M

Any ideas why this is happening?

Nothing in the stdout and stderror logs.

**Comment by aheinze** [comment]
this is strange, may I ask what is the size of the file?

**Comment by Lukewh** [comment]
1.8mb, which makes it strange as it's below the global defaults

**Comment by ggioffreda** [comment]
Are you using PHP-FPM? Did you check the correct config?

If yes to the above, you need to fiddle with Nginx or Apache or any other proxy/web server that you have in front of PHP.
