### ISSUE TITLE
Layout field custom components not working

### ISSUE THREAD

**Issue by gryphonmyers** [agentejo/cockpit#597]
This might just be a docs problem. I am trying to use the new layout field type, and would like to customize the components that are available within it. I have tried specifying the following options block:

```
{
  "components": {
    "test": {
      "fields": [
        {
          "type": "text",
          "name": "myField",
          "label": "My Field"
        }
      ]
    }
  }
}
```
But no new components show up. I have tried debugging https://github.com/agentejo/cockpit/blob/next/modules/Cockpit/assets/components/field-layout.tag#L185

and opts.components is undefined. Is there some missing wiring here or is my syntax wrong?

**Comment by aheinze** [comment]
Thanks for reporting, Gryphon!
