### ISSUE TITLE
Wrong event triggered when content changed within a Section

### ISSUE THREAD

**Issue by chapachapa** [agentejo/cockpit#598]
Hey,

I'm working with the Layout component and any changes with items inside the Section or Grid component under the layout seem to trigger the wrong event. This seems to also cause the changes to be invisible to Cockpit - resetting the changes when you click on Save.

Repro steps:
1) In a collection, add a Layout component
2) Go to the collection and create/edit a entry.
3) Create a section or a grid component within the layout.
4) Add a Text component within the section/grid - try adding content to text
5) close the modal and try saving it - the component will reset.

in step 5 when you close the modal (or if you select a different input box), a custom event _[change.uk.sortable](https://github.com/agentejo/cockpit/blob/bc6e186be4db0d42d246f34242eb621cf550ac8f/modules/Cockpit/assets/components.js#L1943)_ is fired. This seems like an event normally fired when reordering content on the list but because it's false positive, the arguments the event is expecting turns out to be all undefined.

Until this gets fixed, the work around is to change tabs between All/Main/General - which seems to snap shot the content - flagging a proper save.
(edit: or reload the page before adding another item under the section/grid)

Thanks,
-CP*

**Comment by aheinze** [comment]
could you please try to reproduce it with the next branch - https://github.com/agentejo/cockpit/tree/next

**Comment by chapachapa** [comment]
Sorry, I forgot to specify, this has been happening on the Next branch (updated yesterday when posting this issue)

I would also like to add to the original repro steps that this doesn't happen on the very first item added to the layout after loading the page, but when you try adding 2~3 items into the Section and then hit save - 1 or 2 items that were added last will disappear.

**Comment by chapachapa** [comment]
The newest version seems to have fixed this. Thanks! o7
