### ISSUE TITLE
Get thumbnail url : "Target width or height parameter is missing"

### ISSUE THREAD

**Issue by julienchazal** [agentejo/cockpit#600]
Hello i'm using version 0.5.0
I tried the new "/api/cockpit/image" like this with NuxtJS : 

```
async asyncData ({env, params}) {
      let {data} = await axios.get(`${env.cockpit.apiUrl}collections/get/project?token=${env.cockpit.apiToken}`)
      let products = await Promise.all(await data.entries.map(async (p) => {
        let result = await axios.post(`${env.cockpit.apiUrl}cockpit/image?token=${env.cockpit.apiToken}`, {
          src: p.visual.path,
          mode: 'thumbnail',
          width: 300,
          height: 300,
          quality: 80,
          base64: false
        })
        console.log(result.data)
        return p
      }))

      return {
        products
      }
    }
```
Image API returns : "Target width or height parameter is missing"

Any ideas please ?

**Comment by aheinze** [comment]
sorry, I've updated the docs:

```
async asyncData ({env, params}) {
      let {data} = await axios.get(`${env.cockpit.apiUrl}collections/get/project?token=${env.cockpit.apiToken}`)
      let products = await Promise.all(await data.entries.map(async (p) => {
        let result = await axios.post(`${env.cockpit.apiUrl}cockpit/image?token=${env.cockpit.apiToken}`, {
          src: p.visual.path,
          m: 'thumbnail',
          w: 300,
          w: 300,
          q: 80
        })
        console.log(result.data)
        return p
      }))

      return {
        products
      }
    }
```

**Comment by julienchazal** [comment]
thx for your answer.
It's weird now i've got a 404...

**Comment by aheinze** [comment]
could you give me the value of `p.visual.path` ? Do you use an asset field or image field?

**Comment by julienchazal** [comment]
i've created 2 entries, one with an asset field : 
`p.visual.path` = `/cockpit/storage/uploads/2017/11/18/5a109f0bedfffchantier-2.jpg`

the other with an image field: 
`p.visual.path` = `cockpit/storage/uploads/7-inch-uk-picture-disc-back.jpg`

FYI my NuxtJS dev server runs on `localhost:3000` and cockpit folder is on my project root, i use MAMP to serve cockpit API on `localhost:8888`

Nuxt config file : 
```javascript
env: {
    cockpit: {
      apiUrl: 'http://localhost:8888/julienchazal/cockpit/api/',
      apiToken: 'xxyyxx',
      baseUrl: 'http://localhost:8888/julienchazal/'
    }
  }
```

**Comment by julienchazal** [comment]
i also get a 404 with `<img src="http://localhost:8888/julienchazal/cockpit/api/cockpit/image?token=b8ccb79ec044c174f5f9c5f79e6069&src=http://localhost:8888/julienchazal/cockpit/storage/uploads/black-flag-logo.png&w=200&h=200&output=true" alt="">`

**Comment by julienchazal** [comment]
@aheinze did you reproduce ?

**Comment by julienchazal** [comment]
@aheinze up please ;)

**Comment by aheinze** [comment]
could you please try:

`http://localhost:8888/julienchazal/cockpit/api/cockpit/image?token=b8ccb79ec044c174f5f9c5f79e6069&src=storage/uploads/black-flag-logo.png&w=200&h=200`

**Comment by julienchazal** [comment]
`Path not found.`

**Comment by aheinze** [comment]
sorry but I can't follow/understand the issue. maybe you can zip the project and share it with me?

**Comment by julienchazal** [comment]
Hello again :)
The main problem is that when i call `api/cockpit/image?...` i get a 404 : 
`Error: Request failed with status code 404`

i followed the [docs](https://getcockpit.com/documentation/api/cockpit)

**Comment by julienchazal** [comment]
Sorry i wasn't using PHP 7 ...
Now it's working, my bad ;)
thx for your time !
