### ISSUE TITLE
[NEXT] Assets API returns string for image width

### ISSUE THREAD

**Issue by mpartipilo** [agentejo/cockpit#603]
Assets API returns string for image width.
(On my site) I get: 
`Failed prop type: Invalid prop `photos[0].width` of type `string` supplied to `Gallery`, expected `number`.`

**Comment by aheinze** [comment]
!? sorry, I don't get your error message. for me the assets api returns numbers for width and height

**Comment by mpartipilo** [comment]
You're right, I confused the Postman window with my results window.
Huh... Something on my side is converting just that value to a string.
Should have checked better before reporting.
Thanks!
