### ISSUE TITLE
Customize Layout field components

### ISSUE THREAD

**Issue by flayks** [agentejo/cockpit#604]
I was wondering if it's possible to customize which components we can use in a `Layout` field and also if we can add fields to components, like a specific title, a true/false radio or a select, for example. Nothing on the doc specify it, anyway I tried to play with options:
```json
{
  "image": {
    "meta": {
      "title": {
        "type": "text",
        "label": "Gallery title"
      }
    }
  }
}
```
But no luck.

The only option I found is to play with the `id` and `class` fields to customize and use PHP to render my code. This is working but not very modular and open.

It would be nice to be able to custom this `Layout` field and get an adapted CMS solution to any website.

Thanks!

**Comment by aheinze** [comment]
You can do this in the field options (extend existing components + add your own):

```
{
  "components": {
    "mycomponent": {
      "fields": [{
        "type": "text",
        "name": "myField",
        "label": "My Field"
      }]
    }
  }
}
```

**Comment by flayks** [comment]
@aheinze Yay! thanks a lot for this tip, works like a charm. I was wondering if you can start from scratch and fully customize the fields – or removing somes?

**Comment by template01** [comment]
Bump :)

**Comment by aheinze** [comment]
https://github.com/agentejo/LayoutComponents

**Comment by template01** [comment]
Amaze. Any ideas on @flayks comment: _I was wondering if you can start from scratch and fully customize the fields – or removing somes?_. I could see something like this working nicely:

```
{
  "allowed_fields": [
      // custom component
      {"name": "myField"},
      // core fields
      {"name":"text"},
      {"name":"heading"}
  ]
}
```

**Comment by template01** [comment]
Just bumping on ;)

**Comment by template01** [comment]
Uh. Nice. Ill check it out!

**Comment by template01** [comment]
@thinkink Uh. Nice. Ill check it out!

**Comment by Tummerhore** [comment]
Are there news regarding the use of something like the suggested "allowed_fields" attribute. I would really like to use it but it's neither working on stable nor with cockpit next.

**Comment by davishooly** [comment]
@flayks how exactly did you manage to add custom components on the Layout? I'm facing a similar issue.
