### ISSUE TITLE
Is markdown not being parsed?

### ISSUE THREAD

**Issue by Kinzi** [agentejo/cockpit#605]
Hi,

I started playing around with your very nice cms today! And maybe I'm not understanding the full concept yet. But shouldn't markdown be rendered to html in the response object? Or do I need to render it myself? Am I missing some setting or something?

Here is what I currently get as a resonse:

`{"content": "## Title h2\n### title h3\nLong text Long text Long text Long text Long text Long text Long text Long text Long text \n\nSome other image\n![title](/cabin2.jpg)"}`

**Comment by aheinze** [comment]
In fact yes, you've to parse it on side

**Comment by Kinzi** [comment]
Alright, thanks! ;)
