### ISSUE TITLE
Fetching data from Node.js

### ISSUE THREAD

**Issue by sebastianks** [agentejo/cockpit#607]
I am trying to fetch some data from within Node.js / Express. I've tested my code with https://jsonplaceholder.typicode.com/ and it's working just fine, but when I try to fetch data from a Cockpit API I get the error: "406 - Security incident detected" - if I try to `fetch()` from the console it's working just fine. What am I doing wrong?

This is my code:

```javascript
import { Router } from 'express'
import rp from 'request-promise'

const router = Router()

router.get('/products', (req, res, next) => {
	const options = {
		method: 'GET',
		url: 'http://url.com/cockpit/api/collections/get/products?token=xxx',
		// url: 'https://jsonplaceholder.typicode.com/posts',
		headers: { 'Content-Type': 'application/json' }
	}

	return rp(options)
		.then((response) => res.json(response))
		.catch((err) => res.json(err))
})

export default router
```

**Comment by sebastianks** [comment]
I also tried to use post instead, same issue

**Comment by sebastianks** [comment]
For some reason Cockpit doesn't play well with `request()`. I tried to use `node-fetch` like https://github.com/mpartipilo/cockpit-api-client does, and then it's working. I have no idea why, but feel free to comment if you do.

My working code:

```javascript
import { Router } from 'express'
import fetch from 'node-fetch'

const router = Router()

router.get('/products', (req, res, next) => {
	const url = 'http://url.com/cockpit/api/collections/get/products?token=xxx'
	const options = {
		method: 'GET',
		headers: { 'Content-Type': 'application/json' }
	}

	return fetch(url, options)
		.then((response) => response.json())
		.then((response) => res.send(response))
		.catch((err) => res.json(err))
})

export default router
```

**Comment by aheinze** [comment]
well, seems there is an issue in the request-promise lib...
