### ISSUE TITLE
Improve editor work flow for multi-lingual sites

### ISSUE THREAD

**Issue by JesperWe** [agentejo/cockpit#608]
After using Cockpit to power a couple multi-lingual websites I have identified two workflow issues:

1. An editor working with an update to the site will typically need to touch many entries in several collections. If the language being updated is not the default, the editor needs to pull down the Language menu and select his language for each entry. This will soon become annoying, especially for editors in companies that have a lot of dynamic content.

2. A different scenario, where updates are infrequent and editors not so experienced, forgetting to switch language before updating can easily happen. 

Enhancement requests: 
To fix (1), persist the current language selection on the session. 
To fix (2), persist the default language on the account between sessions.

**Comment by sebastianks** [comment]
This would actually be nice. @aheinze maybe we should make a “request feature” - so people won’t open issues which are actually feature requests?
