### ISSUE TITLE
Error uploading assets

### ISSUE THREAD

**Issue by Kinzi** [agentejo/cockpit#609]
I'm getting a 500 when uploading assets. (jpg 2mb) And the image doesn't show. However the file gets uploaded. I can see the file browsing with the Finder. Also uploading with the Finder works.

Since it's basically working I assume permissions are fine?!? Any other ideas?

**Comment by aheinze** [comment]
can you check your php/webserver error log?

**Comment by Kinzi** [comment]
Ahh:
`2017/11/26 15:13:13 [error] 1158#1158: *324 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 65536 bytes$
`

Let me see what I can do about it

**Comment by Kinzi** [comment]
Id do have `memory_limit  128MB` though - should be enough, no?

**Comment by aheinze** [comment]
could you please uncomment these lines: https://github.com/agentejo/cockpit/blob/next/modules/Cockpit/Controller/Assets.php#L84-L88 and try again?

**Comment by Kinzi** [comment]
Will do. Your on to something though. See full error in updated comment above...

**Comment by aheinze** [comment]
could you please update to the latest version of the next branch?

**Comment by Kinzi** [comment]
Awesome! :) Thanks for the super fast response and the awesome product!
