### ISSUE TITLE
Getting 401 unauthorized on image route

### ISSUE THREAD

**Issue by Kinzi** [agentejo/cockpit#610]
Do I need to give permission somewhere like with the toggles @ collections?

POST `https://cockpit.myurl.com/api/cockpit/images?token=XXXXX`
Body: 
```
{
    "src": "/storage/uploads/2017/11/26/5a1ade718ce15cabin3.jpg",
    "m": "thumbnail",
    "w": 300,
    "h": 300,
    "q": 80
}
```

Token Rules
```
/api/collections/get/
/api/cockpit/assets
/api/cockpit/images
```

**Comment by aheinze** [comment]
there is no `/api/cockpit/images` api end-point but `https://cockpit.myurl.com/api/cockpit/image`

**Comment by Kinzi** [comment]
True, alas same result. (I had it right in postman) ;)

**Comment by aheinze** [comment]
hi, could you please update to the latest next branch?

**Comment by Kinzi** [comment]
@aheinze Did that, but still no luck unfortunately

**Comment by sebastianks** [comment]
@Kinzi Did you set your token rules to `image` also? You've written `images` in the question. Maybe it could be a typo?

**Comment by Kinzi** [comment]
@sebastianks yeas, I double checked this earlier today. Also tried full access token.

**Comment by Kinzi** [comment]
It's the same for `/assets` btw. I tried several tokens (custom, full access, account) - I can `/collections/get/` with all of them

**Comment by sebastianks** [comment]
Hmm, that's weird. I can fetch on both assets and image no problem. Just tried with: `http://myurl.com/cockpit/api/cockpit/assets?token=xxx`.

**Comment by Kinzi** [comment]
@aheinze any other ideas what's going on?

**Comment by Kinzi** [comment]
There are a few more routes where I get unauthorized using the full access token. Basically it seems only the routes where I gave / could give public read permissions in the settings are working

**POST requests, empty body, response `401`**:
```
/api/regions/listRegions?token=FULLACCESSTOKEN
/api/cockpit/listUsers?token=FULLACCESSTOKEN
/api/cockpit/image?token=FULLACCESSTOKEN
/api/cockpit/assets?token=FULLACCESSTOKEN
/api/collections/listCollections?token=FULLACCESSTOKEN
```
also other `/cockpit/` routes

**Working `200`**:
```
/api/collections/collection/posts?token=FULLACCESSTOKEN
/api/collections/get/posts?token=FULLACCESSTOKEN
/api/regions/get/{regionname}?token=FULLACCESSTOKEN
/api/regions/data/{regionname}?token=FULLACCESSTOKEN
```

**Comment by aheinze** [comment]
are you sure that you don't have a typo in the token for the other routes? I can't replicate this localy. maybe you can email me the project?

**Comment by Kinzi** [comment]
I double checked it several times for typos but maybe you have better luck. :) I'll email you links and login credentials to hello@agentejo.com

**Comment by aheinze** [comment]
@Kinzi  something seems wrong with your nginx? configuration. GET parameters aren't available on the server side. so $_GET is always empty. collection api works because they are set to have public read rights.

**Comment by Kinzi** [comment]
@aheinze sounds plausible. I followed [these instructions](https://www.rosehosting.com/blog/install-cockpit-on-ubuntu-16-04/) when setting up the server. I'll try to figure out waht's going on today...

**Comment by Kinzi** [comment]
@aheinze sorry but I'm, still not getting images. If I understand the docs right I should be able to post  something like this to the image route:

```
{
    "src": "image._id" || "image.url",
    "m": "fitToWidth",
    "w": 300,
    "h": 300,
    "q": 80
}
```

I'm pretty sure the body gets through nginx settings as I get "src missing" response if I post w/o body.

When I post an _id (I got from assets route) the response is a 200 with body: `Unexpected '/'` 
When I post an url I get 200 with body: `Unexpected '/'` or 404 with body `Unexpected 'P'` depending on path value.

Is the url relative to storage folder, domain or absolute? Is it:
- `/2017/12/02/cabin2.jpg` -> 404
- `/storage/uploads/2017/12/02/cabin2.jpg` -> 200 with `Unexpected '/'`
- `storage/uploads/2017/12/02/cabin2.jpg` -> 200 with `Unexpected '/'`
- `https://mydomain.com/storage/uploads/2017/12/02/cabin2.jpg`

Why am I not getting any results? There is nothing in the error logs...
