### ISSUE TITLE
Cockpit not working on server (Shared Hosting)

### ISSUE THREAD

**Issue by bobaikato** [agentejo/cockpit#611]
Hi,

This is probably a bad idea, trying to host the application on a shared hosting.
When I trying to installing `www.example.com/install` I get redirected to the login page which blanks on _Firefox_ and _Chrome_
<img width="860" alt="screen shot 2017-11-30 at 12 27 26 pm" src="https://user-images.githubusercontent.com/14136806/33431023-aa5beab2-d5ca-11e7-81cf-34b0eeffc609.png">

.
What I'm I doing wrong?

**Comment by aheinze** [comment]
Cockpit should run pretty well on shared hosting out of the box. do you have access to php error log files?

**Comment by bobaikato** [comment]
Surprisingly the error file isn't propagated with any error.

Not where else to look into.

**Comment by nickngqs** [comment]
Hi,

I'm not sure if this is related as well. I'm trying out Cockpit and doing a fresh install. When i go to url/cockpit/install, I also get redirect to auth/login for Login. But I haven't set any account yet. I'm trying this on a localhost MAMP

**Comment by bobaikato** [comment]
Hey,

That’s the exact thing I was facing.
I tried login in with admin as  the username and password and it worked just fine 😆

Try it; and make sure you change your password afterwards.

**Comment by nickngqs** [comment]
@bobaikato Hi! I tried admin as the username and password. It doesn't work.

**Comment by bobaikato** [comment]
Okay, let get back together you on that.

**Comment by nickngqs** [comment]
@bobaikato Hey i figure it out, I followed the instructions on the Docs. It says `/url/to/cockpit/install` So i went to my localhost/folder/cockpit/install. Then i felt really weird, and check the directory, there's no cockpit at all. Voila, just do url/install. I think the Doc should change

**Comment by bobaikato** [comment]
Yeah I do agree with you on that. The Doc was not of help to me at all.
I’m trying to reinstall mine over again and see how I got it working.

**Comment by bobaikato** [comment]
@nickngqs works now?

**Comment by aheinze** [comment]
well `/url/to/cockpit` the url to cockpit installation...

**Comment by nickngqs** [comment]
@bobaikato Yeah it works now
@aheinze Yup, that why it felt weird, i guess most people change their folder names, I thought it will be more straightforward if it's public/install instead

**Comment by bobaikato** [comment]
Goodluck.

**Comment by ThiagoMiranda** [comment]
Hi @nickngqs . Just stumbled at this thread trying to solve my Cockpit configuration and it seems that you've solved it. I've just made a fresh install of MAMP for Mac and just pointed out to my cockpit folder but I'm getting the same `auth/login` redirect ( for any URL ). Can you help me?

Thanks

**Comment by nickngqs** [comment]
Whats ur folder directory like
