### ISSUE TITLE
On uploading a a PNG with only white and transparent pixels, fatal exception from ColorThief

### ISSUE THREAD

**Issue by justrealmilk** [agentejo/cockpit#612]
```
<br />
<b>Fatal error</b>:  Uncaught exception 'RuntimeException' with message 'Unable to compute the color palette of a blank or transparent image.' in /nfs/c12/h06/mnt/222710/domains/bd02.upliftnaturereserve.com/html/lib/ColorThief/ColorThief.php:138
Stack trace:
#0 /nfs/c12/h06/mnt/222710/domains/bd02.upliftnaturereserve.com/html/modules/Cockpit/Controller/Assets.php(84): ColorThief\ColorThief::getPalette('/nfs/c12/h06/mn...', 5)
#1 [internal function]: Cockpit\Controller\Assets-&gt;upload()
#2 /nfs/c12/h06/mnt/222710/domains/bd02.upliftnaturereserve.com/html/lib/Lime/App.php(1074): call_user_func_array(Array, Array)
#3 /nfs/c12/h06/mnt/222710/domains/bd02.upliftnaturereserve.com/html/lib/Lime/App.php(846): Lime\App-&gt;invoke('Cockpit\\Control...', 'upload', Array)
#4 [internal function]: LimeExtra\App-&gt;Lime\{closure}(Array)
#5 /nfs/c12/h06/mnt/222710/domains/bd02.upliftnaturereserve.com/html/lib/Lime/App.php(1051): call_user_func(Object(Closure), Array)
#6 /nfs/c12/h06/mnt/222710/domains/bd02.upliftnaturereserve.com/html/lib/Lime/App.php in <b>/nfs/c12/h06/mnt/222710/domains/bd02.upliftnaturereserve.com/html/lib/ColorThief/ColorThief.php</b> on line <b>138</b><br />
```

**Comment by aheinze** [comment]
hi,

could you please provide the image that causes the error? Thanks!

**Comment by iulas** [comment]
reopen please? 

same here when trying to upload PNGs with only white and transparent.

PHP Fatal error:  Uncaught RuntimeException: Unable to compute the color palette of a blank or transparent image. in /var/www/html/lib/ColorThief/ColorThief.php:138

Stack trace:

#0 /var/www/html/modules/Cockpit/Controller/Assets.php(88):ColorThief\\ColorThief::getPalette('/var/www/html/s...', 5, 6)
#1 [internal function]: Cockpit\\Controller\\Assets->upload()
#2 /var/www/html/lib/Lime/App.php(1074): call_user_func_array(Array, Array)
#3 /var/www/html/lib/Lime/App.php(846): Lime\\App->invoke('Cockpit\\\\Control...', 'upload', Array)
#4 [internal function]: LimeExtra\\App->Lime\\{closure}(Array)
#5 /var/www/html/lib/Lime/App.php(1051): call_user_func(Object(Closure), Array)
#6 /var/www/html/lib/Lime/App.php(998): Lime\\App->render_route('/assetsmanager/...', Array)
#7 /var/www/html/lib/Lime/App.php(955): Lime\\App->dispatch('/assetsmanager/...')
#8 /var/www/html/index.php(37): Lime\\App->run()
#9 {main}\n  thrown in /var/www/html/lib/ColorThief/ColorThief.php on line 138, referer: http://yaaycockpit.yaayapp.ch/assetsmanager
