### ISSUE TITLE
WYSIWYG field broken since commits from ~Nov 11

### ISSUE THREAD

**Issue by gryphonmyers** [agentejo/cockpit#614]
When loading the most recent version from next branch, I get "module [h] returned undefined" when on the entry view for any collection featuring a wysiwyg field. Reverting to 33727a20e3db9e075ef1a11d4af4f78aae35b064 fixes the issue.

**Comment by aheinze** [comment]
Hi Gryphon, 

could you please try to clear your browser cache? This should solve the issue.

**Comment by gryphonmyers** [comment]
You are absolutely right. I should have tried that - my bad!
