### ISSUE TITLE
Need information for working with form api

### ISSUE THREAD

**Issue by tevenFr** [agentejo/cockpit#616]
Hi there, great tool, thanks for sharing with the community.

By the way, i need some advice for working with forms:

- What is the endpoint for accessrules ?
- Is there a specific format additional to plain/text ?

Can you give me a quick API call exemple please.

Thanks in advance

**Comment by mpartipilo** [comment]
@tevenFr  See #638

**Comment by woutervddn** [comment]
While the amount of information is still very low; this one should be closed as there is a quick API example.

furthermore, all API examples can be found here:
https://getcockpit.com/documentation/api/cockpit
