### ISSUE TITLE
WebP image format is missing

### ISSUE THREAD

**Issue by vlad00777** [agentejo/cockpit#618]
Hi. I can't select webp images for my image field, because determination of webp is absent in source code.
Plz fix it. Thx.

**Comment by aheinze** [comment]
WebP is almost only supported by Chrome based Browsers, also there is now no out of the box support by the GD lib Cockpit is using for image processing. But I'll observe the need for webp but for now, sorry, I think there are more important things for Cockpit.

**Comment by BlindDespair** [comment]
@aheinze Do you think this issue could be reopened now? WebP has quite good support now and the format is very useful. After converting from jpg to webp the size of my images was reduced by like 50%. I tried to upload those into cockpit and it would work if I used the direct asset link, but I am still using the `/image` endpoint to resize the images through `srcset`. And that doesn't work with webp sadly :( It would be really great if this could work. For now I'll go with jpg images. Although I still think the issue should be reopened.

**Comment by patrickuhlmann** [comment]
@BlindDespair ok, I used webp but I resized the images locally already and just used the assets link. Can you please make an example how you are using it (e. g. how you construct the link, how the image tag looks like)

**Comment by BlindDespair** [comment]
@patrickuhlmann I need to use `srcset` for responsive pages so that the browser selects the image of the right size. So I store only **one** image in cockpit and then use the `/image` endpoint to get the desired size, which is then cached. This way I have really good flexibility as to what sizes of images I need.
Here is an example img tag:
```
<img _ngcontent-psh-c52="" sizes="(min-width: 768px) 50vw, 100vw" src="https://cockpit.sakurachef.com.ua/storage/uploads/2020/11/29/5fc2ec8d7b2a4birthday-min-min.jpg" srcset="https://cockpit.sakurachef.com.ua/api/cockpit/image?token=da6b808c5b8210a2b282ef47bd5cba&amp;src=https://cockpit.sakurachef.com.ua/storage/uploads/2020/11/29/5fc2ec8d7b2a4birthday-min-min.jpg&amp;w=320&amp;o=1&amp;q=80 320w, https://cockpit.sakurachef.com.ua/api/cockpit/image?token=da6b808c5b8210a2b282ef47bd5cba&amp;src=https://cockpit.sakurachef.com.ua/storage/uploads/2020/11/29/5fc2ec8d7b2a4birthday-min-min.jpg&amp;w=640&amp;o=1&amp;q=80 640w, https://cockpit.sakurachef.com.ua/api/cockpit/image?token=da6b808c5b8210a2b282ef47bd5cba&amp;src=https://cockpit.sakurachef.com.ua/storage/uploads/2020/11/29/5fc2ec8d7b2a4birthday-min-min.jpg&amp;w=960&amp;o=1&amp;q=80 960w, https://cockpit.sakurachef.com.ua/api/cockpit/image?token=da6b808c5b8210a2b282ef47bd5cba&amp;src=https://cockpit.sakurachef.com.ua/storage/uploads/2020/11/29/5fc2ec8d7b2a4birthday-min-min.jpg&amp;w=1280&amp;o=1&amp;q=80 1280w" alt="В День Рождения">
```
I use angular to create my pages, so the way I construct these srcsets is that I use a simple pipe like this:
```
@Pipe({
  name: 'cockpitSrcSet',
})
export class CockpitSrcSetPipe implements PipeTransform {
  private readonly minWidth = 320;

  transform(value: string, sizeCount = 4): string {
    const imageUrl = mergePaths(environment.cockpit.baseUrl, value);
    return new Array(sizeCount)
      .fill(0)
      .map((_, index) => {
        const size = index + 1;
        const optimizedImageUrl = mergePaths(
          environment.cockpit.apiUrl,
          `cockpit/image?token=${environment.cockpit.apiccessToken}&src=${imageUrl}&w=${this.minWidth * size}&o=1&q=80`
        );
        return `${optimizedImageUrl} ${size * this.minWidth}w`;
      })
      .join(', ');
  }
}

```

**Comment by patrickuhlmann** [comment]
Ok, I just asked because I added webp support with the pullrequest #1373. It was merged in November and there has been no release since then. I guess you are on the 0.11.2 release and not on the next branch?

**Comment by BlindDespair** [comment]
@patrickuhlmann yes, I am on 0.11.2, because I am using the latest docker image.

**Comment by patrickuhlmann** [comment]
I quickly tested the image endpoint on my installation that is running the code from #1373. It is working. Thus the issue can be kept closed as it is solved and just waits for the next release (don't know when it will happen).

**Comment by BlindDespair** [comment]
@patrickuhlmann thank you for your answer, I will wait for the next release then and when it's out I will migrate all the images on the site to webp (gonna be fun :D).

**Comment by BlindDespair** [comment]
@aheinze do you have a plan for the next release?
