### ISSUE TITLE
Specify admin user

### ISSUE THREAD

**Issue by Kamshak** [agentejo/cockpit#619]
Hey,

I really like the way i can just do docker run -d --name cockpit -p 8080:80 agentejo/cockpit as you indicate on the website. Only problem: I have no idea what user to put in. Kind of ruins the nice onboarding flow.

Why not add a -e ADMIN_USER=admin -e ADMIN_PASSWORD=password or something similar for getting started quickly. Bettter yet, a demo page :)

**Comment by Kamshak** [comment]
OK i figured it out :) 
Please add a quick line on the homepage to navigate to /install after launching the container

**Comment by jordanboston** [comment]
I think it shows that right here on the setup in the docs: https://getcockpit.com/documentation/getting-started/installation
Under **Create your first user.**

**Comment by Kamshak** [comment]
@aheinze would it be possible to put this into https://getcockpit.com/download below the docker cmdline? Or link to the docs? Would remove some friction from the initial UX.

**Comment by b01** [comment]
So yeah, my eyes jumped past the line "Go to /url/to/cockpit/install in your favorite Browser and follow the instructions." and when straight to the header "Installation using Docker" so I missed that. Would be nice if the first run just takes you to the install, or update the docker doc section to say go to that URL first.

**Comment by Kamshak** [comment]
![img](http://i.imgur.com/sutiDlW.png)

This page is amazing, it's really appealing to just put that command in the command line. Unfortunately after running it you have no idea what to do :smile: It would be soooo great to have that line to navigate to the install page :)

I love this project, just trying to help here :)

**Comment by rm-rf-etc** [comment]
@Kamshak is exactly right

**Comment by kiwimonk** [comment]
This is still a problem

**Comment by asarra** [comment]
Can second that. Still a problem.

**Comment by beasteers** [comment]
+1 I agree that user/pwd via environment variables would be really convenient

**Comment by petersg83** [comment]
I launched Cockpit via Docker, it's been 10 minutes I'm looking what are the default username & password to log in. Still haven't found it.
Would be nice to write what are the default username & password at least on the docker hub page
