### ISSUE TITLE
Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by ayvanov** [agentejo/cockpit#620]
I have Installed Cockpit via
docker run -d --name cockpit -p 8080:80 agentejo/cockpit
After succesfull auth via /api/cockpit/authUser trying to fetch created collection:
/api/collections/get/xxx?token=xxx
Im seeing this response: 
<br />
<b>Warning</b>:  count(): Parameter must be an array or an object that implements Countable in <b>/var/www/html/modules/Collections/Controller/RestApi.php</b> on line <b>47</b><br />

Im using Postman 5.5.0 to access the api
Cockpit version 0.5.1

**Comment by aheinze** [comment]
Thanks for reporting!

**Comment by cve** [comment]
+1

**Comment by MidnightPineapple** [comment]
any ideas on work-arounds yet?

**Comment by finnfiddle** [comment]
+1

**Comment by aheinze** [comment]
this is fixed in the next branch https://github.com/agentejo/cockpit/tree/next
