### ISSUE TITLE
Autocomplete tags

### ISSUE THREAD

**Issue by Turqueso** [agentejo/cockpit#623]
I tried to enable autocomplete on tags, maybe I'm using them wrong? Added this in options for the fieldtype
```
{
    "autocomplete": ["cat1", "cat2"]
}
```

**Comment by template01** [comment]
Ditto. Same issue.

**Comment by woutervddn** [comment]
same issue...

**Comment by woutervddn** [comment]
@aheinze why is this closed? Is there a solution to this?

**Comment by aheinze** [comment]
It is fixed in the mentioned commit

**Comment by woutervddn** [comment]
Sorry... Missed the commit tag... 🙈🙊
