### ISSUE TITLE
Filter by tags

### ISSUE THREAD

**Issue by Turqueso** [agentejo/cockpit#625]
I want to get my collection filtered by tags (with javascript) I had no success so far.

Some things I tried: `filter: {tags: "cat1"}`, `filter: {tags: ["cat1"]}`

**Comment by aheinze** [comment]
could you please try `tags: { $all: [ "cat1" ] }`

**Comment by Turqueso** [comment]
It returns all items from the collection

**Comment by creativeautomaton** [comment]
I found the answer to this on the [cockpit cms  google group](https://groups.google.com/forum/#!topic/cockpitcms/QakVJlALjRA)  but the answer that fixed this for anyone in the future is this below:

ex.
http://{your website }/cockpit/api/collections/get/{yourcollectionname}?token=abd9460d02475ee1da146aff017548&filter[{your field key}]= {your value}

Replace the {} with your values it should look like this:
http://website.com/cockpit/api/collections/get/page?token=abd9340d02475ee1da146aff017548&filter[title]=Mulch Installation

**Comment by willbrowningme** [comment]
@Turqueso I'm using Mongolite and axios and managed to get this working with the following:

```
axios.post(`${env.cockpit.postsUrl}`, 
JSON.stringify({
  filter: { tags: { $has:"the-tag" } },
}),  
{
  headers: { 'Content-Type': 'application/json' }
})
```

Where `env.cockpit.postUrl` is my cockpit posts url endpoint and "the-tag" is just the tag you want to check if the post has.

You can test that it works using postman adding a header with `Content-Type` of `application/json` and a raw body of `{"filter":{"published":true, "tags":{"$has":"laravel"} }}` then sending a post request with your token to your collection endpoint.

It would be great to see some examples like this in the documentation.
