### ISSUE TITLE
More Intuitive Examples for Non-Eggheads ¯\_(ツ)_/¯ ; I dont understand how to access the data

### ISSUE THREAD

**Issue by cedricweatherly** [agentejo/cockpit#626]
> Add content management functionality to any site......ok how?

*Note: I'm not exactly a developer, nor am I exactly a designer. I mostly develop frontend components (HTML/CSS/some JS). I have a working understanding of PHP. All I'm trying to do is connect this CMS to a basic HTML page.

So I found this CMS, and it seemed straight forward up until it was time to access the data and apply it to the page. I just need to know how do I access my data via the API. I have generated a token. But then what? To a person that's not exactly a backend dev, the next step is just missing. I don't exactly work with JSON but I've worked with it before. So do I need to make a call to the API with the token generated...if so how? What is the syntax for the data once I'm able to access it? Is it <div> {{whatever.Code}}</div>? 

If there was a simple Youtube video or screenshots where there was a step by step for dummies like me, I could possibly give this a try. I've searched around but there isn't any more examples beyond me tying cockpit with some other convoluted JS/Node/Static Generator tool.

Currently I've created a collection entry for basic page data (page-title and page-content). This is just for testing purposes. But I can't seem to access the collection data. I keep getting an error whenever I add the token to the top of the page as either a script
`<script src="/api/cockpit/authUser?token=0a014d090bf541dc7482939f22841e'"></script>` 
or as the example you have in the documentation
`
	
	fetch('/api/cockpit/authUser?token=0a014d090bf541dc7482939f22841e')
		.then(res => res.json())
    	.then(res => console.log(res));
	
`

Also, I'm trying to do this all locally. If thats my issue this need to be stated somewhere in the documentation, but I would figure I would be able to access the data locally. Could someone help, or email me for quick answers....thanks!

**Comment by angganegara** [comment]
You can use php curl to access the API endpoint. or you can use axios if you simply want to connect it to your html with a basic js. Install axios using any methods you prefer, include it in your html file, then simply copy the example code in the documentation but replace fetch with axios.get and you sohuld get your data.

**Comment by cedricweatherly** [comment]
Ok, so I was able to get the data to come through in the console. Apparently you don't need 
`.then(res=> res.json()))`
for Axios. Found this out after hours of researching why I kept getting 
`Uncaught (in promise) TypeError: res.json is not a function`

Now I just need to know how I can pull certain entries from my collection and applying them on the page. Or at least how to filter entries from others. So say I made a Pages collection with an entry for page.Title, how do I echo out this page title to the page I want with Axios? Sorry for the noob questions but I'm really just trying to learn because this decoupled CMS seems pretty interesting.

**Comment by angganegara** [comment]
That's also explained in the doc. You make a POST to your endpoint and use `filter` to filter the data. Here's how I did it in my recent project.

`axios({`
`  method: 'post',`
`   url: '/cockpit/api/collections/get/Gallery?token='+ this.$root.apikey,`
`        headers: { 'Content-Type': 'application/json' },`
`        data: JSON.stringify({`
`          filter:{'_id': 12345},`
`          limit: 1`
`        })`
`      }).then((res) => console.log(res.data));`

hope this helps
