### ISSUE TITLE
On image upload, ColorThief memory exception

### ISSUE THREAD

**Issue by justrealmilk** [agentejo/cockpit#627]
<b>Fatal error</b>:  Allowed memory size of 103809024 bytes exhausted (tried to allocate 32 bytes) in <b>/lib/ColorThief/Image/Adapter/GDImageAdapter.php</b> on line <b>96</b><br />

Can we just have the option to disable ColorThief altogether? 

First error of its kind I've encountered, probably due to the image having a resolution of 3840x3840.

**Comment by aheinze** [comment]
could you please try the latest codebase from the next branch? - https://github.com/agentejo/cockpit/tree/next
