### ISSUE TITLE
How to upload images through the API?

### ISSUE THREAD

**Issue by afilina** [agentejo/cockpit#630]
I went through all the API docs and couldn't find how to upload media through the API. I tried to guess by checking my network tab and tried posting to `media/api?token=abc`, but it tells me that I'm not authenticated.

**Comment by aheinze** [comment]
there is no api yet to add assets. this is only possible in the admin ui right now.

**Comment by Solinx** [comment]
@aheinze Do you have any plans for such a feature? I really like the look of this headless CMS, but I really could use the ability to upload assets and files through the API.

**Comment by fabianmu** [comment]
I need that too and came up with this ugly hack... not nice to bypass the API but it works well enough ;)
In order to make this work I am just posing the image just like the CMS would do to the assetmanager and am passing the cookie of a logged in user `$cookieValue`, dunno but one may also need to adjust the cookie-key `40d1b2d83998fabacb726e5bc3d22129` in my case.

```php
use GuzzleHttp\Client as CMS;

 private function _uploadAsset($assetSourceUrl) {
        $cmsClient = new CMS();
        $cookieValue = "get the cookie from any browser"
        $event = $cmsClient->post("http://CMS-HOST/assetsmanager/upload", [
            'headers' => [
                'Accept' => 'application/json',
                'Accept-Language' => 'en-US,en;q=0.5',
                'Accept-Encoding' => 'gzip, deflate',
                'Cookie' => '40d1b2d83998fabacb726e5bc3d22129=' . $cookieValue
            ],
            'multipart' => [
                [
                    'name'     => 'files[]',
                    'contents' => file_get_contents($assetSourceUrl),
                    'filename' => '_entry.jpg'
                ]
            ],
        ]);
        return json_decode($event->getBody()->getContents());
    }
```

**Comment by iryanrachman** [comment]
where do we put that ?
