### ISSUE TITLE
Filter by collection link

### ISSUE THREAD

**Issue by NMathar** [agentejo/cockpit#631]
Is it possible to filter collection by link data? A quick example would be great.

**Comment by NMonst4** [comment]
Example:
`    {
        "name": "Test Product",
        "price": 2,
        "size": "200 ml",
        "picture": "",
        "quantity": 2,
        "min_quantity": 1,
        "isremoved": false,
        "location": {
            "_id": "5a21afc56b326doc1808959226",
            "link": "location",
            "display": "Fridge"
        },
        "_mby": "5a2186d123da4doc1779419057",
        "_by": "5a29b20cdc1fedoc2115936280",
        "_modified": 1514399134,
        "_created": 1512156966,
        "_id": "5a21af263640ddoc1642799047",
        "_order": 0,
        "barcodes": [
            {
                "_id": "5a29a4eed0618doc1840030729",
                "link": "barcode",
                "display": 2343245
            },
            {
                "_id": "5a2c1d1126ffbdoc2017858211",
                "link": "barcode",
                "display": 324143532
            },
            {
                "display": 42141112,
                "link": "barcode",
                "_id": "5a43e59eec741doc1305024509"
            }
        ]
    }`

And i need to filter the product by barcodes i tried this:

`filter: {'barcodes.display': 42141112}`

`filter: {'barcodes.barcode': 42141112}`

`filter: {'barcodes': [{'barcode': 42141112}]}`

`filter: {'barcodes': { $elemMatch: { 'barcode': 42141112 } }}`

`filter: {'barcodes': { $match: { 'barcode': 42141112 } }}`

**Comment by drnasin** [comment]
@NMonst4  did you manage to solve this?I have the same issue....

**Comment by NMonst4** [comment]
@drnasin Sadly not i hope some of the project maintainer could help.

@aheinze A bit more information in the documentation would be very helpful especially the filter part.

**Comment by voncount** [comment]
You have to use $elemMatch to filter array in MongoDB

The correct way should be
`filter: {'barcodes': { $elemMatch: { 'display': 42141112 } }}`

If you want to use additional fields in barcode you need to add `populate: 1` to your query first

**Comment by NMonst4** [comment]
hi @voncount ,

thank you for your answer. Thats the logical way but if i add this i get a 406 Response from cockpit. :(

**Comment by voncount** [comment]
[HTTP 406](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406)

something wrong with your request headers and server response

**Comment by NMonst4** [comment]
More Details:
Filter:
`filter: {"barcodes": {$elemMatch: {"display": 42141112}}}`

Response 406 Not Acceptable

`{
"error": true,
"message": "Condition not valid ... Use $elemMatch for custom operations"
}`

**Comment by voncount** [comment]
Did you try with postman?
I can filter this way with both postman and javascript client

**Comment by NMonst4** [comment]
I test it with advanced REST client (chrome extension) and i get this error in my decoupled app with axios and in my chrome extension.

**Comment by voncount** [comment]
Strange because i use axios too
Here is my method
axios.post('api URL', { filter: { categories: { $elemMatch: { _id: 'some ID' } } } })

Notice the apostrophe when using axios

**Comment by NMonst4** [comment]
Really strange.

Now i test it with the same filter string in axios and Postman:

Filter:
`filter: { barcodes: { $elemMatch: { _id: '5a43e59eec741doc1305024509' } } }`

Axios -> still 406
Postman -> All Results no filter :D 

I dont know what i doing wrong i use a docker container of the cockpit master branch.

**Comment by Sephen** [comment]
I'm also experiencing 406 errors with the filtering on collection links:

```
{
    "error": true,
    "message": "Oooops, something went wrong."
}
```
the filter is use
`filter: { categories: { _id: '5a8fcd26765c9doc563517609'  } }`

I'm using vue.resource

Without the filter everything is returned as expected

**Comment by voncount** [comment]
_id is very different from node js world, i don't have time to dig into the source code but i think you can only filter fields that you defined in the backend not auto generated fields

**Comment by Sephen** [comment]
Has anyone found a solution for this? I really like this cms but i'm still not able to use the collectionlink.

**Comment by RoelantStegmann** [comment]
This is closed so it is not possible? :)

**Comment by christophermiles** [comment]
I have run into this too, but I'm not even filtering on a collection link

**Comment by drascom** [comment]
> I have run into this too, but I'm not even filtering on a collection link

i had exactly same issue.i removed database records from sql and deleted all related files from storage.than recreate same collection and field than problem solved.
it is probably related some records cockpit created with this collection.
