### ISSUE TITLE
Localized fields still returned localized result after disable localization.

### ISSUE THREAD

**Issue by anthonyivol** [agentejo/cockpit#632]
I still get localized API results for fields that I disable the Localize option. The same behavior appears when I remove a language from the config.yaml, I still get myfield_[isocode] in results.

And clearing cache doesn't solve that.

my version of cockpit : v0.5.1

Any idea ?

**Comment by aheinze** [comment]
this is right, once saved data stays after saving...

**Comment by anthonyivol** [comment]
Ok... is there a way to remove it manually ?

**Comment by drnasin** [comment]
Hi, I have the same issue. is there a solution for this? If not then cocpkit is pretty much useless. Every time you change something in the structure you have to delete all the related data and enter them again!? Same happened to us when we changed name of the PARENT category...it was never reflected on children so we had to "re-link" (to same category basically) the whole gallery. I thought cockpit was suppose to save me time?

**Comment by drnasin** [comment]
@anthonyivol did you manage to solve this?

**Comment by anthonyivol** [comment]
@drnasin unfortunately nope

**Comment by drnasin** [comment]
Thanks @anthonyivol, so pretty much the thing is useless for any normal usage...
