### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by justrealmilk** [agentejo/cockpit#633]
What is the actual latest version?
Is the latest release as per /agentejo/cockpit/releases?
What are the risks of replacing everything but the database and file storage?
Are there any changes to how cockpit interacts with the database?

Not so much an issue, but it'd be good to have clarification. Perhaps someone, not necessarily always @aheinze  because he's a busy bee, could update the readme with the latest numbers to look for?

And maybe even add those basic instructions on which folders to replace when updating.

**Comment by drnasin** [comment]
Seems to me both are pretty much useless for any normal usage. Documentation is all over the place, half of features are not documented or documented wrong, you have no idea for which version are the docs or solutions given here to people..bugs all over and no support. Even your valid concern is sitting here for 9 days already...I'm staying clear of this project...looks good on paper but it went wrong somewhere obviously...

**Comment by aheinze** [comment]
@drnasin well, it is an open source project (no money involved). so it might be better to contribute/help out instead of complaining ... just as a suggestion 🤷‍♂️

**Comment by aheinze** [comment]
@justrealmilk the latest version is always the master branch, the next branch is the current dev version.

Regarding updating: https://getcockpit.com/documentation/getting-started/installation

- Backup!!!
- Download and unzip your desired version of Cockpit
- Override the whole cockpit directory except the config and the storage folder.

**Comment by drnasin** [comment]
@aheinze I understand but lack of time is not a valid reason for releasing half finished work...it is a good excuse but a bad reason...

**Comment by justrealmilk** [comment]
@aheinze Finally getting around to this but I don't have a config folder. After some browsing, I've found my .sqlites under storage/data and there is no config folder

**Comment by justrealmilk** [comment]
?????????????????

**Comment by justrealmilk** [comment]
?

**Comment by aheinze** [comment]
the config folder will get auto-created created if you override the default settings in SETTINGS > SYSTEM SETTINGS (backend)

**Comment by piotr-cz** [comment]
I think a [changelog](keepachangelog.com) would come handy, or at least mentioning release highlights on [Releases](https://github.com/agentejo/cockpit/releases) page
