### ISSUE TITLE
API access keys not working

### ISSUE THREAD

**Issue by Kalcode** [agentejo/cockpit#634]
Current Build: Docker Image (0.5.1)

It seems the the api tokens generated are not working in the token parameter.

```
'/api/collections/save/posts?token=xxtokenxx'
ex: /api/collections/save/posts?token=2fc85cdfdb824e7c03a7f3941e211d
```
I get "error": "Unauthorized"
or
"
Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/modules/Collections/Controller/RestApi.php on line 47"

Any api key I generate for full access token doesn't work here. Nor do the custom keys.

If I go to a user and use the account-api

```
/api/collections/save/posts?token=account-6ead5e82b0bac7e02599c4b9a5ba68
```

this works with all the endpoints.

**Comment by dubaua** [comment]
yup, I encountered same problem.
I have `/api/collections/save/orders` in my custom api key rules, then I try to save data
```
  fetch(`/api/collections/save/orders?token=${process.env.API_KEY}`, {
    method: 'post',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      data: order,
    }),
  })
```
Got `{error: "Unauthorized"}`.
Saving works only with admin account api key, but this is don't fit, because its unsecure.

**Comment by frankjonen** [comment]
You're lucky. All I get is:  `PHP Notice:  Undefined index: admin in /Applications/MAMP/htdocs/cockpit/lib/Lime/App.php on line 1261` 

The API doesn't even respond.
