### ISSUE TITLE
How to do LIMIT and OFFSET in API?

### ISSUE THREAD

**Issue by sonyarianto** [agentejo/cockpit#635]
I am testing cockpit and success doing limit like below.

http://localhost:1000/api/collections/get/posts?token=my_token&limit=1

Question:
How to do limit based on particular offset?

**Comment by sonyarianto** [comment]
http://localhost:1000/api/collections/get/posts?token=my_token&limit=1&skip=5

will do ya, great

**Comment by gryphonmyers** [comment]
Yup seems like you figured it out! You should close your issue to reduce clutter for @aheinze ;)
