### ISSUE TITLE
Next: Forms API

### ISSUE THREAD

**Issue by davidenke** [agentejo/cockpit#638]
Hi,

is there a way to send forms using the API? Is there anything implemented yet? Or does anybody has experiences to share?
 
I created a form called 'registrations' and tried to POST data to it using `link/to/cockpit/api/forms/submit/registration?token=XXXXXXXXXXXXXXXXXXXX`, but I always get `Path not found`.

**Comment by huleos** [comment]
frustrante

**Comment by aheinze** [comment]
```
fetch('/api/forms/submit/newsletter?token=xxtokenxx', {
        method: 'post',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            form: {
            fieldnamex: value,
            fieldnamey: value
          }
        })
    })
```

**Comment by JulioC** [comment]
@aheinze is this available on 0.5.3?

**Comment by davidenke** [comment]
@aheinze does that mean, that every form is available at the `newsletter` path? I can't see how the data will be mapped to the form than.

**Comment by sevenOneHero** [comment]
does this work in postman ?

**Comment by davidenke** [comment]
@sevenOneHero Yes, I always test with Postman or curl. And no it does not work.

**Comment by sevenOneHero** [comment]
@davidenke I got it working 

you need to wrap your input params in a 'form' object like this

```
{
	
	"form" : {
		"name": "Vinit",
		"gender": "Male"
	
}
}
```

**Comment by davidenke** [comment]
@sevenOneHero But the basic question was how the url is formed. Do I have to send arbitary form data to a specific url matching my individual form, or is it always the newsletter url (`/api/forms/submit/newsletter?token=xxtokenxx`)? And if it is the newsletter url, how is the data mapped to my form than?

**Comment by sevenOneHero** [comment]
@davidenke  you have to create a form inside your cockpit cms

![screen shot 2018-03-07 at 3 58 33 pm](https://user-images.githubusercontent.com/6957759/37087505-78d9188c-2220-11e8-8a21-16fa52222a1f.png)

**Comment by davidenke** [comment]
@sergeypavlenko Yes, of course. I'll give it another try.

**Comment by vovaleontiev** [comment]
I have the same issue (Server says 404), but..
When i use the url without `?token=xxx` server doesn't send me 404 status.
Instead, it send me json response `{"error":"Unauthorized"}`

**Comment by woutervddn** [comment]
@vovaleontiev in your collection/singleton/... settings, click on the permissions tab and set the appropriate actions to available under the public part.

**Comment by bikeholik** [comment]
just as an observation returning 400 instead of 404 when form data is not wrapped in form object would give better information
