### ISSUE TITLE
How it's create / update entry with axios

### ISSUE THREAD

**Issue by huleos** [agentejo/cockpit#639]
this my code: 
```
let data = {
    author: 'John Doe',
    content: 'Something',
    published: true
}

axios.post(config.apiUrl + '/api/collections/save/quotes?token=' + config.apiKey, data)
.then(response => {
    console.warn(response.data);
})
```

**Error:** 
createError.js?16d0:16 Uncaught (in promise) Error: Request failed with status code 404
    at createError (createError.js?16d0:16)
    at settle (settle.js?db52:18)
    at XMLHttpRequest.handleLoad (xhr.js?ec6c:77)

what is wrong?

thank you for your help

**Comment by NMonst4** [comment]
Hi huleos,

can you try this.

````javascript
let quotes = {
    author: 'John Doe',
    content: 'Something',
    published: true
}
axios.post(config.apiUrl + '/api/collections/save/quotes?token=' + config.apiKey,{
            data: quotes 
          })
.then(response => {
    console.warn(response.data);
})
````

**Comment by huleos** [comment]
Thanks @NMonst4 , it has worked for me.
Sorry, will you know how to make the cockpit forms work?

**Comment by NMonst4** [comment]
No sorry I didn´t  worked with forms. 😞  I stopped working with this great tool because of missing documentation.

**Comment by huleos** [comment]
yup, it's a shame 😞

**Comment by vinkodlak** [comment]
@NMonst4 what do you use instead?

**Comment by NMonst4** [comment]
hi @vinkodlak  I played around with many api frameworks and end up with two. For PHP API-Platform https://github.com/api-platform/api-platform and for Nodejs TypeORM with Restify Simple Example here https://github.com/NMonst4/event_api

**Comment by funkvn** [comment]
@NMonst4 Thanks for your link to API Platform. This was new to me and seems to be a very good approach.

The missing documentation of Cockpit is a serious impediment. Sadly.

**Comment by sebastianks** [comment]
@funkvn If you want to contribute to the documentation, feel free to make a PR here: https://github.com/agentejo/cockpit-docs

**Comment by funkvn** [comment]
@sebastianks I started this some days before. Just look at the commits: https://github.com/agentejo/cockpit-docs/commits/master

But the master isn't yet deployed to https://getcockpit.com/documentation. I will ping @aheinze to do that in a next PR.
