### ISSUE TITLE
[Proposal] Support multiple collection types on Collectionlink field

### ISSUE THREAD

**Issue by pauloamgomes** [agentejo/cockpit#646]
Currently the field Collectionlink provides a reference to a collection, I see some use cases where it could be interesting to support multiple collection types instead of only one, for example, we can have a set of components (e.g. faq, top10, show/hide, block, etc..) that we may want to reference on a basic page collection by using a component field.

**Comment by pauloamgomes** [comment]
Since not sure if should submit this as a patch on the original Collection link field, I created it as a new addon. Basically, I'm extending the existing code in a way that supports what is requested. Addon is available on https://github.com/pauloamgomes/Cockpit-MultipleCollectionLink

Happy for feedback

**Comment by gryphonmyers** [comment]
I may be misunderstanding the proposal, but couldn't you accomplish this via a repeater with the supported collection links as options?

**Comment by pauloamgomes** [comment]
Hi @gryphonmyers , don't think that works with a repeater, above example seems to fail to render the collection link fields

**Comment by AdictoChannel** [comment]
Hi @pauloamgomes, for me it worked as described by @gryphonmyers. Although the options look slightly different for me:

```
{
"fields": [
      {
        "type": "collectionlink",
        "options": {
          "link": "myCollectionA"        
         }
      },
      {
        "type": "collectionlink",
        "options": {
          "link": "myCollectionB"        
         }
      } 
    ]
}
```

**Comment by pauloamgomes** [comment]
Hi @AdictoChannel, yes, your example works, and adding a label will help on identify the field to add:

```
{
"fields": [
      {
        "type": "collectionlink",
        "label": "myCollectionA",
        "options": {
          "link": "myCollectionA"        
         }
      },
      {
        "type": "collectionlink",
        "label": "myCollectionB",
        "options": {
          "link": "myCollectionB"        
         }
      } 
    ]
}
```
however still believe that an approach of having that by default is better, that's the reason of https://github.com/pauloamgomes/Cockpit-MultipleCollectionLink, I think it results better to handle and reorder the linked items.

**Comment by FlexTG** [comment]
hi 
one question regarding the collectionlink
is it also possible to set a default link? 
I tried but can't get to work properly...

**Comment by pauloamgomes** [comment]
Hey @FlexTG , yes, its possible, just use the default attribute and provide the collection _id you want to link, e.g.:

```
{
  "link": "page",
  "display": "title",
  "multiple": false,
  "default": {
    "_id": "5c5851e8e8f61c00443551cb",
  }
}
```

**Comment by FlexTG** [comment]
@pauloamgomes thank you!
