### ISSUE TITLE
Content Preview: bind attribute to url

### ISSUE THREAD

**Issue by template01** [agentejo/cockpit#649]
Hay Artur Heinze,

Looking into Cockpit a bit. It has really developed the last year! Hope this continues! It seems so mature that we're considering using it for production. 

Curious how the 'Content Preview' works. Is it possible to bind an attribute to the url you want to direct to? Say the _id or another attribute of the collection item. Would be really great! Something like: www.yourdomain/posts/{{_id}}

Cheers
Lasse

**Comment by aheinze** [comment]
Hi Lasse,

all needed data is send to the provided preview url: 

https://github.com/agentejo/cockpit/blob/next/modules/Collections/assets/collection-entrypreview.tag#L271-L282

Greets
Artur

**Comment by template01** [comment]
Ah. Nice. 
So basically you let the iframe/frontend react to this event by listening in. Something like:

```
window.addEventListener('data',function(event) {
	console.log('message received:  ' + event.data,event);
},false);
```
Cheers

**Comment by aheinze** [comment]
right ;-)

**Comment by template01** [comment]
Top. I'll try it out! Cheers
