### ISSUE TITLE
Custom nosql Database

### ISSUE THREAD

**Issue by tmvnk** [agentejo/cockpit#651]
For example I would like to connect Cockpit CMS to a DynamoDB

**Comment by aheinze** [comment]
Sorry, no plans for that right now.

**Comment by tmvnk** [comment]
Maybe any tips how I can do this myself? Which controller/service to change?

**Comment by aheinze** [comment]
take a look at the storage service https://github.com/agentejo/cockpit/blob/next/bootstrap.php#L115-L118
