### ISSUE TITLE
Gallery Thumbnails Not Loading - url Undefined

### ISSUE THREAD

**Issue by B-Stewart** [agentejo/cockpit#653]
I'm running into an issue where gallery thumbnails don't load on a fresh install of cockpit on:
Server: Local MAMP
PHP: 7.0 (Also tried 7.1)
Cockpit version: 0.5.1
Browser: Latest Firefox and Chrome

Any gallery thumbnails I upload to a collection are not loading into the collection entry. The assets work fine in the asset manager and selector but there is just an infinite load spinner on the thumbnail within the collection. 

My console is throwing a 'url is undefined' error and has send to the background image url not being set. I've added a comment to the code below to identify the line for you and given some context as to what the browser is reporting. Potentially you are relying on a time delay for the url to be set and it's being called before the url is actually set?

![screen shot 2018-01-31 at 10 06 23 am](https://user-images.githubusercontent.com/7998805/35639422-11ed293c-066f-11e8-9327-20a5f7e710a6.png)

```
requestAnimationFrame(function() {

                if (_src.match(/^(http\:|https\:|\/\/)/)) {

                    setTimeout(function() {
                        App.$($this.refs.canvas).css({
                            backgroundImage: 'url('+url+')', //THIS LINE THROWS url UNDEFINED ERROR
                            backgroundSize: 'contain',
                            visibility: 'visible'
                        });

                        $this.refs.spinner.style.display = 'none';
                    }, 50);

                    return;
                }

                App.request('/cockpit/utils/thumb_url', {src:_src,w:opts.width,h:opts.height,m:mode}, 'text').then(function(url){

                    if (_src.match(/\.svg$/i)) {
                        url = _src;
                    }

                    src = _src;

                    setTimeout(function() {
                        App.$($this.refs.canvas).css({
                            backgroundImage: 'url('+url+')', 
                            visibility: 'visible'
                        });

                        $this.refs.spinner.style.display = 'none';
                    }, 50);

                }).catch(function(e){});
            });
```

**Comment by aheinze** [comment]
could please test the next branch?

**Comment by sodhancha** [comment]
Did it work @B-Stewart ? using the next branch ?
Cause doesn't seem to work with master
