### ISSUE TITLE
Deprecated: Function create_function() is deprecated in lib/MongoLite/Database.php on line 107 on PHP 7.2.1

### ISSUE THREAD

**Issue by fabianmu** [agentejo/cockpit#655]
Running the next branch (head at d6aea947f2302b97bc0c9e165ec292288ef76b4f) Version | 0.5.1, PHP 7.2.1-1+ubuntu16.04.1+deb.sury.org+1 throws the error `Deprecated: Function create_function() is deprecated in lib/MongoLite/Database.php on line 107`

Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imap, intl, json, exif, msgpack, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, memcached, Zend OPcache

**Comment by aheinze** [comment]
I do already a check whther the `create_function` function exists or not:

https://github.com/agentejo/cockpit/blob/master/lib/MongoLite/Database.php#L104-L108

So the lib should still work as expected. what you have to do on your side is to disable deprecated notices

**Comment by trk** [comment]
Using PHP 7.2.5 and changed this function, if i get any error i will let you know.
```php
// $fn = create_function('$document','return '.UtilArrayQuery::buildCondition($criteria).';');
$fn = $fn = function($document) use ($criteria){ return UtilArrayQuery::buildCondition($criteria); };
```

**Comment by piotr-cz** [comment]
Problem is, that  `create_function` exists in PHP 7.2 but triggers deprecated error.
Temporary workaround is to disable deprecated errors in custom bootstrap file:

```php
// config/bootstrap.php

// Tweak error_reporting to ignore E_DEPRECATED triggered by create_function deprecated in PHP 7.2
error_reporting(error_reporting() & ~ E_DEPRECATED);
```
