### ISSUE TITLE
When using Link Collection the link value is not returned when populate=1

### ISSUE THREAD

**Issue by pauloamgomes** [agentejo/cockpit#656]
When implementing the multiple collection link addon, discovered that the link value of the collection link is not returned if we have populate = 1, that seems to happen during:

`$items[$k] = cockpit('collections')->_resolveLinedkItem($v['link'], $v['_id'], $fieldsFilter);`

so resuming, if populate is not set we receive the linked collection as below:

```
[
    {
        "name": "test",
        "component": {
            "_id": "5a71181540289doc371271402",
            "link": "simpleblock",
            "display": "Block 1 - Contacts"
        },
        "_mby": "5a61396e7640edoc1261186187",
        "_by": "5a61396e7640edoc1261186187",
        "_modified": 1517518388,
        "_created": 1517518388,
        "_id": "5a737e34a6ed7doc739007011"
    }
]
```

if populate is set we receive the linked contents but not the linked collection name:

```
[
    {
        "name": "test",
        "component": {
            "name": "something",
            "content": "contents",
            "_mby": "5a61396e7640edoc1261186187",
            "_by": "5a61396e7640edoc1261186187",
            "_modified": 1517361210,
            "_created": 1517361173,
            "_id": "5a71181540289doc371271402"
        },
        "_mby": "5a61396e7640edoc1261186187",
        "_by": "5a61396e7640edoc1261186187",
        "_modified": 1517518388,
        "_created": 1517518388,
        "_id": "5a737e34a6ed7doc739007011"
    }
]
```

Believe that is important to have the linked collection name on the response as we may need to have some logic based on it on the client side application.

**Comment by pauloamgomes** [comment]
Created a possible fix on the PR #657 , kindly confirm that make sense

**Comment by aheinze** [comment]
Hmm, but what if the linked collection has a field named link? so maybe instead of `link` -> `_link` ? I'm not sure about the name...do you have a suggestion?

**Comment by pauloamgomes** [comment]
Yep, agree as it follows the same pattern for the reserved fields (e.g. _id, _created, etc..)
