### ISSUE TITLE
Collection timestamp

### ISSUE THREAD

**Issue by julienchazal** [agentejo/cockpit#659]
Hello
Is it possible to add a timestamp to a collection, which will be updated when adding an entry for example ?

Something like this : 
```json
{
"fields": {},
"entries": [],
"total": 3,
"timestamp": 1517868735
}
```
thx

**Comment by tomdupont** [comment]
Hi @julienchazal,

There would be a workaround by doing also a post request with following payload:
a sort on _modified (or _created) and a limit of 1.

```
{
   "limit": 1,
   "sort": {"_modified": -1}
}
```

Then you would get the timestamp value by doing for example in PHP:
$response->entries[0]->_modified

**Comment by julienchazal** [comment]
thx @tomdupont 
nevermind i'll do with the collections entries timestamps ;)
