### ISSUE TITLE
Multilingual collections

### ISSUE THREAD

**Issue by diamantisk** [agentejo/cockpit#660]
Hello guys,
Does any body knows a way to have multilingual versions of a collection entry for example?
Is something that can be done in cockpit?
Regards,
Diamantis

**Comment by tomdupont** [comment]
Hi @diamantisk!

In the cockpit admin go to settings -> settings add the following to the config.yaml file:
```
# define the languages you want to manage
languages:
    en: Englisch
    nl: Dutch
```

Then while adding or editing fields of a collection you can _Localize_ a field. When creating or editing a entry you can select the language on the right sidebar.

See the orange boxes on the images to clarify the last 2 steps.

![schermafbeelding 2018-02-06 om 18 20 59](https://user-images.githubusercontent.com/15290357/35873782-0a3ef9c6-0b6b-11e8-8a0f-66e712a9aeea.png)
![schermafbeelding 2018-02-06 om 18 22 03](https://user-images.githubusercontent.com/15290357/35873783-0a5a2bd8-0b6b-11e8-8ca0-6bf18cff225b.png)

**Comment by diamantisk** [comment]
It worked as expected! Thank you very much!
