### ISSUE TITLE
In next version, possible bug with pictures from assets? I see only the spinner.

### ISSUE THREAD

**Issue by diamantisk** [agentejo/cockpit#663]
Dear team,
I am facing an issue in Regions module.
When i select a picture from Assets to an assets field type as defined in a region, the picture is not displayed at all and i just see the loading spinner, spinning for ever.
After some testing and firebug monitoring, i managed to fix it somehow by changing the following from:

var SITE_URL   = '{{ rtrim($app->pathToUrl('site:'), '/') }}';
To: 
var SITE_URL = 'http://admin.myperfectsite.com{{ rtrim($app->pathToUrl('site:'), '/') }}';
        
Well, no matter if it works now with the above fix, i feel that something is going wrong. Does anybody have any idea regarding this behaviour ?
Im on PHP > 7.0 behind NGINX. 

With Regards,
Diamantis

**Comment by aheinze** [comment]
Thanks for reporting!
