### ISSUE TITLE
Upload Large Size Images

### ISSUE THREAD

**Issue by tripti20** [agentejo/cockpit#664]
Hi,

Thanks for a great tool.
I am facing issue uploading image of 11mb size.
It doesn't upload in cms/upload/storage/ folder.
Is there any restriction for the image size? 
I need to upload large size image for some 360 view.
I can't reduce the image size.
 Is there any way I can acheive this?

**Comment by aheinze** [comment]
I would suggest that you increase the `post_max_size` and `upload_max_filesize` in your php.ini.

greets
artur
