### ISSUE TITLE
Problem resolving full version of images (url is wrong)

### ISSUE THREAD

**Issue by diamantisk** [agentejo/cockpit#665]
Dear friends,
In next version, i noticed an issue in gallery type field and especially in full size preview url.
The thumbnail version is displayed properly but when we click the button to display the full version, cockpit tries to resolve from an invalid address of type: http://storage e.t.c.
This happens because of an extra slash which exists in the right size of relative image url. Double slash are treated as a wildcard protocol (automatic inherits http or https, whichever is in use).

More info in screens attached:

<img width="817" alt="screen shot 2018-02-11 at 01 04 54" src="https://user-images.githubusercontent.com/2445630/36067572-2ba26980-0ec8-11e8-8362-80464c4add6b.png">
<img width="481" alt="screen shot 2018-02-11 at 01 04 19" src="https://user-images.githubusercontent.com/2445630/36067573-2bca849c-0ec8-11e8-8634-c392353d43e8.png">
<img width="258" alt="screen shot 2018-02-11 at 01 04 12" src="https://user-images.githubusercontent.com/2445630/36067574-2bf2808c-0ec8-11e8-95bd-844c049fd8bf.png">

**Comment by aheinze** [comment]
Thanks for reporting! Fixed now in the next branch.
