### ISSUE TITLE
collectionlink option name is not given 

### ISSUE THREAD

**Issue by arismarko** [agentejo/cockpit#666]
When a try to add a link to a collection another collection I dont get the drop down i used to get in the old version. 

![screen shot 2018-02-11 at 10 53 30](https://user-images.githubusercontent.com/281849/36072591-e7694322-0f19-11e8-9daf-2a7495fd447c.png)

**Comment by tomdupont** [comment]
Hey @arismarko 

In the new/current "next" version you need to specify this as json options. This are all the available options for the collection link field.

``` json
{
    "link": "collectionname",
    "multiple": false,
    "display": "fieldname",
    "limit": false
}
```

You can find all these in the [fieldtype documentation](https://getcockpit.com/documentation/reference/fieldtypes)
