### ISSUE TITLE
Problem with API token in next version?

### ISSUE THREAD

**Issue by diamantisk** [agentejo/cockpit#668]
Dear team,
I have set an API key as follows:
<img width="823" alt="screen shot 2018-02-12 at 23 57 02" src="https://user-images.githubusercontent.com/2445630/36121976-78ed18fa-1050-11e8-9226-3277daa65520.png">

But when i'm trying to use it, i always get an "Unauthorized" error.
<img width="1089" alt="screen shot 2018-02-12 at 23 58 07" src="https://user-images.githubusercontent.com/2445630/36122022-a10dcd02-1050-11e8-940c-814ba6b2b455.png">

I tried multiple times by generating new keys with the same result. 

What i noticed is that api.keys.txt is that characters are damaged. Possibly is normal but i just put it on the table:

<img width="602" alt="screen shot 2018-02-13 at 00 01 21" src="https://user-images.githubusercontent.com/2445630/36122191-2396d69c-1051-11e8-9106-0ae094347464.png">

With Regards,
Diamantis

**Comment by tomdupont** [comment]
Hi @diamantisk,

In the screenshot I see _/api/collections/get_ but such a route is not existing (in the current version). But probably you tested it already with one of [these routes](https://getcockpit.com/documentation/api/collections) However it would show up as
`{"error": "Missing collection name"}`

I can confirm that my working installations also don't have plaintext keys in api.keys.php.

Trying the same setup on the latest version is working in Postman:
![schermafbeelding 2018-02-13 om 07 42 38](https://user-images.githubusercontent.com/15290357/36136581-8d0532fa-1091-11e8-9066-1a355bc5474b.png)

**Comment by diamantisk** [comment]
Hello Domdupont,
Thank you for the reply. Well, i also tried the same endpoint you did, but with the same result. Please see the screen:

<img width="954" alt="screen shot 2018-02-13 at 10 05 24" src="https://user-images.githubusercontent.com/2445630/36139238-74f4c450-10a5-11e8-9005-e1c48093691e.png">

For some reason i keep getting the Unauthorised error and i'm wondering if i did something wrong. Im using the "next" branch not the current stable which in my initial setup worked as expected. The main reason i moved to next, is that it contains several fixes especially regarding in view paths of assets e.t.c.

With Regards,
Diamantis

**Comment by diamantisk** [comment]
Finally i managed to solve the issue. It wanst cockpit's fault but nginx faulty configuration regarding API endpoint. I configured nginx to route everything to index.php (which will handle the routes internally) and it worked. Apologizes for this issue post, it was my fault
