### ISSUE TITLE
regions.save nor regions.save.after triggering webhook

### ISSUE THREAD

**Issue by fabianmu** [agentejo/cockpit#670]
Neither `regions.save.after` nor `regions.save` triggers webhooks :( I am using `collections.save.after` for another hook and that one works just fine.  
Someone has a hint? Thanks.

**Comment by aheinze** [comment]
Hi,

tested webhook against https://requestb.in and it works fine for me 🤔

**Comment by tomdupont** [comment]
Hi,

I tested it myself, and I am having the same results. _regions.save.after_ , _regions.save_ and _regions.save.after.{name}_ are not working (like expected). While the collections.save.after.test works in this setup:
![screen shot 2018-02-16 at 08 30 28](https://user-images.githubusercontent.com/15290357/36297615-04f9882e-12f4-11e8-9d63-32e21604db87.png)

**Comment by tomdupont** [comment]
Found the issue:

The regions.save and regions.save.after.{name} were only added on 21 December 2017 in commit [#9e76da](https://github.com/agentejo/cockpit/commit/9e76daea191029c1ea02fa54398532a6ac6da0e0#diff-769d4fbd3106788456a9b1acb6b5329a)
        
Updating to the next branch solves the "problem"

**Comment by fabianmu** [comment]
I've been using the next branch obviously. Sorry, my fault. i oversaw a really stupid thing on my end. All fine, sorry for the confusion!
