### ISSUE TITLE
[Suggestion] Default font-weight 300 -> 400

### ISSUE THREAD

**Issue by justrealmilk** [agentejo/cockpit#671]
Adjust font-weight to 400.

![capdfgdfgdture](https://user-images.githubusercontent.com/156681/36349252-bf403662-14cd-11e8-968c-582d9cb1a628.PNG)

I bet the design choice was made on OS X where fonts render chunky and the default font isn't Segoe and that's fine but with every deployment I need to manually edit Cockpit's CSS!

**Comment by cesasol** [comment]
I created a userstyle for this, but you are right, this must be dealt from upstream.
