### ISSUE TITLE
[Help] Intended use case of "access list" field type

### ISSUE THREAD

**Issue by gryphonmyers** [agentejo/cockpit#676]
I recently noticed the "access list" field type, and was hoping you might explain how it's supposed to work. For a moment, I was very excited because I thought you had added a way to provide per-entry overrides of collection-level permissions. I attempted a basic test though and it didn't seem to do what I was hoping.

**Comment by aheinze** [comment]
Hi Gryphon,

the access list is just a field type to select groups and users. what you're doing with the data, is then up to you.

BUT...

I think what you're looking for are the "programmatic" access rules you can do in the collections settings:

![image](https://user-images.githubusercontent.com/321047/36449226-78881ce4-168a-11e8-9815-ce6404c4fad8.png)


so what I'm doing here is extending any read query going against the post collection. in that special case I check whether we have a logged in user and if yes I extend the query by adding my additional query condition. 

So, if a user isn't in the admin group he'll always only get items he created.
