### ISSUE TITLE
Deployment Question

### ISSUE THREAD

**Issue by ryanhmaas** [agentejo/cockpit#678]
What's the best way to get a Cockpit instance set up on a deployment server (i.e. DigitalOcean, Vultr, etc)? Documentation hasn't been too friendly, especially to someone who isn't a PHP developer.

Thanks.

**Comment by aheinze** [comment]
Hi,

a generic LAMP stack should work just fine!

**Comment by ryanhmaas** [comment]
Hi @aheinze , thanks for the feedback. Like I said I'm not a PHP developer, so the trouble is more of downloading & installing Cockpit rather than the stack itself. Any pointers there? Not sure if composer can let me install via CLI or whatnot.

**Comment by colinappnovation** [comment]
Might want to consider using Docker for that? https://hub.docker.com/u/cockpit/
