### ISSUE TITLE
Getting multiple regions data at once?

### ISSUE THREAD

**Issue by yarl** [agentejo/cockpit#687]
Is there any possibility to get multiple regions without making request for every single one? It's kinda bummer, when you have to make 10 requests on landing page.

```
GET api/regions/data/foo?token=...
GET /api/regions/data/bar?token=...
GET /api/regions/data/baz?token=...
```

Or the solution is to do one big region per page?

**Comment by aheinze** [comment]
there different ways to do that.

one solution is to create a custom api entry point. to do so create the following file `/config/api/regions-data.php`

we now do a custom query in that file:

```php
<?php

$regions = $this->param('regions');

if (!$regions) {
    return false;
}

$data = [];

foreach (explode(',', $regions) as $name) {
  $data[$name] = cockpit('regions')->region($name);
}

return $data;

```

now you can query `localhost:8080/api/regions-data?token=xxx&regions=foo,bar,baz`

or another possible way is to use the CockpitQL Addon - https://github.com/agentejo/CockpitQL. This way you can request multiple data in one request.

Or you can build your custom module...as you can see, many roads lead to Rome ;-)

**Comment by yarl** [comment]
Perfect, thanks!
