### ISSUE TITLE
collectionlink get more fields?

### ISSUE THREAD

**Issue by cannap** [agentejo/cockpit#689]
hi how can i get more fields atm i just get the _id 
https://gyazo.com/7ff7a16acdc438807ba0a38698e198da

**Comment by Blemming** [comment]
try a deeper populate

**Comment by cannap** [comment]
hi i tried

nothing 

http://localhost/cockpit/api/regions/data/project?token=5b99c9139f5f5aedf3649f386e9dc2&populate=10 same result

**Comment by gryphonmyers** [comment]
> http://localhost/cockpit/api/**regions**/data/project?token=5b99c9139f5f5aedf3649f386e9dc2&populate=10 

?

**Comment by cannap** [comment]
yes?

i have a Region which has collectionlink

because i want to use Region forms for Seo and some other static stuff

**Comment by cannap** [comment]
is there a simple way to fix it now? :D i mean can i modify something i checked the source code but i have no idea where i could say it should also popupate some other stuff :P

**Comment by aheinze** [comment]
should work now using the next branch

**Comment by cannap** [comment]
thank you it is possible to use the next branch with docker?

**Comment by funkvn** [comment]
> it is possible to use the next branch with docker?
@cannap Yes, it is. Just check this branch out and create a new image. If you have npm installed you may use the scripts `docker-init` and `docker`. Take a look in the `package.json` if you want to see what it does.
