### ISSUE TITLE
 Undefined variable: formname

### ISSUE THREAD

**Issue by JulioC** [agentejo/cockpit#694]
When sending a new form entry, I get this PHP Warning:

> Undefined variable: formname in /var/www/cockpit/modules/Forms/bootstrap.php on line 293

From the source code, looks like that variable is indeed being used without a definition.

**Comment by JulioC** [comment]
In fact, that entire line doesn't work. It's not setting the title on form emails

**Comment by aheinze** [comment]
Thanks for reporting!

**Comment by JulioC** [comment]
@aheinze Looks like it's not possible to use `__mailsubject`, from what I can tell the `$this->param` call is not returning the expected value.

I was able to workaround this by calling that function from the RestApi.php file and passing the subject as a variable to `submit`, as it's done in the other cases.
