### ISSUE TITLE
errors on removeRegion()

### ISSUE THREAD

**Issue by pauloamgomes** [agentejo/cockpit#697]
The removeRegion() method makes reference to undefined variable $regions (shoudl be $region) and undefined method dropregion (should be dropCollection):

```
-            $region = $regions["_id"];
+            $region = $region["_id"];

             $this->app->helper("fs")->delete("#storage:regions/{$name}.region.php");
-            $this->app->storage->dropregion("regions/{$region}");
+            $this->app->storage->dropCollection("regions/{$region}");
```

**Comment by pauloamgomes** [comment]
Submitted PR #698 with fix

**Comment by aheinze** [comment]
Fixed with the following commit: https://github.com/agentejo/cockpit/commit/161ec4cb126017497ce22c9d3a627dd5ea0fea01
