### ISSUE TITLE
Feature Request: Key Value for multipleselect and select

### ISSUE THREAD

**Issue by paulstelzer** [agentejo/cockpit#699]
At the moment you can only type in the options as string for multipleselect and select like:

```
{
    "options": "Option 1, Option 2, Option 3"
}
```

Could you add an option to make it key-value like:

```
{
"options": {
"key1": "Option 1",
"key2": "Option 2",
"key3": "Option 3"
}
}
```

So in Cockpit Backend you can check "Option 1", but in json (API output) it is "key1"

**Comment by woutervddn** [comment]
This would simplify things by A LOT!

The current method isn't a generic json format and therefor isn't searchable in vanilla javascript (or php) without building a parser for it.

Though it isn't likely that an option itself would contain a "," we shouldn't assume this.
