### ISSUE TITLE
"entries" always returns only the "_id", when using "fields" to reduce the response. How to?

### ISSUE THREAD

**Issue by teamgroove** [agentejo/cockpit#701]
I try to reduce the key/values in the response with: 'fields'. I tried like this:
```
let filtered = {
    filter: {"title":"Home"},
    fields: ["title", "items"],
    //fieldsFilter: ["title"],
    populate: 3
}
app.$axios.$post('/api/collections/get/Pages/',filtered)
```

But instead of returning only the fields i wanted, the only thing returned in entries is:
```
...
"entries": [
        {
            "_id": "5a31439f1a605doc706042998"
        }
    ],
...
```
I also tried fieldsFilter, no luck.

Try it online: 
https://api.renethiel.info/api/collections/get/Pages/?token=87ed395beee01f27e0715b0e63ab79

Maybe i am holding it wrong, but what i want to achieve is the same when using graphql. Let cockpit just respond with the fields, that i need, not all the metadata. What is the right way to do it?

Side question, there must be a way to get rid of the schema that is sent in 'fields', too.

A graphql side-example with the same dataset:
```
query {
  allPages(skip: 0, limit: 1, populate: 3) {
    title
    items{
	title
   }
  }
}
```

would return only:
```
{
	"data": {
		"allPages": [
			{
				"title": "Home",
				"items": [
					{
						"title": "Projects"
					},
					{
						"title": "About"
					}
				]
			}
		]
	}
}
```
I want to achieve this result with the normal api without graphql by using fields/fieldsFilter. I hope it is possible to do that.

**Comment by aheinze** [comment]
`fields: {'_id': 1 ,'title': 1, 'slug': 1}`
you'll then get only the fields _id, title and slug in the resultset
or `fields: {'title': -1, 'slug':- 1}` get all fields except title and slug
