### ISSUE TITLE
"Saving Failed" when trying to add a new entry in a collection

### ISSUE THREAD

**Issue by aldrakos** [agentejo/cockpit#714]
Hello,
I am getting a "Saving Failed" error pop up when I am adding a new entry in a Collection. The entry seems to get added correctly, but the error pops up.
I think it has something to do with translations: I have an extra language (default and Greek) defined, and on one collection all fields are translatable (localize on) and entries get added ok.
On the other collection some fields are not translatable (a collectionlink to the 1st collection, an image field, a gallery field), but even turning them localized as well keeps showing the error.
Going back to list and then entering and updating the entry, works ok. It's just the creation that has issues.

Is there a way to check exactly what the error is and provide more info?

**Comment by aheinze** [comment]
Could you please try the latest next branch? otherwise try to check the php error log!

**Comment by aldrakos** [comment]
Perfect it now works ok! 
I also tweaked and changed a few things on the collection structure (mainly removed all required toggles as I was trying to add it first and translate later), but for the record the problem seemed to be:

Undefined index: required in modules\Collections\bootstrap.php on line 333
(although just a PHP notice)
