### ISSUE TITLE
Broken link for setup instructions on docker-hub

### ISSUE THREAD

**Issue by elizasj** [agentejo/cockpit#716]
Just underneath **How to Use this Image** there's a broken link to **setup instructions**. [Clicking on it](https://getcockpit.com/docs#!getting_started/setup) redirects to a **404**.

If I'm not mistaken you mean to send people to the Installation page (https://getcockpit.com/documentation/getting-started/installation).

**Comment by aheinze** [comment]
Thank you for the hint. I fixed it but it is an outdated image. `agentejo/cockpit` is the active one.
