### ISSUE TITLE
I cannot find the config file

### ISSUE THREAD

**Issue by rickerd** [agentejo/cockpit#717]
In the documentation it says about a config file in yaml format but i cannot find it anywhere in the filesystem.
https://getcockpit.com/documentation/reference/configuration

Where to add the configfile and what permissions needed for the file.

Sorry.. but i cannot find it anywhere.

**Comment by paulstelzer** [comment]
I do not know if this file exist after installation, but you can edit this in Cockpit Admin panel:

http://yourwebsitetocockpit.com/settings/edit ("Settings" -> "Settings")

Afterwards the config.yaml is in your FTP under /config/config.yaml

**Comment by rickerd** [comment]
Yes that's the folder and file i needed.
I couldn't find that it have to be in the config folder.
It works now! Thanks.
