### ISSUE TITLE
Reordering of entities as non-admin fails

### ISSUE THREAD

**Issue by mkalus** [agentejo/cockpit#719]
When I reorder entries in the list as admin for a sortable collection, a POST request is triggered to //SERVER/cockpit/call/collections/save containing the updated order of entities.

Now I have a user belonging to a non-admin group. The setting of the group is

```php
    group:
        $admin: false
        $vars:
            finder.path: /storage/uploads/xyz
        cockpit:
            backend: true
            finder: false
```

The group also has create, edit, view, delete entries ACLs but not "Edit Collection".

As a non admin user, I see the reorder icons and the remark when I call the list view. I can also drag and drop entities, but the call above will return a 404.

I guess this is an ACL issue. Where could I change these?

**Comment by mkalus** [comment]
As an additional note: After some experiments, I have found out that `modules/Cockpit/webhooks.php` seems to block the access somehow or return 404.

I am not quite sure which file the CURL in this script calls, but it seems to block access to a non admin user.

**Comment by mkalus** [comment]
Ok, I debugged it down to the source. It was indeed an acl check in `modules/Cockpit/Controller/Base.php`, method `call`.

Calling reorder will check module 'collections', asl 'manage'.

I could get it to work after adding this to groups:

```yaml
groups:
    MYGROUPNAME:
        collections:
            manage: true
```

Is this documented somewhere? If not it would be cool to write it down somewhere. I would be willing to do this/support you if i knew where. Just give me a hint!

**Comment by aheinze** [comment]
@mkalus you can find the docs here: https://github.com/agentejo/cockpit-docs . 

Feel invited to contribute. Thanks!

**Comment by mkalus** [comment]
Ok, thanks! You can close the issue then 😄
