### ISSUE TITLE
IIS fails to save the collection / region

### ISSUE THREAD

**Issue by Brandoning** [agentejo/cockpit#726]
Hey,

I know this is not made to support Microsoft IIS or anything along those lines, however we made the application for a client without knowing exactly their hosting setup as it wasn't possible at the time.

We've managed to overcome a few hurdles including some htaccess change and a permission issue, and I believe everything is working minus being able to save content in the CMS (I can save users, just not collection or region).

It just says "Save failed" on these types of content. User updated comes up fine on editing users...

The server administrator has told me this error is firing, I am no IIS expert and I know the same files in Apache work. Any assistance with what going be going wrong here? 

Possibly there's no post data or some similar issue?...

```
[06-Apr-2018 15:02:35 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Collections\Controller\Admin::save_entry(), 0 passed and exactly 1 expected in cockpit\modules\Collections\Controller\Admin.php:189
Stack trace:
#0 [internal function]: Collections\Controller\Admin->save_entry()
#1 cockpit\lib\Lime\App.php(1074): call_user_func_array(Array, Array)
#2 cockpit\lib\Lime\App.php(846): Lime\App->invoke('Collections\\Con...', 'save_entry', Array)
#3 [internal function]: LimeExtra\App->Lime\{closure}(Array)
#4 cockpit\lib\Lime\App.php(1051): call_user_func(Object(Closure), Array)
#5 cockpit\lib\Lime\App.php(998): Lime\App->render_route('/collections/*', Array)
#6 cockpit\lib\Li in cockpit\modules\Collections\Controller\Admin.php on line 189
```

Thanks,
Brandon

**Comment by aheinze** [comment]
sorry to hear that. unfortunately I can't test it on an IIS machine. but it looks like a routing issue 🤔

**Comment by Brandoning** [comment]
Thanks, closed as the issue is resolved.

FYI, this could actually support IIS from the outset very easily given some htaccess trickery (supply web.config or whatever the equivalent is).

95% of the functionality seemed to work.

Keep up the good work 😄

**Comment by aheinze** [comment]
would you like to share your web.config?

**Comment by Brandoning** [comment]
It will probably need a few things adding, but this is a good start for people trying to get this on IIS:

**web.config for root directory**
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <staticContent> 
      <mimeMap fileExtension=".css" mimeType="text/css; charset=UTF-8" /> 
      <mimeMap fileExtension="woff" mimeType="application/font-woff" /> 
      <mimeMap fileExtension="woff2" mimeType="application/font-woff" /> 
      <mimeMap fileExtension=".js" mimeType="application/x-javascript" />
      <mimeMap fileExtension=".handlebars" mimeType="text/x-handlebars-template" /> 
      <mimeMap fileExtension=".tag" mimeType="text/x-javascript" /> 
    </staticContent>
  <rewrite>
  <rules>
    <rule name="Imported Rule 1" stopProcessing="true">
      <match url="^.*/?\.git+" ignoreCase="false" />
      <action type="CustomResponse" statusCode="403" statusReason="Forbidden" statusDescription="Forbidden" />
    </rule>
    <rule name="Imported Rule 2" stopProcessing="true">
      <match url=".*" ignoreCase="false" />
      <conditions>
        <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" negate="true" />
        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
      </conditions>
      <action type="Rewrite" url="index.php" />
    </rule>
  </rules>
</rewrite>
</system.webServer>
</configuration>
```

Not 100% sure of the architecture or back-end config since it's a remotely managed server - I know it's IIS with PHP 7.0 GD, ZIP and the mongo extension installed (due to load balancing sqllite not possible). Everything is working fine that I've tried up to now.

**Comment by webcliq** [comment]
Can you confirm that you have had no problems displaying and saving records generally with this Web.Config?

**Comment by aheinze** [comment]
@Brandoning great to hear, thanks for sharing 👍

**Comment by jpgollnitz** [comment]
Updated web.config for Azure Web App

``<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
     <staticContent>
      <mimeMap fileExtension=".css" mimeType="text/css; charset=UTF-8" />
      <mimeMap fileExtension="woff" mimeType="application/font-woff" />
      <mimeMap fileExtension="woff2" mimeType="application/font-woff" /> 
      <mimeMap fileExtension=".js" mimeType="application/x-javascript" />
      <mimeMap fileExtension=".handlebars" mimeType="text/x-handlebars-template" />
      <mimeMap fileExtension=".tag" mimeType="text/x-javascript" />
    </staticContent>
  <rewrite>
  <rules>
    <rule name="Imported Rule 1" stopProcessing="true">
      <match url="^.*/?\.git+" ignoreCase="false" />
      <action type="CustomResponse" statusCode="403" statusReason="Forbidden" statusDescription="Forbidden" />
    </rule>
    <rule name="Imported Rule 2" stopProcessing="true">
      <match url=".*" ignoreCase="false" />
      <conditions>
        <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" negate="true" />
        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
      </conditions>
      <action type="Rewrite" url="index.php" />
    </rule>
  </rules>
</rewrite>
</system.webServer>
</configuration> ``

**Comment by Tin-Joy59** [comment]
@Brandoning I know this is old but do you remember how you fixed the saving issue?

**Comment by Brandoning** [comment]
> @Brandoning I know this is old but do you remember how you fixed the saving issue?

No I don't :( I think it would be possible easily if you find someone who knows IIS but I'm not an IIS expert and didn't have access to the server to finish the job

**Comment by ronspierings** [comment]
Dear @Brandoning .
Since your reply serves as a source of knowledge (ie copy/paste) for many (including myself), could you please add the mimetypes (as stated below) to your post? This would be of great help for any newcomer, who is struggling with the IIS setup.

`     <staticContent>
      <mimeMap fileExtension=".css" mimeType="text/css; charset=UTF-8" />
      <mimeMap fileExtension="woff" mimeType="application/font-woff" />
      <mimeMap fileExtension="woff2" mimeType="application/font-woff" /> 
      <mimeMap fileExtension=".js" mimeType="application/x-javascript" />
      <mimeMap fileExtension=".handlebars" mimeType="text/x-handlebars-template" />
      <mimeMap fileExtension=".tag" mimeType="text/x-javascript" />
    </staticContent>` 

Thanks!

**Comment by Brandoning** [comment]
> Dear @Brandoning . Since your reply serves as a source of knowledge (ie copy/paste) for many (including myself), could you please add the mimetypes (as stated below) to your post? This would be of great help for any newcomer, who is struggling with the IIS setup.
> 
> ` <staticContent> <mimeMap fileExtension=".css" mimeType="text/css; charset=UTF-8" /> <mimeMap fileExtension="woff" mimeType="application/font-woff" /> <mimeMap fileExtension="woff2" mimeType="application/font-woff" /> <mimeMap fileExtension=".js" mimeType="application/x-javascript" /> <mimeMap fileExtension=".handlebars" mimeType="text/x-handlebars-template" /> <mimeMap fileExtension=".tag" mimeType="text/x-javascript" /> </staticContent>`
> 
> Thanks!

I have updated my previous post, thanks for that!
