### ISSUE TITLE
$in or $nin not working in SQLite

### ISSUE THREAD

**Issue by 6feferonka9** [agentejo/cockpit#727]
Hello, $in nor $nin are not working for me. 

Im using SQLite.

No error message, server just returns plain object.

```
      filter: {
        'cena-vozidla': {
          $gte: vehiclePriceStart,
          $lte: vehiclePriceEnd
        },
        'prevodovka': {
          $in: ['manuálna']
        }
      }
```

If I dont use the 'prevodovka' filter, server returns objects with that property and it is an Array and also it does contain the value 'manuálna'.

$nin returns 406;

**Comment by aheinze** [comment]
Thanks for reporting. I'll look into that
