### ISSUE TITLE
Importing repeater fields

### ISSUE THREAD

**Issue by Brandoning** [agentejo/cockpit#730]
Importing a repeater field seems to be impossible by default unless I'm doing something wrong...

![screen shot 2018-04-12 at 12 17 39](https://user-images.githubusercontent.com/5629295/38674223-9ad27a68-3e4b-11e8-9ae8-a08e1c72d18a.png)

Facts is a repeater field in the CMS and is displayed as one mappable field in the import screen. However, when exporting it splits the field meta out in to all of these different CSV columns.

Is this an oversight maybe or does it just need an interface creating for it?

**Comment by gryphonmyers** [comment]
Yes I believe I wrote a filter for this some time ago but never merged it in.

**Comment by Brandoning** [comment]
Issue closed as we discovered it's not part of the original specification
