### ISSUE TITLE
Fields REST API parameter seems broken recently

### ISSUE THREAD

**Issue by gryphonmyers** [agentejo/cockpit#732]
The fields parameter is very useful for cutting down on bloat in HTTP requests, but I just realized it isn't working as expected on my dev server (which has more recent commits applied). 

`
/cockpit/api/collections/get/myCollection?token=xxx&simple=true&limit=10&fields[0]=URL&fields[1]=region
`
```javascript
//RESPONSE
[{"_id":"581b9aa3d8aa883f288b45d7"}, 
{"_id":"581b9aa3d8aa883f288b45d9"},
{"_id":"581b9aa6d8aa88cf278b45ae"}, 
{"_id":"581b9aa6d8aa88cf278b45af"},
{"_id":"581b9aa6d8aa88cf278b45b0"},
{"_id":"581b9aa8d8aa88d3278b45d7"},
{"_id":"581b9aa8d8aa88d3278b45d8"},
{"_id":"581b9aa8d8aa88d3278b45d9"},
{"_id":"581b9aa8d8aa88d3278b45da"},
{"_id":"581b9aa8d8aa88d3278b45db"}]
```
You can see when I specify fields, it empties the response objects to only contain IDs. The same request to my prod server includes the expected fields in the response (exact same schema and data set). 

Assuming it's not an environmental issue on my end (entirely possible, I did just update my MongoDB driver) can you think of anything in these commits that might have caused this?

![screen shot 2018-04-12 at 3 07 38 pm](https://user-images.githubusercontent.com/5785304/38706832-89f74c4c-3e63-11e8-8418-584b5799f771.png)

**Comment by aheinze** [comment]
Please have look here: https://docs.mongodb.com/manual/tutorial/project-fields-from-query-results/

so, to solve your issue change your query to:

`
/cockpit/api/collections/get/myCollection?token=xxx&simple=true&limit=10&fields[URL]=1&fields[region]=1
`

**Comment by gryphonmyers** [comment]
Ohh! I did not realize this was builtin Mongo functionality. I guess I had just gotten used to doing it a legacy way without realizing it. Thanks!
