### ISSUE TITLE
Accessing region via PHP

### ISSUE THREAD

**Issue by muoto** [agentejo/cockpit#733]
trying to access data in a region via php like this:

```
$settings = cockpit('regions:get_region', 'settings');
print_r ($settings);
```

but result is always empty? Any ideas?

**Comment by aheinze** [comment]
If you just want to use the data, I would recommend to use the singletons module

**Comment by muoto** [comment]
Thanks! What is the PHP call/method to get that?
Also any way to convert Region ->Singleton easily

[http://clients.metablocks.com/static/meta.jpg]<http://www.metablocks.com/>

Oliver Muoto
Metablocks, Inc.
oliver@metablocks.com<mailto:oliver@metablocks.com>
888-503-7182x90 / 615-435-3819 direct / 650-787-5567 mobile
