### ISSUE TITLE
/install redirects me to /auth/login on MAMP

### ISSUE THREAD

**Issue by ThiagoMiranda** [agentejo/cockpit#737]
Hi..
I'm trying to get Cockpit work in my MacOS. I've installed MAMP and downloaded the Cockpit.zip. So I've pointed my apache server ( Mamp uses PHP 7.1.12 ) to the directory of my cockpit but when I type `localhost/install` in my browser I am redirected to the `auth/login` page which I don't have the username and password. Does anyone had the same issue?
How can I solve it?

Ps: Followed the bolt instructions and my mod_rewrite is working nicely: https://docs.bolt.cm/3.4/howto/making-sure-htaccess-works

**Comment by mpartipilo** [comment]
Make sure that the storage folder, and all of its sub-folders have write-access permission.

**Comment by ThiagoMiranda** [comment]
It does!
But it seems that the admin/admin user is working so I´ll stick to that.
Thanks
