### ISSUE TITLE
Problem fetching user in PHP

### ISSUE THREAD

**Issue by muoto** [agentejo/cockpit#739]
Trying to get the current user in php using:

`$u = cockpit("cockpit")->getUser();`

But not getting any results. Ideas?

**Comment by aheinze** [comment]
can give more details on the context?

**Comment by muoto** [comment]
i am using it from a php page (outside cockpit). So this works within cockpit but i am trying to get the user from a page outside using:

```
require_once ("cockpit/bootstrap.php");
$u = cockpit("cockpit")->getUser();
print_r ($u);
```

**Comment by muoto** [comment]
As context i am trying to use cockpit for general user authentication for my site and this is the last step needed.

**Comment by aheinze** [comment]
Seems to be a session problem. Please try:

```php
session_name(md5(__DIR__).'/cockpit');
session_start();

require_once ("cockpit/bootstrap.php");
$u = cockpit("cockpit")->getUser();
print_r ($u);
```

**Comment by muoto** [comment]
Very helpful, thanks! I love the versatility of cockpit! I can even use it for user management ;)
