### ISSUE TITLE
Calculate Fieldtype

### ISSUE THREAD

**Issue by thinkink** [agentejo/cockpit#741]
what is the best way for calculate diferent values from fields in a collection and punt into result field.

For example for multiply quantity and price in a collection row.

It's posible to make a new Fieldtype called calculate and define som rules in options, to choose diferent fields and apply aritmethic rules.

**Comment by mpartipilo** [comment]
I think this doesn't exist yet, but could be implemented.

Maybe specifying a function name in a Calculate field by calling a specific php function that takes the form data in a file in the config directory. Something like functions.php.

I might even try to make this myself.

**Comment by aheinze** [comment]
@mpartipilo no. in that case it won't be available in the admin backend, but you get it in your query result-set. you can also use the field to query, sort etc via the api.

**Comment by thinkink** [comment]
@aheinze i try your code but nothing happens.

**Comment by thinkink** [comment]
I create a collection named calculation
and create 3 fields 

- price

- quantity

- calculated



this is my config/bootstrap.php
 

```
<?php 
$collectionName = "calculation";

$app->on('collections.save.before.{$collectionName}', function($name, $entry, $isUpdate) {
   
   if (isset($entry['price'], $entry['quantity'])) {
        $entry['calculated'] =  $entry['price'] * $entry['quantity'];
   }    
});

````

**Comment by aheinze** [comment]
```
$app->on('collections.save.before.calculation', function($name, &$entry, $isUpdate) {
   
   if (isset($entry['price'], $entry['quantity'])) {
        $fichero =  __DIR__ . '/debugcalculator.txt';
		 
		$entry['calculated'] =  $entry['price'] * $entry['quantity'];
		file_put_contents($fichero, $entry['calculated']);
   }    
});
```

`&$entry` does the trick
