### ISSUE TITLE
When using "Text" component content is not saved

### ISSUE THREAD

**Issue by sebastianks** [agentejo/cockpit#744]
Hello there

I'm trying to use the text widget for a basic text page, and pretty often when trying to change the text it's not saving the changes. The changes could be new text, making text bold or another formatting. Also sometimes when adding new components it's not saving the whole component.

**Comment by aheinze** [comment]
what is a text widget? 🤔

**Comment by sebastianks** [comment]
Oh, component it might be - not widget.

**Comment by aheinze** [comment]
🤔can't verify the issue. which branch do you use?

**Comment by sebastianks** [comment]
That seems weird. It’s happening all the time for me. It’s the Next branch.

**Comment by aheinze** [comment]
can you send me your cockpit instance?

**Comment by sebastianks** [comment]
How do you need, sorry?

**Comment by aheinze** [comment]
just zip the cockpit folder and email it

**Comment by sebastianks** [comment]
Meant how much* sorry. On the phone... I’ll do that.

**Comment by sebastianks** [comment]
@aheinze I've sent you an e-mail.

**Comment by aheinze** [comment]
It seems that you're using version 0.5.1 could you please try to update to the latest version or even latest next branch?
