### ISSUE TITLE
REST API and unpublished entries

### ISSUE THREAD

**Issue by kamarkiewicz** [agentejo/cockpit#745]
I'm fiddling with `Posts` collection generated from the default template. Is there a possibility not to show entries on call `/api/collections/get/posts` where `published: false`? I would like to hide those entries from an API user.

**Comment by Blemming** [comment]
You will have to send a POST (http verb) request with this in the body:
```
{
"filter":{
   	"published":true
   }
}
```

**Comment by Blemming** [comment]
What you want would require graphQL, @aheinze has made a addon for it , but I believe it is very experimental and your front end would have to change to accept the graphql responses

**Comment by kamarkiewicz** [comment]
If so, what would stop this front-end user from using `collection(name:"posts", filter:{published:false})`? It's not it. I'm thinking of writing this filtering logic on `/cockpit/collections/collection/posts` view on `Permissions` tab in the `READ` block or somewhere, just wanted to know if it would work or not...

**Comment by aheinze** [comment]
@kamarkiewicz  you can achieve this in many ways...

## 1. Custom api entry point

Create a file in `/config/api` named `posts.php` with the following content:

```php
<?php

return cockpit('collections')->find('posts', [
   'filter'=>array_merge($this->param('filter', []), ['published'=>true])
];
```
now you can query `/api/posts` and you'll always only get published posts.


## 2. Bind on `collections.find.before`

add the following snippet to `/config/bootstrap.php`:

```php
<?php

$app->on('collections.find.before.posts', function($name, &$options) {

    if (COCKPIT_API_REQUEST) {
        $options['filter']['published'] = true;
    }
});
```

**Comment by kamarkiewicz** [comment]
@aheinze That is exactly what I was looking for! Thank you! :smile:
