### ISSUE TITLE
More detailed rules on api keys

### ISSUE THREAD

**Issue by beyer-johannes** [agentejo/cockpit#746]
If i have posts with a boolean attribute **public**, I only want to show public marked entries.

Yes I can use the filter in my request, but the core problem is, everybody has access to my 
private entries with my api key.

For example, to use the rule:
/api/collections/get/posts?public=true

Thanks for help or ideas :)

**Comment by aheinze** [comment]
please take look here: https://github.com/agentejo/cockpit/issues/745

**Comment by beyer-johannes** [comment]
@aheinze thanks for the fast response.

`/api/collections/get/posts?filter[published]=true`

is exactly what i need but it does not work?
Does it mean, my request needs the query parameter "filter[public]=true" to be valid?

**Comment by aheinze** [comment]
I meant this one: https://github.com/agentejo/cockpit/issues/745#issuecomment-383937653

**Comment by beyer-johannes** [comment]
Okay, thanks :)
