### ISSUE TITLE
Upload PDF to assets -- how to get link?

### ISSUE THREAD

**Issue by cschweda** [agentejo/cockpit#747]
I'm able to upload a PDF to my assets collection, but in my markdown preview, I only see an 'image' icon (that will embed an image link).

How do I embed the link to the pdf (stored in my assets collection)?

Currently, the only way to do this is open my 'assets' in another browser tab, click on the PDF file in the assets list, get the full URL -- and then go back to my markdown editor in the other tab, paste in the link.

Is there an easier way? Can I do this directly from the markdown editor (much like the 'image' link icon)?

**Comment by aheinze** [comment]
insert assets in markdown fields was added in this commit: https://github.com/agentejo/cockpit/commit/3f46fc72bd8a77b383280e2b7ff8eb5ca8b2af48  

please update to the latest next branch codebase

**Comment by cschweda** [comment]
Awesome. Thank you!

**Comment by cschweda** [comment]
I still only see the 'image' icon in the markdown editor.

If I click on it, it opens the assets as a modal -- but if click on a PDF, it doesn't give me the highlight open to select it.

Selecting an image works fine.

I'm guessing I'm doing something wrong.

Here's what I did:

```
$ git clone https://github.com/agentejo/cockpit.git
$ git checkout git checkout 3f46fc72bd8a77b383280e2b7ff8eb5ca8b2af48
```
Status:

`HEAD is now at 3f46fc72... Enhance html/markdown field to reference assets #747`

**Comment by aheinze** [comment]
Better checkout next so you can just pull always the latest changes

`git checkout next`

then don't forget to clean your browser cache

**Comment by cschweda** [comment]
Bingo!

'Empty Cache and Hard Reload' did the trick.

Many thanks!
