### ISSUE TITLE
Question: How do I connect cockpit to a database?

### ISSUE THREAD

**Issue by samprity** [agentejo/cockpit#756]
I am trying to migrate old adobe cq pages to cockpit. I couldnt find any documentation on how to connect to a database using the cockpit docker image

**Comment by porjolovsky** [comment]
[Here's what little the docs say about configuring a DB.](https://getcockpit.com/documentation/reference/configuration)

This configuration settings should be in your config/config.yaml file, which can be edited by the main administrator from cockpit itself.

I believe it currently supports only mongo or (the default) sqlite dbs.

**Comment by samprity** [comment]
Thanks!
