### ISSUE TITLE
[Question] Multi tenant support

### ISSUE THREAD

**Issue by samprity** [agentejo/cockpit#759]
Does cockpit support multi tenants? I can only login as admin. Does cockpit support different users with different roles and permissions

**Comment by mares29** [comment]
Sure. You can manage other user accounts on /**accounts** page.
Roles with permissions are defined in the configuration file ([doc](https://getcockpit.com/documentation/reference/configuration)) or you can try to use this [plugin](https://github.com/serjoscha87/cockpit_GROUPS).

**Comment by internetstyle** [comment]
Is it possible with one install to manage multiple apps / sites? Is it possible for each app to have its separate database? Or would his one single db separate on roles/groups?
