### ISSUE TITLE
Singleton link

### ISSUE THREAD

**Issue by gryphonmyers** [agentejo/cockpit#761]
I like the introduction of singletons - it definitely fills a hole. It would be nice to have a field for referencing singletons like you can with a collection link, though I understand why this might be more complicated. Is it planned?

**Comment by stuartcusackie** [comment]
I have multiple Laravel projects that would benefit from being able to link singletons to each other or to a collection item.

A singletonLink field would really open up the possibilities of cockpit as a cms.

**Comment by pauloamgomes** [comment]
That would be interesting for sure, for now, and since I have the same need I created a simple singleton select link that can permit to link to a singleton and have the singleton data in the field on api requests - https://github.com/pauloamgomes/CockpitCMS-Helpers#singleton-select-field
