### ISSUE TITLE
Upload asset via API

### ISSUE THREAD

**Issue by paulstelzer** [agentejo/cockpit#763]
Hello, I saw in Commit [b63202e7100b09ac03b0a0d10f645cc78131c311]( https://github.com/agentejo/cockpit/commit/b63202e7100b09ac03b0a0d10f645cc78131c311)  that the rest api now contains a addAssets() function.

Is there a documentation available how to use it?

**Comment by johannesvg** [comment]
> Hello, I saw in Commit [b63202e7100b09ac03b0a0d10f645cc78131c311](https://github.com/agentejo/cockpit/commit/b63202e7100b09ac03b0a0d10f645cc78131c311) that the rest api now contains a addAssets() function.
> 
> Is there a documentation available how to use it?

This works for me. Just make sure that the API url receives a post request containing the files to upload. the block brackets are apparently required in order to force the php $_FILES variable in an array format, which is needed for the current implementation of the code.

```
    <form method="POST" id="formid" enctype="multipart/form-data">
        <input type="file" name="files[]">
        <input type="submit" id="test" value="ok">
    </form>

    <script>
    
    $( document ).ready(function() {

        $( '#formpid' )
        .submit( function( e ) {
            $.ajax( {
            url: 'xxx/api/cockpit/addAssets?token=xxx',
            type: 'POST',
            data: new FormData( this ),
            processData: false,
            contentType: false
            } );
            e.preventDefault();
        } );
    
    });

    </script>
```

**Comment by iryanrachman** [comment]
but this is not connected to any collection right ?

**Comment by iryanrachman** [comment]
is there a problem with my code ? 

 ```submit(){
        const data = new FormData() 
        data.append('file[0]', this.state.selectedFile)
        console.warn(this.state.selectedFile);
        // let url = `${process.env.GATSBY_DIRECTUS_API_URL}/gemaclc/files?access_token=${process.env.GATSBY_DIRECTUS_TOKEN}`;
        
        let url = `${process.env.GATSBY_COCKPIT_API_URL}/api/cockpit/addAssets?token=${process.env.GATSBY_COCKPIT_TOKEN}`;

        fetch(url, { 
            method: 'post',
            data: 
                     data,
                 
            headers:{ 'Content-Type': 'application/json'} })
            .then(res => res.json())
            .catch(error => console.error('Error:', error))
            .then(res => {console.log('Success:', res)})
            this.setState({
                        display1:false
                    })
        

    }```

**Comment by abernh** [comment]
>        data.append('file[0]', this.state.selectedFile)

By default the `addAssets` endpoint only picks up on files in the parameter named `files[]` (see also @johannesvg [comment below on the mandatory brackets](https://github.com/agentejo/cockpit/issues/763#issuecomment-434509812) )
So this should be

```
       data.append('files[]', this.state.selectedFile)
```
even though it is only a single file.
