### ISSUE TITLE
disable gravatar by default (privacy)

### ISSUE THREAD

**Issue by raffaelj** [agentejo/cockpit#771]
If I want to get tracked, I could use a hosted solution. And if I might cite the cockpit startpage  ;-)

>Self-hosted - Keep complete control. Your data is and will be always yours.

I still have a solution, but I never worked with APIs or riot or npm before. So I wait with my pull request until someone else will review the code or give some hints for a cleaner logic. But I learned a lot the last days - searching for docs, reading the code, using Guzzle, Postman, riot etc. and I can't wait to restructure all my data.

My [commit][2] in my [repo][1] adds a config variable `gravatar` with default to `false` to `bootstrap.php` and it adds some logic to a few views and .tag-files to take care of the configuration.

It also contains a few `console.log`s for debugging.

Two commits later I removed a lock file and added it to `.gitignore`.

And thank you for this software.

[1]: https://github.com/raffaelj/cockpit
[2]: https://github.com/raffaelj/cockpit/commit/b4dd7557d615d852f006956a1fcdd7e10e06ed0c

**Comment by aheinze** [comment]
You're totally right, I already planed to remove gravatar for the next release

**Comment by raffaelj** [comment]
Thank you very much. That was fast and removing sounds even better than disabling. Next time I'll ask you before I write a workaround. But otherwise - now I have a basic understanding of the templating system.
