### ISSUE TITLE
set inside repeater with options or/and collectionlinks doesn't work

### ISSUE THREAD

**Issue by raffaelj** [agentejo/cockpit#773]
I tried a workaround to have labels for collectionlinks, like I explained in #772 and I discovered another bug. I wanted to have a set with a select and a collectionlink field. The set is in a repeater.

The code in the repeater field:

```json
{
  "fields": [
    {
      "type": "set",
      "label": "Relation",
      "options": {
        "fields": [
          {
            "type": "select",
            "label": "action",
            "options": {
              "options": "will blow away, could possibly eat, will be destroyed by"
            }
          },
          {
            "type": "collectionlink",
            "label": "object",
            "options": {
              "link": "objects",
              "display": "title",
              "multiple": false,
              "limit": false
            }
          }
        ]
      }
    }
  ]
}
```

If I select an option and afterwards I link a collection, the select option gets lost. The other way around it's the same.

For a better understanding I captured a gif: 

![cockpit_repeater_multiple_issue3](https://user-images.githubusercontent.com/13042193/40802396-c4626d16-6515-11e8-9125-d8aa65985f2d.gif)

I tried it with the next branch Version 0.5.5 from [3 days ago][1] as a fresh installation and with MultipleCollectionLink plugin and I'm not sure anymore, if I tested other versions, too.

System 1:
XAMPP for Windows 7.2.5, Win7-64bit

System 2:
Uberspace with CentOS 7, PHP7, I don't know the exact specifications, but I could search for it if it's relevant.

Browsers:
Firefox ESR with script blockers, new FF without plugins, Opera

The issue appears everywhere.

[1]: https://github.com/agentejo/cockpit/commit/a19e3c3d27bb43c1c09fbc1a24aebe4c9ed443a6

**Comment by Kemsan** [comment]
Use "name" key for each set field

**Comment by raffaelj** [comment]
Now it works. Thank you.
