### ISSUE TITLE
assetsmanager upload error

### ISSUE THREAD

**Issue by AldrinSalazar** [agentejo/cockpit#777]
I have the cockpit version currently in master.

**Actions:**
- Go to the assets manager
- Click upload
- Select image

**Expected:**
The image should have been uploaded to the server, and listed in the assets screen

**Happening**
The upload progress bar goes to 100%, then there is the error message "Something went wrong."

Network tab shows a POST to the **/assetsmanager/upload** URL with a **500** status and no meaningfull information nor stacktrace
- - - -
A check to the php error_log reveals this:

`[08-Jun-2018 22:18:50 UTC] PHP Fatal error:  Call to undefined function Cockpit\Controller\finfo_open() in /home/vivoarge/public_html/demos/triviatur/admin/modules/Cockpit/Controller/Assets.php on line 50`

**Comment by gryphonmyers** [comment]
What version of PHP are you using?

**Comment by AldrinSalazar** [comment]
PHP version 5.6

**Comment by gryphonmyers** [comment]
Not sure if it would be the cause of this, but I know PHP 7 is basically required now. I’d try upgrading if possible and see if that fixes it.

**Comment by AldrinSalazar** [comment]
My solution:
It seems like the fileinfo PHP extension is not enabled in my production eviroment, since i wasn't able to activate it i changed the files in the core that get the file mime type and implemented a more "generic" approach using the system shell.

**Comment by nilsborg** [comment]
Hey guys,

I have exactly the same issue but without any errors in either nginx or php fpm logs :/

I have version: `0.8.2` and this would be my php info:

![screenshot 2018-10-12 at 10 50 15](https://user-images.githubusercontent.com/1119139/46858918-a8b28000-ce0c-11e8-8590-a8145e2fa225.png)

Any ideas?

**Comment by nilsborg** [comment]
Also one more thing: I CAN upload a file in the finder … but if I do that it doenst show up in the Assets panel.
I have a Cockpit installation on the same machine with version `0.7.0` which uploads assets just fine.

**Comment by benedictjohannes** [comment]
In some distributions, the `fileinfo` PHP extension is enabled/installed by default when installing PHP. This should be documented, probably in `README.md` to list `fileinfo` as a requirement.
