### ISSUE TITLE
REST API filter query does not match text field value when it can be parsed as int

### ISSUE THREAD

**Issue by gryphonmyers** [agentejo/cockpit#779]
Repro steps:

1. Set up collection with text field
2. Add an entry to this collection, give the field a value containing all numbers (e.g. "123123")
3. Attempt to query this value on the REST API using query string (e.g.`/cockpit/api/collections/get/{myCollection}?token={myToken}&filter[{myField}]=123123`)
4. Note that no results are displayed.
5. Make another entry in the collection with at least one non-number char (e.g. "123123H")
6. Try the same query with new value and note that the latter entry is displayed.

Expected behavior:

All text field values should be queryable via GET request from the API. This is probably due to the values being interpreted as numbers and stored in the database as such, then being queried with string values (or perhaps vice versa). Query strings should be interpreted as whatever type text field values are stored as internally.

**Comment by aheinze** [comment]
This seems to be true if you're using mongodb as data source.  Should be fixed now

**Comment by gryphonmyers** [comment]
Leave it to me to find all the Mongo bugs 😁
