### ISSUE TITLE
Filter is not working

### ISSUE THREAD

**Issue by ranjit-redekar** [agentejo/cockpit#780]
I need to get the single record from API and I set _id into filter but it's load the all the records of collection. So, how can get the single record of  specified key.  Also tried rating key but still it's not working.  

`filter: {_id: '5b235cf10ab95doc886865679'}`
Also tried `filter: {"rating":{'$eq': '4'}}`

**Comment by ranjit-redekar** [comment]
Please, any update on this.?

**Comment by paulo-santos** [comment]
I had the same problem while filtering using the post method.

Meanwhile, I used the filter in query parameters:
`/api/collections/get/{collection}?token=&filter[_id]=xxxxxxxx`

**Comment by aheinze** [comment]
@ranjit-redekar how do you query the api?

**Comment by ranjit-redekar** [comment]
it's my bad I did something wrong.
thanks @paulo-santos  its working.
