### ISSUE TITLE
How to create "pages"

### ISSUE THREAD

**Issue by omzy83** [agentejo/cockpit#783]
I am looking to use Cockpit as a CMS to manage a simple brochure site. There are some standard pages on this site, e.g. Home, About, Services, Contact.

Each of these pages have different types of content, and only a few shared elements e.g. a banner image. What is the best way to set up Cockpit to create pages?

I was thinking of creating a separate "collection" for each page but that doesn't really make sense. For example you would not have more than one home page.

**Comment by DigitalGoldfish** [comment]
I am using the Regions feature to deal with this type of request. I usually have the following regions
 - One "Common" region  (Headertexts, Footertexts, Contact information, ...)
 - "Homepage" regions => represents all content on the homepage
 - "About company" region => represents all content on the about company page
 - ...
