### ISSUE TITLE
Do you have plan to include others authentication providers?

### ISSUE THREAD

**Issue by pascencio** [agentejo/cockpit#785]
Hi,
I'm looking for an headless CMS and get your project. After some minutes playing with the docker image and I think it's cool tool. But in some cases I will need to integrate my CMS with other systems using OAuth2, LDAP, etc.

How can I achieve it with this tool?

**Comment by aheinze** [comment]
there is a Auth0 addon that might help:

https://github.com/agentejo/Auth0

**Comment by lgkonline** [comment]
My company uses Active Directory, so it would be nice if users could sign in using LDAP. As far as I can see, there's currently no way to do this without using Auth0, right? 🤔

**Comment by aheinze** [comment]
there is a WIP SAML addon https://github.com/agentejo/SAML.
