### ISSUE TITLE
order in api request for collections

### ISSUE THREAD

**Issue by kevinfoerster** [agentejo/cockpit#788]
i would like use the `custom sortable entries option` and i wonder why the order is not correctly displayed within the json and rather displayed as an internal key `_o`. an array itself is an ordered list and therefor i think it would make sense to apply that order when printing the json

in my case i use cockpit with gatsby-plugin-cockpit and the properties starting with an underscore are simply not exposed to graphql

**Comment by aheinze** [comment]
should be fixed now with this commit: https://github.com/agentejo/cockpit/commit/42fe40e5e3d47a2c3e2944012c256f12de43e314
