### ISSUE TITLE
MogoDB query with special fiter returns 406

### ISSUE THREAD

**Issue by lejoe** [agentejo/cockpit#803]
I have collection with an object.
I do a query to find objects with a special key:

```
{
    "filter": {
        "accounts": {
            "$has": "aSearchValue"
        }
    },
    "token": "…"
}
```

With SQLite as DB the call works.
With mongoDB it returns a 406 error code with this body:
```
{"error":true,"message":"Oooops, something went wrong."}
```

Let me know if you need more info to reproduce

**Comment by aheinze** [comment]
This is a different implementation between MonongoDB and MongoLite.

MongoDB doesn't have a `$has` operator. Instead you just do `"accounts":"aSearchValue"` this will do also a ✌️does accounts contains "aSearchValue"✌️check if the accounts field is an array.

Long story short, I adjusted the MongoLite Query builder: https://github.com/agentejo/cockpit/commit/cda8813968fe7ed26cfbcdb47185a25733681793

so the following query should work now with mongodb and sqlite as datasource:

```
{
    "filter": {
        "accounts": "aSearchValue"
    },
    "token": "…"
}
```

**Comment by lejoe** [comment]
That solved the issue!
Thanks a lot @aheinze for the quick fix. Really helpful

**Comment by lejoe** [comment]
other queries work like a charm. Didn't encounter any other problems
