### ISSUE TITLE
Regions' template feature

### ISSUE THREAD

**Issue by ricardobrandao** [agentejo/cockpit#809]
Hi,

Looking through the forum I've found the following [statement](https://discourse.getcockpit.com/t/difference-between-singleton-and-region/47/2):

> Singletons will replace regions. While looking back on past projects I investigated that regions where postly used like “single item” collections (e.g. for global configuration etc). the template feature was pretty useless as most of the time the rendering was on the client side. so regions will get removed from the core and will get replaced by “Singletons”.
 
Until now, we are using **Regions** as a way to define our email templates. I.e., we define the template structure for a given email with some fields that can be customised and/or translated by our customer.

If **Regions** are dropped in favour of **Singletons** we will loose this ability since Singletons don't allow templating. Therefore, we will need to copy the email structure to all the translations and the client will have to dig in the email structure to replace the "custom fields".

Are you willing to keep **Regions** for such use cases or are you inclined to remove Regions from the product? On the other hand, adding templating to Singletons might do the work.

**Comment by aheinze** [comment]
Regions will move out of the core but you'll be able to install it as an addon (addons folder) ... so no need to worry here ☝️

**Comment by ricardobrandao** [comment]
Hi Artur,

Thanks for the quick reply!

Those are great news 👍

One more thing: I'll open a new issue because, as of now, it seems that I'm not able to use the translated content of a region. I.e. it always return the default language.
