### ISSUE TITLE
User-friendly permissions error

### ISSUE THREAD

**Issue by martpie** [agentejo/cockpit#810]
When the storage folder does not have the correct rwx permissions, I get this error. Could it be possible to have a more dev-friendly message? Like `storage/ folder does not have the correct permissions`

<img width="1552" alt="screen shot 2018-07-16 at 14 24 58" src="https://user-images.githubusercontent.com/1311607/42758582-4e946266-8904-11e8-9d9e-63b4e1f355cd.png">

**Comment by aheinze** [comment]
Should be now look like this:

![image](https://user-images.githubusercontent.com/321047/45578956-c11e9180-b884-11e8-85fc-3aab4d8f9291.png)

**Comment by aheinze** [comment]
This checks are done on /install 🤔

**Comment by martpie** [comment]
but you cannot even access /install when those permissions are not there (If I am not mistaken)

**Comment by aheinze** [comment]
This is fixed now!

**Comment by martpie** [comment]
Awesome!
