### ISSUE TITLE
[question] clean database

### ISSUE THREAD

**Issue by RoelantStegmann** [agentejo/cockpit#821]
How can we remove 'old' (removed) fields from the API requests and possibly even the database?

**Comment by DigitalGoldfish** [comment]
If you are willing to edit files manually you can do so by editing the files that contain the data directly:
- For **Regions** the data is stored in PHP files in storage/regions - look for the array key "data"
- For **Collections** the data is stored in an SQLite database in the file /storage/data/collections.sqlite

If you have more than a few records then you might have to write a script that does the cleaning for you - the schema is always stored in PHP files, should not be too hard to read that and match it to the data.

**Comment by gryphonmyers** [comment]
Right now, Cockpit makes no attempt to clean up after itself. I am in the same boat as @DigitalGoldfish - it's annoying, but I haven't been bothered enough to try to write the functionality myself. It should really be a part of Cockpit, probably as an explicit "clean" operation at the collection / singleton level.

**Comment by RoelantStegmann** [comment]
Agree that this shouldn't be automatic. Could imagine a button together with 'export', 'import' called 'clean' that handles it (maybe with an explicit warning). The expected behavior is that it will only leave the fields that exist in the current definition. 

Bit busy with some other parts of my project but might come back to this one day :)

**Comment by aheinze** [comment]
you can do this now via cli `./cp collection/removefield --field myfield`
