### ISSUE TITLE
wtf is slug ?

### ISSUE THREAD

**Issue by michabbb** [agentejo/cockpit#828]
hi, sorry if i missed this, but searching here or in the docu didn´t help me to understand, 
what _**slug**_ is, what it´s used for, i don´t get it, sorry.

**Comment by katespaghetti** [comment]
A URL slug is the exact address of a specific page or post on your site.

**Comment by michabbb** [comment]
thanks a lot, would be nice to have such simple infos somewhere in the docu 😏
