### ISSUE TITLE
"Saving failed" on saving collections

### ISSUE THREAD

**Issue by dragosdydy** [agentejo/cockpit#831]
I can't save any content - collections, forms, etc. After I press save I get "Saving failed" notification on top, and in my console there's an error `Failed to load resource: the server responded with a status of 404 (Not Found) - /admin/collections/save_collection:1 `

Server is fresh, meeting all requirements. Cockpit is installed in /var/www/domain.com/admin 
I am missing something? Sorry if it's a dumb question.

**Comment by mpartipilo** [comment]
Add write permission to the storage folder and sub folders. Cockpit is trying to create files for your schemas and data.

**Comment by dragosdydy** [comment]
Oh, I see. I added permission only to subfolders, my mistake to not change permission for the storage folder itself. 
Thank you for you work!

**Comment by bastianhilton** [comment]
For future people coming here, if you try and save your collections or whatever and it gives an error that says "File not found" do as stated above and give permissions to the storage folder itself along with all of its subfolders. It helped me big time
