### ISSUE TITLE
Copying field data between languages requires a page refresh to avoid overwriting original data

### ISSUE THREAD

**Issue by gryphonmyers** [agentejo/cockpit#832]
**Repro steps:**

1) Create a collection with a localizable field. 
2) Create an entry in this collection with default language data, save. 
3) Switch languages in the editor to any other language than default. 
4) Click to copy data from default language to the new language. Default data populates the field. 
5) Edit this data in some obvious way, save.
6) Switch back to default language. Note that the edit has been applied to the default data as well as the localized data. 

**Expected behavior:**

Editing data that has been copied from one locale to another should always save edits to a copy, not the source of the copy. 

**Workaround:**

Between steps 4 and 5, perform a save and refresh. This mitigates the issue, decoupling the data from the two languages.

**Comment by aheinze** [comment]
which field type did you use? is the value an object?

**Comment by gryphonmyers** [comment]
I was able to produce the bug with both layout and repeater, so yes objects

**Comment by aheinze** [comment]
Could you please test again with the latest `next` code base?

**Comment by gryphonmyers** [comment]
That fixed it!
