### ISSUE TITLE
custom API 

### ISSUE THREAD

**Issue by RoelantStegmann** [agentejo/cockpit#835]
I read somewhere that you can initiate custom API endpoints. I'm however not sure where to do this + what is the advised method :) Any place I can find examples or documentation about this?

**Comment by raffaelj** [comment]
I wrote an example here: https://github.com/raffaelj/cockpit-scripts/blob/master/custom-api-endpoints/jekyll.php

It is an API endpoint to generate a .md file with yaml frontmatter to be reused by [jekyll](https://jekyllrb.com/). It's not ready but I commented the code and you could get an idea, what's possible with this feature.

**Comment by RoelantStegmann** [comment]
Thanks! For the next person looking here, take the listModules as example - it worked best for me :)

project 
  config
    config.yaml
    api 
      listModules.php
