### ISSUE TITLE
How to request a token key when Authenticate user from a client app?

### ISSUE THREAD

**Issue by ronaldaug** [agentejo/cockpit#840]
https://getcockpit.com/documentation/api/cockpit 
I read the documentation and it seems every "fetch" ajax request has to include a token key. 
Form my experience with others API CMS, a user send a post request and a token key is returned. 

Probably, something like this

```
$.ajax({
  type: 'POST',
  url: 'http://mydomain.com/api/auth',
  data: {
    username: 'john@johndoe.com',
    password: 'johndoe'
  },
  success: function(response) {
    console.log('User token', response.jwt);
  },
  error: function(error) {
    console.log('Error : ', error);
  }
});
```
Do I have to generate a new token key in backend panel manually? 

Thanks in advance.

**Comment by ronaldaug** [comment]
Thanks @raffaelj,
But this is similar to the documentation one, my question is requesting a token key with only username and password. 

Let's say my client send a request to **https://mydomain.com/api/cockpit/authUser**
He must have a token key in his hand first, Right?

So basically it means I have to copy a token key from backend panel 
and give to my clients to let them send the requests? 
What if a thousand of clients?

Do I miss something?

**Comment by raffaelj** [comment]
As I understood the code, an api key is necessary. But I'm not 100% sure and I expected, that it's possible with user credentials only before trying it out, too.

But if so, you can use the same key for all your clients. They call `authUser` with this key and in the next step their application can use the user api key `"api_key": "account-SECRETUSERTOKEN"`.

If you don't want to give them a url and a key, give them just a url
`https://mydomain.com/api/cockpit/authUser?token=TheNewApiKeyWithAccessToAuthUser`.

And yes, it would feel cleaner without needing the key in the first place.

**Comment by aheinze** [comment]
Create the following file  `/config/api/public/auth.php` with the following code:

```
<?php

return  $this->invoke('Cockpit\\Controller\\RestApi', 'authUser');
```

now you can query `/api/public/auth` withot a token ☝️

**Comment by raffaelj** [comment]
Another option would be, to allow all requests without an api key if the user credentials match... I copy-pasted a simple solution here: https://github.com/raffaelj/cockpit/commit/cd541c6130ed8b23dbf69b8a7cddb9fd81879f0e

**Comment by aheinze** [comment]
@raffaelj don't agree on this, therefore you should use the account api key

**Comment by ronaldaug** [comment]
@aheinze @raffaelj  
Thanks for your quick replies. 
 It works like a charm.
I love the fact it doesn't have to inject the core codes. 
❤️Cockpit

**Comment by Cryptospy** [comment]
> 



> Create the following file `/config/api/public/auth.php` with the following code:
> 
> ```
> <?php
> 
> return  $this->invoke('Cockpit\\Controller\\RestApi', 'authUser');
> ```
> 
> now you can query `/api/public/auth` without a token ☝️

is this still relevant?  i cant find said directories.
I have a similar issues, i want to hand over user token once the user has logged in. basically i am creating restful front dashboard and this happens to be the first step.

**Comment by raffaelj** [comment]
>  i cant find said directories.
Just create them.

**Comment by andrenajp** [comment]
> > i cant find said directories.
> > Just create them.

don't work for me
