### ISSUE TITLE
_id regenerating when import entries to collection

### ISSUE THREAD

**Issue by alioygur** [agentejo/cockpit#851]
why the _id field discarding on import entries to collection? relationship broken since that.

**Comment by raffaelj** [comment]
If you use the backend for importing collections, you lose `'_id', '_uid', '_created', '_modified'`

If you use the cli, all original data gets stored.

* Open your console, navigate to cockpit and run `./cp export --target outputfolder` (or maybe `php ./cp ...`)
  * Now you have an "outputfolder", which contains the folders /cockpit, /singletons, /collections.
   * Delete the folders and files, you don't want to import.
* Create a collection "newcollectionname" in your new Cockpit.
* Rename `outputfolder/collections/oldcollection.json` to `outputfolder/collections/newcollectionname.json` if you changed the name.
* run `./cp import --src outputfolder` in your new cockpit

All your old collection data should be stored with original ids and dates.
