### ISSUE TITLE
Invalid command 'Deny'

### ISSUE THREAD

**Issue by dur41d** [agentejo/cockpit#854]
I installed a fresh copy and when I go to /cockpit/install i get error 500. The log says:

`cockpit/.htaccess: Invalid command 'Deny', perhaps misspelled or defined by a module not included in the server configuration`

I guess i have to comment the lines that say Deny in the .htaccess but I'm afraid that will cause a security issue.

PHP: Version 7.2.9-nfsn1
OS:  FreeBSD 11.2-RELEASE-p2

**Comment by aheinze** [comment]
Hi,

do you use apache >=2.4 then you would need to replace `Deny` with `Require`, e.g.:

```
Order deny,allow
Deny from all
```
to
```
Require all denied
```

https://httpd.apache.org/docs/2.4/upgrading.html


Greets,
Artur
