### ISSUE TITLE
Fetch singleton schema through API

### ISSUE THREAD

**Issue by andrewn** [agentejo/cockpit#856]
Is there any way to fetch the schema of a singleton via the API, in the same way as `/api/collections/collection/{collectionname}` supports?

I've tried `/api/singletons/singleton/{singletonname}` but get a 404.

The use case for this request is for libraries such as [gatsby-plugin-cockpit](https://github.com/ginetta/ginetta-gatsby-source-plugin/tree/master/gatsby-plugin-cockpit) that introspect the schema of collections to convert data depending on the field type. For example, `image` and `gallery` field types. It woud be *very* useful to do this for singletons too.

**Comment by aheinze** [comment]
Good point. Added wit this commit: https://github.com/agentejo/cockpit/commit/0d0661fbf0ea0f4cb46e346d447c48ffca0068dd

Thanks!

**Comment by andrewn** [comment]
Amazing, thanks!
