### ISSUE TITLE
Error 500 when saving collection with faulty characters

### ISSUE THREAD

**Issue by natemate90** [agentejo/cockpit#866]
When not being aware that the - (dash) character is not allowed in the creation of a collection, one can end up with an error 500 not being able to access the dashboard anymore (at least when the "show in system menu" is marked). Despite of the invalid character, cockpit cms will create an empty collection when using ctrl + s).

I don't know much about the cockpit cms structure but I was able to recover the dashboard after renaming the collection in the /storage/collections/ folder.

However, I can't delete the collection anymore (error 401) and I'm stuck with an invalid collection

**Comment by natemate90** [comment]
I didn't! Just used ctrl-s keyboard shortcut as I was in a hurry ;-)
then Cockpit said that collection was successfully saved, after this the "Uuuups, something went wrong."

**Comment by raffaelj** [comment]
This is a problem of trusting browser validation without server-side validation. This can happen, if (old) browsers don't know this pattern thing or if evil users modify the html before sending the form.
