### ISSUE TITLE
javascript redirect on collections entries pages, can't navigate back in browser

### ISSUE THREAD

**Issue by raffaelj** [agentejo/cockpit#867]
Collection entries view redirects itself on each request and I can't navigate back in the browser. It also happens on the first request. Collections with sortable entries only redirect on changes.

`http://localhost/cockpit/collections/entries/booltest` redirects to
`http://localhost/cockpit/collections/entries/booltest?q={...}`

Here is the part, that produces this issue:
https://github.com/agentejo/cockpit/blob/next/modules/Collections/views/partials/entries.php#L464-L472

I fixed it [here](https://github.com/agentejo/cockpit/commit/78b3e88c061a960cbd6525481bfe3c6fc7a3f7fa), but I added another hack in the [nect commit](https://github.com/agentejo/cockpit/commit/464f58907a5eb6a9f69166fbc67f0b12390d7a6f) to make the redirect more generic.

This redirect was one reason, why some tests with invoking classes failed.
https://discourse.getcockpit.com/t/how-to-extend-controller-restapi-php-or-admin-php-of-core-modules/288

**Comment by aheinze** [comment]
should be fixed with this commit: https://github.com/agentejo/cockpit/commit/014e6d65b47706104ddaa391ba74b2ab265fc2cf

**Comment by raffaelj** [comment]
Thanks. Going back in browser history works and it doesn't redirect after invoking/extending a controller anymore on first load.

Would you consider, to change the hardcoded line
`App.route(['/collections/entries/', this.collection.name, '?q=', JSON.stringify({`
into `App.route(['{{ $app['route'] or similar }}', '', '?q=', JSON.stringify({`?

If yes, it would be possible to add an collection entries view to an addon without touching much code.
`url/to/cockpit/addonname/collectionname` could `return $this->invoke('Collections\\Controller\\Admin', 'entries', [$name]);` and the filters wouldn't destroy the url.

If not, it's OK. The defaults work and if I really need it, I can change the view file in `/config/collections/name/views/entries.php` already or extend the Admin class.
