### ISSUE TITLE
Image uploads via API?

### ISSUE THREAD

**Issue by eberfreitas** [agentejo/cockpit#868]
I need to automate a lot of "posts" insertion on this website I'm building trying to get out of wordpress. On wordpress I used a script to "upload" (basically move locally) images and attach them to the post. How can I do something like that with cockpit? I couldn't find any info about that on the docs or anywhere (forums, issues, etc).

Thanks in advance. Awesome project. Looking forward to work with it.

**Comment by mrpatg** [comment]
I'm also curious about this.

**Comment by eberfreitas** [comment]
So... What I did was to mimic the application adding records directly the database and copying the files later. Not ideal as not everyone might have access to the database but it worked for me...

**Comment by iryanrachman** [comment]
> So... What I did was to mimic the application adding records directly the database and copying the files later. Not ideal as not everyone might have access to the database but it worked for me...

can you explain how do you do it please...

**Comment by eberfreitas** [comment]
> can you explain how do you do it please...

It was so long ago, and I didn't end up using cockpit... But I think I just inserted the data on the database and copied the files "manually" (with my own script).
