### ISSUE TITLE
Feature Request: Reformat meta titles

### ISSUE THREAD

**Issue by crtl** [agentejo/cockpit#872]
Hello,
Cockpit is good but given the following screenshot it can be also annoying:

![image](https://user-images.githubusercontent.com/25827827/46128502-f5eef900-c233-11e8-8a13-4bd75ad945c4.png)

So I would suggest to format the site titles in a way the information is ordered by importance like:
- Collections - Cockpit
- CollectionName - Collections - Cockpit

etc.

**Comment by raffaelj** [comment]
It is on the to do list already

> artur
> Thanks for the suggestion! I’ll add it o my todo list

https://discourse.getcockpit.com/t/page-titles-in-backend-head-title-controller-app-name/281
