### ISSUE TITLE
[REQUEST] Filter / branching rules for Webhooks

### ISSUE THREAD

**Issue by gryphonmyers** [agentejo/cockpit#874]
A common need for webhooks is to trigger (or not trigger) different URLs depending on the state of the data the event is being triggered for. e.g. my collection has a "should purge" boolean field, and depending on whether or not that bool is checked, we do or do not trigger a purge request to a caching server. I could see this feature working similar to the way you have ACL rules set up for collections (field that takes some php code, with relevant data revealed in that context), with the returned value being used for the request endpoint.

**Comment by raffaelj** [comment]
This is possible already if you make a small detour. Add this to config/bootstrap.php

```php
$app->on('collections.save.after.triggertest2', function($name, &$entry, $isUpdate) {
    if ($entry['purge'] == true) {
        $this->trigger('my.custom.trigger');
    }
});
```

and change your webhook to 'my.custom.trigger'.

**Comment by gryphonmyers** [comment]
Thanks for the suggestion, @raffaelj. It's not a bad workaround, but I still think the UI for it would be better :D
