### ISSUE TITLE
Not generating thumbnails for assets (site url is missing)

### ISSUE THREAD

**Issue by mskraban** [agentejo/cockpit#877]
I'm unable to reorder images on my website, because thumbnails for images are not generating inside cockpitcms collections entry. I'm trying to find file inside modules folder where I could change path, that generates thumbnail.

My current not working path: src="//cockpit/storage/uploads/2018/01/30/5a702abcf1224test-image.jpg"

Site url ="https://site.com"

Working path (if manually inserted into browser url)="https://site.com/cockpit/storage/uploads/2018/01/30/5a702abcf1224test-image.jpg"

**Comment by weinde** [comment]
I'm having the same issue!  **(cockpit version 0.5.1)**
