### ISSUE TITLE
changing user name breaks login if user with same name exists

### ISSUE THREAD

**Issue by raffaelj** [agentejo/cockpit#885]
I tried, what happens if I change the user name "editor" to "admin". Of course, I didn't get the admin credentials, but I wasn't able to login again with my username.

The user admin was created before the user editor. OK, next test: I created a new admin user and changed editor to newadmin. Now the new admin wasn't able to login.

User names should be unique and readonly.

And it's possible, but it feels wrong: user names and passwords can contain whitespaces. Login works fine with whitespaces.

**Comment by aheinze** [comment]
Your concerns were adressed in this commit: https://github.com/agentejo/cockpit/commit/a75a9a6db8daae5d3ca9fca74f6dc7d9bb6b02d9

**Comment by raffaelj** [comment]
The unique check fails again. Not sure, if I didn't test it enough yesterday.

It fails under these conditions:

* a user `user2` with mail `user2@example.com` was created later than user `user1` with mail `user1@example.com`
* user1 changes name OR mail (not both)
* `findOne(...)` finds the user `user1` and `$exists` says, everything is alright
* now the user1 (with name `user2`) can change the mail adress to `user2@example.com`, too.

---
Thanks for the new trigger `'cockpit.accounts.save', [&$data, isset($data['_id'])]`. All these checks and responses, opened a new issue: A user could crawl for all user names and mail addresses. We can catch brute forcing on this trigger and setup a mail confirmation system here if necessary.

**Comment by aheinze** [comment]
@raffaelj should be fixed now: https://github.com/agentejo/cockpit/commit/e405176bda5779d86a769b5b9ea2770eb39e976d

**Comment by raffaelj** [comment]
looks good now - unique check works
