### ISSUE TITLE
Wrong path used in Image/Gallery components

### ISSUE THREAD

**Issue by flayks** [agentejo/cockpit#893]
I'm using the latest version of Cockpit (with the recent changes) and AFAIK I think it's using a wrong folder location with Image/Gallery components.

For example I pick few images and it adds `portfolio/…` at the beginning of the path, which is wrong. It should be `medias/image…`. So I have to remove in my website code the `portfolio/` part in the path, which is a bit annoying, or remove it manually from the path using "Enter Image URL" in Cockpit for each image.

Any idea of what happens here? Yes, my local website is on `~/www/portfolio`, but idk why the Components are using this path as the root it should be `/` or even blank.

**Comment by raffaelj** [comment]
Maybe you have to adjust the `COCKPIT_SITE_DIR` or other constants in `defines.php`. There is a dir string replacement for assets: https://github.com/agentejo/cockpit/blob/next/modules/Cockpit/bootstrap.php#L167

This can happen if you use symlinks and I recently had a weird [issue](https://github.com/agentejo/cockpit/issues/905) where the root dir wasn't deep enough in a symlinked windows environment.
