### ISSUE TITLE
Secure post to collection - or form

### ISSUE THREAD

**Issue by stefanKBL** [agentejo/cockpit#902]
Hi,
first of all I am very impressed by cockpit, building a multi collections project with vue.js frontend.
Part of the project is the ability of posting contacts and Ads from frontend, without user account. So it's ok for me to call the save form api or even the save collection api from Axios, but my question is : as the token key is public, how to prevent the api will not be spammed or used by another front end ? Do i have to inject my own process to cockpit (via custom endpoint ?) or is there a core way to do ?
Thanks a lot for cockpit
Stefan

**Comment by raffaelj** [comment]
There is no inbuilt server side validation, so you have to inject your own process. I wrote the [FormValidation addon](https://github.com/raffaelj/cockpit_FormValidation) for this purpose. It's not complete yet, but it has a few functions to validate data without the need of a captcha. I tried to write the [validation class](https://github.com/raffaelj/cockpit_FormValidation/blob/master/FormValidation/Controller/FormValidation.php) in a way, that it can be abstracted to validate collection fields, too. But for now it's limited to forms.

If you don't care about your visitor's privacy, there is a [reCaptcha addon](https://github.com/Bixie/cockpit-recaptcha). I never tested, if it works, but it could be a fast start for spam protection.

> how to prevent the api will not be spammed or used by another front end

You could change the api key on a regular basis or validate against `$_SERVER` variables to dismiss unallowed requests.

**Comment by stefanKBL** [comment]
@raffaelj thanks for answer.
i already used your forms validation module and will try to extend for the collections as it works great.
For prevent api usage, yes you are right, using CORS allowedOrigins for example is a way. I will also add a sort of ip whitelist.

**Comment by raffaelj** [comment]
Well... It was on my to do list with a very low priority, but I love riddles ;-)

Not sure, if it could break anything, but my first tests seemed to work. You have to adjust some options in `storage/collections/validatetest.php` (sample below) by hand or use the VERY EXPERIMENTAL [MoreOptions addon](https://github.com/raffaelj/cockpit_MoreOptions) if you want to change all options in a json field via GUI.

And please keep me updated if you improve the validator - here... or better start a new discussion on discourse or in the FormValidation issues.

Add this to `config/bootstrap.php`:

```php
<?php

$app->on('collections.save.before.validatetest', function($name, &$entry, $isUpdate){
    
    $frm = $this->module('collections')->collection($name);
    
    $data = $entry;
            
    // load validation class
    require_once(COCKPIT_DIR . '/addons/FormValidation/Controller/FormValidation.php');
    
    $validated = new Forms\Controller\FormValidation($data, $frm);
    
    // continue if true or send error messages to sender
    if (true!==$validated->response()) {

        $error = '';
        foreach ($validated->response() as $field => $errors) {
          
            foreach ($errors as $e) {
                $error .= "$field: $e<br>";
            }
        }
        
        $this->stop(['error' => $error], 412);
        
    }
    
});
```

sample collection:

```php
<?php
 return array (
  'name' => 'validatetest',
  'label' => '',
  '_id' => 'validatetest5bd44c24cb076',
  'allow_extra_fields' => true, // don't fail on _id, _created etc.
  'fields' => 
  array (
    0 => 
    array (
      'name' => 'name',
      'label' => '',
      'type' => 'text',
      'default' => '',
      'info' => '',
      'group' => '',
      'localize' => false,
      'validate' => true, // validate this field
      'options' => // validate options
      array (
        'validate' => 
        array (
          'type' => 
          array (
            'url' => false,
            'mail' => false,
          ),
        ),
      ),
      'width' => '1-1',
      'lst' => true,
      'acl' => 
      array (
      ),
    ),
    1 => 
    array (
      'name' => 'mail',
      'label' => '',
      'type' => 'text',
      'default' => '',
      'info' => '',
      'group' => '',
      'localize' => false,
      'validate' => true, // validate this field
      'options' =>  // validate options
      array (
        'validate' => 
        array (
          'type' => 
          array (
            'url' => false,
            'mail' => true,
          ),
        ),
      ),
      'width' => '1-1',
      'lst' => true,
      'acl' => 
      array (
      ),
    ),
  ),
  'sortable' => false,
  'in_menu' => false,
  '_created' => 1540639780,
  '_modified' => 1540639780,
  'color' => '',
  'acl' => 
  array (
  ),
  'rules' => 
  array (
    'create' => 
    array (
      'enabled' => false,
    ),
    'read' => 
    array (
      'enabled' => false,
    ),
    'update' => 
    array (
      'enabled' => false,
    ),
    'delete' => 
    array (
      'enabled' => false,
    ),
  ),
);
```

**Comment by aheinze** [comment]
I would recommend to config `cors/allowedOrigins` correctly: https://github.com/agentejo/cockpit/blob/next/index.php#L24

so, in your config.yaml:

```yaml
cors:
    allowedOrigins: https://yourdomain.com
```
