### ISSUE TITLE
Please update the docs :-)

### ISSUE THREAD

**Issue by stefanKBL** [agentejo/cockpit#903]
using cockpit, i try to well understand how to manage permissions.
What i understood, there is multiple solutions:
- first, we can set permissions via admin api access page (generate a new api key and set rules), or use the permission tab from each collections. When permission is set via api access page permissions tab are useless, is it correct ?
- then, if choice is to set permissions via api access page in admin panel, we can generate an api key and set * to rules (so all apis are opened to public). Surely the bad one solution :-)  at my opinion
- next, if we do not want to let opened all apis, 2 choices:
1. using the api key rules, we can indicate opened apis as api/collections/get/posts, or api/forms/submit/newsletter_subscription (1 per line).
2. let the api key rules empty (means no apis access) and set permissions via each collections tabs. (except for forms as forms do not have permission tab)

If this is correct, i will try to update the docs for this part.

ps. what i still not understand and not investigate is what for are the CRUD tabs at the bottom of the collections permissions tab. Set PHP webhook ?

enjoy Cockpit
Stefan

**Comment by jankal** [comment]
We are currently working on new docs. For an early in-development version, head [here](https://zeraton.gitlab.io/cockpit-docs/).
