### ISSUE TITLE
Change configuration for uploading large size images with docker

### ISSUE THREAD

**Issue by gbikas16** [agentejo/cockpit#904]
Hello,

Is there any way to change the max size configuration for files when using docker? I've seen this [`](https://github.com/agentejo/cockpit/issues/664) but I don't know how to implement it , while serving a docker image directly.

You've done a great work. Thank you!

**Comment by johnfoley** [comment]
Thanks for your mail. I am out of the office and offline all day Thursday 25 October 2018. For any urgent matters please do not hesitate to contact the office, otherwise I will respond to your mail on Friday.
