### ISSUE TITLE
settings/edit can't load config.yaml if symlink and COCKPIT_SITE_DIR ends with slash

### ISSUE THREAD

**Issue by raffaelj** [agentejo/cockpit#905]
Since a while, my settings/edit view can't load the config file anymore. I never realized the real reason and tests with fresh downloaded cockpits (without symlinks) always worked correctly. Most of the time I change the config with the text editor, so I forgot it. But now I found the reason.

My setup is (Windows and Xampp):

* cockpit's path is `E:\github\cockpit` with a symlink to `E:\xampp7\htdocs\cockpit`
* localhost points to `E:\xampp7\htdocs`

This leads to `[COCKPIT_SITE_DIR] => E:\`

So I detected two issues in one:

1. `COCKPIT_SITE_DIR` is wrong (all other paths have directory separator replacements)
2. `settings/edit.php` can't replace `COCKPIT_SITE_DIR` correctly and sends the full path instead of a relative path `path: E:/github/cockpit/config/config.yaml`

It works if I replace https://github.com/agentejo/cockpit/blob/next/bootstrap.php#L56

```php
if (!defined('COCKPIT_SITE_DIR'))               define('COCKPIT_SITE_DIR'       , COCKPIT_DIR == COCKPIT_DOCS_ROOT ? COCKPIT_DIR : str_replace(DIRECTORY_SEPARATOR, '/', dirname(COCKPIT_DOCS_ROOT)));
```

and https://github.com/agentejo/cockpit/blob/next/modules/Cockpit/views/settings/edit.php#L19

```
<picoedit path="{{ str_replace(rtrim(COCKPIT_SITE_DIR, '/') . '/', '', $configexists) }}" height="auto" readonly="{ {{ !is_writable($configexists) ? 'true':'false'}} }"></picoedit>
```

But it looks a bit ugly.

**Comment by aheinze** [comment]
Cockpit is build to recognize the most common setups. But there are scenariaos out there (like yours) where you need some fine tuning. therefore cockpit loads looks for a `defines.php` on boot (https://github.com/agentejo/cockpit/blob/next/bootstrap.php#L28-L30), so you can setup your cockpit instance according to your environment.

**Comment by raffaelj** [comment]
Of course, it was too obvious to use `defines.php`.

If someone else stumbles upon this issue here is a generic check to set COCKPIT_SITE_DIR to the right windows volume:

```php
// check if cockpit is in a Windows environment in E:\git\cockpit
// cockpit would define('COCKPIT_SITE_DIR', 'E:\'), which leads to wrong replacement patterns
$COCKPIT_SITE_DIR = dirname(dirname(__DIR__));
if (strpos($COCKPIT_SITE_DIR, ':\\', 1)) {
    define('COCKPIT_SITE_DIR', rtrim($COCKPIT_SITE_DIR, '\\')); // E:
}
```
