### ISSUE TITLE
Image upload not working

### ISSUE THREAD

**Issue by drieshooghe** [agentejo/cockpit#910]
I have a collection where I try to upload an Asset, a jpg file of 516kb.
The loader gets to a 100% but then the "Something went wrong." message appears.
The file is not stored in the uploads directory, it is however present in the storage/tmp directory.

I checked and the storage/uploads directory is writable.

### info
PHP version: 7.2.11
Upload file size limit: 4M
Memory limit: 128M
Cockpit version: 0.8.3
OS: Debian 9 Stretch
Web server: Nginx

**Comment by pauloamgomes** [comment]
@drieshooghe check in the devtools network tab what response message you have for the upload request

**Comment by drieshooghe** [comment]
@paoloamgomes I forgot to mention, the application returns a 500 error

**Comment by pauloamgomes** [comment]
sure, but what you have in the network tab response, check below:

![image](https://user-images.githubusercontent.com/102261/48083493-3788a180-e1ed-11e8-97ab-03584f4aa7f2.png)

just to understand if there is anything more about the error

**Comment by drieshooghe** [comment]
![image](https://user-images.githubusercontent.com/25033847/48114864-05188c00-e261-11e8-9cd3-3e99eb9d5ef2.png)
![image](https://user-images.githubusercontent.com/25033847/48115064-cafbba00-e261-11e8-999d-003ef3d39f8a.png)

**Comment by pauloamgomes** [comment]
@drieshooghe I know you said that you have correct permissions, but just for be sure, give full permissions (including group and others - 777) on the storage/uploads folder and test again.

**Comment by drieshooghe** [comment]
![image](https://user-images.githubusercontent.com/25033847/48145889-1f2f8a00-e2b4-11e8-8f71-cb1278fceb6f.png)

![image](https://user-images.githubusercontent.com/25033847/48145827-fa3b1700-e2b3-11e8-90ac-d849fc2119f9.png)

I still get the same result.

**Comment by pauloamgomes** [comment]
Yeah, was expecting that 😞 Do you can upload assets on the asset page?

**Comment by drieshooghe** [comment]
Nope, no luck...

**Comment by drieshooghe** [comment]
@pauloamgomes I resolved the issue.
The PHP GD extension wasn't installed correctly, which caused the problem.
All is well! Thank you for your help.

Perhaps the php GD extension is an idea for an additional check in the installer script?

**Comment by mpartipilo** [comment]
@drieshooghe I'm having the same problem running Cockpit with the Dockerfile. What was wrong with GD in your setup? Maybe I have the same problem.

**Comment by mpartipilo** [comment]
It gets worse. I run cockpit locally with the exact same docker compose file and uploading works.

**Comment by mpartipilo** [comment]
Some more information:
This is the status code returned: 413 Request Entity Too Large

Strange, since the file being uploaded is barely 3MB and the .htaccess file sets the upload max size to 256M

**Comment by mpartipilo** [comment]
Found the reason... Locally I'm accessing the cockpit instance directly, but on my remote server it's running behind nginx as reverse proxy. Something must have changed in the nginx config that limits the size of the upload files. I updated the nginx config and it all works now.

**Comment by hypo-thesis** [comment]
So for future ref this is how I dealt with it

Step 1 : go to bootstrap.php line 100 and set 'debug' = true, since my error was `Call to undefined function finfo_open()`
Step 2 : install fileinfo	Universal Extensions if is not installed on your php
Step 3 : go to php.ini of your website and find extension=fileinfo and remove the ;
Step 4 : reload and restart php service on your server.

Now I can upload files. Cockpit still rules
