### ISSUE TITLE
[Idea] remove lib/vendor

### ISSUE THREAD

**Issue by AienTech** [agentejo/cockpit#915]
Hi there,

so, as the title suggests, why not remove lib/vendor and let users install composer dependencies using `composer install`?

**Comment by aheinze** [comment]
Hi,

I want Cockpit as easy as it can be to setup an run for everyone (not only php developers). Just drop the files on a php enabled webserver and you‘re ready to go.

Plus, I support these arguments:  https://www.codeenigma.com/build/blog/do-you-really-need-composer-production

**Comment by AienTech** [comment]
Although I can't completely agree with the arguments stated in the blog post, I do understand your approach to make the project easier for other users. I personally added the vendor foler to gitignore and let the CI install dependencies for me.

another thing which came to my mind, me and my team are building a headless cms based on top of cockpit. Though it's kinda taking long time to understand the architecture of codes. Wouldn't it be nice to create a documentation for developers, so that they could also help on developing the project? (We would gladly help with development process if we have a blueprint of the project)

**Comment by aheinze** [comment]
A headless cms on top of a headless cms !? 🤔 But I wish you the best 👍

Of course it would be nice to have a more detailed documentation, but it would be also nice to have time for that ;-)

Cockpit is not a commercial product. I have contract work to do which will always have a higher priority as it pays the bills (+ enables Cockpits further development). Then I have also to do community support and maintain the current codebase. Btw. my family is also happy if spend some time with them ;-)

So, I would like to invite you to dive into Cockpit and contribute to the docs taking the knowledge from what you'll learn. Cockpits codebase isn't that complicated, I always tried to keep it simple as possible.
There are plenty of addons for Cockpit already out there, made by people without having any prior touch points with Cockpit.

I hope you accept the challenge ;-)

Greets,
Artur
