### ISSUE TITLE
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by lechaps** [agentejo/cockpit#917]
Hi

I made a collection named 'article" with one simple record (id:"1" libelle:"test").
I put public permission to View Entries but when i try to use the api _http://localhost:32769/api/collections/article/?token=b18644a65d97f5c076532555be08b8_ the answer is 
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

i don't find the solution. Can you help me ?

**Comment by lechaps** [comment]
nervermind, the right adresse is _http://localhost:32769/api/collections/get/article/?token=b18644a65d97f5c076532555be08b8_

But i think, i'll be better if you catch the error.

Best regards

**Comment by raffaelj** [comment]
The error is simple. The response was `Path no found` (404), which is not a JSON string and can't be parsed.

**Comment by lechaps** [comment]
Indeed. Thank you for this answer and this nice project.
