### ISSUE TITLE
Running on HTTPS behind a load balancer with HTTP

### ISSUE THREAD

**Issue by kulrich-kwp** [agentejo/cockpit#926]
We are currently running Cockpit behind an Elastic Load Balancer configured as follows:

User <--443--> Load Balancer <--80--> Cockpit

This is running fine so far, except for a problem with Asset-URL. Since Cockpit behind the load balancer is running on HTTP, the following function (i presume) will always cause an http:// in front of asset URLs:

https://github.com/agentejo/cockpit/blob/next/lib/Lime/App.php#L1146

This will then cause a mixed content warning in most browsers or refuse to work at all.

It would be very helpful to be able to override this behaviour instead of having it hardcoded via superglobals. Thank you.

**Comment by aheinze** [comment]
you can now define `site_url` in the config

```
site_url: https://domain.com
```
