### ISSUE TITLE
Edit collection links seem broken

### ISSUE THREAD

**Issue by lejoe** [agentejo/cockpit#932]
When on the collection screen you try to click in the edit collection link, the link is: 
[http://localhost:8080/collections/collection/[object%20Object]](http://localhost:8080/collections/collection/[object%20Object])
This leads to a 401 page

![image](https://user-images.githubusercontent.com/1759/48784320-b9df8e00-ece2-11e8-8c9a-c3a46f770e44.png)

**Comment by lejoe** [comment]
We're using the latest next build btw

**Comment by aheinze** [comment]
Should be fixed now
