### ISSUE TITLE
Collections overview page broken

### ISSUE THREAD

**Issue by JesperWe** [agentejo/cockpit#934]
The commit fd3dbe69247f62db033fa7eeae69c5c098e29e44 broke the collections overview page for us. Just getting "500 :-( Uuuuuups something went wrong". 

Other pages work, including individual collections and collection entries.

**Comment by aheinze** [comment]
please make sure that you have the mbstring (multibyte string) extension installed and enabled (this is a common extension and enabled on almost all webservers)

**Comment by JesperWe** [comment]
Ok, that was it.

**Comment by aheinze** [comment]
you're welcome...
