### ISSUE TITLE
Error: cannot download "pecl/mongodb"

### ISSUE THREAD

**Issue by sintaxx** [agentejo/cockpit#936]
Attempting the dockerized version

1. Run `npm run docker-init` to build the initial image.

`WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
Could not download from "http://pecl.php.net/get/mongodb-1.5.3.tgz", cannot download "pecl/mongodb" (File http://pecl.php.net:80/get/mongodb-1.5.3.tgz not valid (received: HTTP/1.0 500 Internal Server Error
))
Error: cannot download "pecl/mongodb"
Download failed
install failed
The command '/bin/sh -c apt-get update     && apt-get install -y                wget zip unzip         libfreetype6-dev         libjpeg62-turbo-dev         libpng-dev         sqlite3 libsqlite3-dev         libssl-dev     && pecl install mongodb     && pecl install redis     && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/     && docker-php-ext-install -j$(nproc) iconv gd pdo zip opcache pdo_sqlite     && a2enmod rewrite expires' returned a non-zero code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cockpit-next@0.8.3 docker-init: `docker build -t cockpit/dev .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cockpit-next@0.8.3 docker-init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
`

**Comment by colinappnovation** [comment]
@sintaxx have just run the container build and run, all was well. Was able to login to Cockpit instance without hassle.

**Comment by webdenis77** [comment]
For everyone facing the same issue. For me the problem was that PhpStrom was listening for xdebug connections and was interrupting docker install. When i closed PhpStorm, everything was installed normally.
