### ISSUE TITLE
app-action-bar - no body-padding in some views in Firefox

### ISSUE THREAD

**Issue by raffaelj** [agentejo/cockpit#940]
I don't understand why, but the app-action-bar overlaps in `/collections/collection/collectionname` view in Firefox. For some reason the body has no padding-bottom.
Same problem with:
* singletons edit view
* forms
* api access
* ...?

![cp-app-action-bar-apply-css-body-firefox](https://user-images.githubusercontent.com/13042193/48969661-f4f30180-f001-11e8-978c-06fa35f7674e.png)

It works in `/accounts/account`

![cp-app-action-bar-apply-css-body-firefox-account-works](https://user-images.githubusercontent.com/13042193/48969731-07216f80-f003-11e8-9148-b269e96a0d45.png)

**System**

OS: Windows 7 64bit

Cockpit: latest next branch without any addons

* 60.3.0esr (64-Bit) with script blockers and multiple addons etc. --> fails
* fresh installed FirefoxPortable 63.0.3 without addons --> fails
* Opera 56.0.3051.104 --> everything works

**Comment by raffaelj** [comment]
Still the same behaviour. Should be reopened.

**Comment by raffaelj** [comment]
I found a solution. Remove https://github.com/agentejo/cockpit/blob/next/assets/app/js/bootstrap.js#L127-L129 and it works in Firefox and Opera.

I tested the lines directly in the console and it seems, that some data is not valid:
`document.body.style.paddingBottom = '70'` --> fails
`document.body.style.paddingBottom = ''` --> fails
`document.body.style.paddingBottom = '70px'` --> works

**Comment by aheinze** [comment]
I can't confirm this.

Which Firefox version do you have? Did you clear the browser cache?

**Comment by raffaelj** [comment]
I overlooked, that it works with the fresh installed FirefoxPortable 63.0.3 without addons now. So your last commit seems to work.

My Firefox 60.3.0esr (64-Bit) with script blockers and multiple addons still has `<body style="">` and no padding-bottom. After deactivating all addons and restarting Firefox it's the same. But maybe something broke since the last Firefox update to Quantum, when a some plugins didn't work anymore. I never cleaned it up... Otherwise - until now everything worked. It is only this padding-bottom.

Another test with an older FirefoxPortableESR 52.5.0 (64-bit) with disabled addons:

![cp-app-action-bar-apply-css-body-firefox_2](https://user-images.githubusercontent.com/13042193/49124887-62cb5180-f2be-11e8-8a6d-d969e84b55dc.png)

It doesn't work.

**Comment by raffaelj** [comment]
After some research and tests it seems, that Firefox [ESR](https://www.mozilla.org/en-US/firefox/organizations/) triggers the `disconnectedCallback()` each time for some weird reason... but I'm not 100% sure.

It was so annoying, that I installed the latest Firefox Quantum and finally I'm able to see and click all buttons again.

Removing the whole `disconnectedCallback()` worked for me with "normal" Firefox and with the extended support release.

But the bug still exists.

**Comment by raffaelj** [comment]
@artur: Please reopen this issue.

Today I had the same problem on a clients PC. I was a bit confused, when she told me, that she can't upload gallery images and the issue was simple: She didn't see the gallery upload icon, because it was the last field in the collection and the action bar overlapped it.

System:
MacOS X El Capitan 10.11.6
Firefox Quantum 60.6.3esr (64-Bit)

So it is an Firefox ESR again.
