### ISSUE TITLE
500 Internal Server Error 

### ISSUE THREAD

**Issue by erkand-imeri** [agentejo/cockpit#942]
Hello, i just downloaded cockpit cms to give it a try. But i am getting the 500 internal server error after i route to path/cockpit/install on local wamp server.

This is the only thing the page displays

`Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at wampserver@wampserver.invalid to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.`

Anyone knows why i can't keep cockpit cms running?

I fullfill all the requirements (i believe).

PHP >= 7.1
PDO with SQLite support (or MongoDB)
GD, Zip extension enabled
Apache (with mod_rewrite enabled) or nginx

**Comment by aheinze** [comment]
Hi,

do you have access to the php error log file?

**Comment by erkand-imeri** [comment]
> Hi,
> 
> do you have access to the php error log file?

Yeah i do, here is the php error log file.

[03-Nov-2018 17:32:41 UTC] No error - Only to create the file

Also, this is the Apache error log file.

`[Sat Nov 03 13:32:42.955469 2018] [mpm_winnt:notice] [pid 9200:tid 760] AH00455: Apache/2.4.35 (Win64) PHP/7.2.10 configured -- resuming normal operations
[Sat Nov 03 13:32:42.956468 2018] [mpm_winnt:notice] [pid 9200:tid 760] AH00456: Apache Lounge VC15 Server built: Sep 19 2018 16:08:47
[Sat Nov 03 13:32:42.956468 2018] [core:notice] [pid 9200:tid 760] AH00094: Command line: 'c:\\wamp64\\bin\\apache\\apache2.4.35\\bin\\httpd.exe -d C:/wamp64/bin/apache/apache2.4.35'
[Sat Nov 03 13:32:43.116370 2018] [mpm_winnt:notice] [pid 9200:tid 760] AH00418: Parent: Created child process 11164
[Sat Nov 03 13:32:44.541488 2018] [mpm_winnt:notice] [pid 11164:tid 700] AH00354: Child: Starting 64 worker threads.
[Sun Nov 04 12:28:15.719193 2018] [mpm_winnt:notice] [pid 9200:tid 760] AH00422: Parent: Received shutdown signal -- Shutting down the server.
[Sun Nov 04 12:28:17.723165 2018] [mpm_winnt:notice] [pid 11164:tid 700] AH00364: Child: All worker threads have exited.
[Sun Nov 04 12:28:17.874302 2018] [mpm_winnt:notice] [pid 9200:tid 760] AH00430: Parent: Child process 11164 exited successfully.
[Tue Nov 06 19:04:16.577505 2018] [mpm_winnt:notice] [pid 4612:tid 784] AH00455: Apache/2.4.35 (Win64) PHP/7.2.10 configured -- resuming normal operations
[Tue Nov 06 19:04:16.580503 2018] [mpm_winnt:notice] [pid 4612:tid 784] AH00456: Apache Lounge VC15 Server built: Sep 19 2018 16:08:47
[Tue Nov 06 19:04:16.580503 2018] [core:notice] [pid 4612:tid 784] AH00094: Command line: 'c:\\wamp64\\bin\\apache\\apache2.4.35\\bin\\httpd.exe -d C:/wamp64/bin/apache/apache2.4.35'
[Tue Nov 06 19:04:16.612484 2018] [mpm_winnt:notice] [pid 4612:tid 784] AH00418: Parent: Created child process 176
[Tue Nov 06 19:04:18.860092 2018] [mpm_winnt:notice] [pid 176:tid 448] AH00354: Child: Starting 64 worker threads.
[Thu Nov 08 06:23:00.514540 2018] [mpm_winnt:notice] [pid 4612:tid 784] AH00422: Parent: Received shutdown signal -- Shutting down the server.
[Thu Nov 08 06:23:02.545765 2018] [mpm_winnt:notice] [pid 176:tid 448] AH00364: Child: All worker threads have exited.
[Thu Nov 08 06:23:02.592593 2018] [mpm_winnt:notice] [pid 4612:tid 784] AH00430: Parent: Child process 176 exited successfully.
[Thu Nov 08 06:33:15.832937 2018] [mpm_winnt:notice] [pid 12236:tid 740] AH00455: Apache/2.4.35 (Win64) PHP/7.2.10 configured -- resuming normal operations
[Thu Nov 08 06:33:15.832937 2018] [mpm_winnt:notice] [pid 12236:tid 740] AH00456: Apache Lounge VC15 Server built: Sep 19 2018 16:08:47
[Thu Nov 08 06:33:15.832937 2018] [core:notice] [pid 12236:tid 740] AH00094: Command line: 'c:\\wamp64\\bin\\apache\\apache2.4.35\\bin\\httpd.exe -d C:/wamp64/bin/apache/apache2.4.35'
[Thu Nov 08 06:33:15.838931 2018] [mpm_winnt:notice] [pid 12236:tid 740] AH00418: Parent: Created child process 12280
[Thu Nov 08 06:33:18.160497 2018] [mpm_winnt:notice] [pid 12280:tid 728] AH00354: Child: Starting 64 worker threads.
[Tue Nov 13 08:38:15.614626 2018] [mpm_winnt:notice] [pid 12236:tid 740] AH00422: Parent: Received shutdown signal -- Shutting down the server.
[Tue Nov 13 08:38:17.645956 2018] [mpm_winnt:notice] [pid 12280:tid 728] AH00364: Child: All worker threads have exited.
[Tue Nov 13 08:38:17.739658 2018] [mpm_winnt:notice] [pid 12236:tid 740] AH00430: Parent: Child process 12280 exited successfully.
[Tue Nov 13 08:39:42.663374 2018] [mpm_winnt:notice] [pid 12908:tid 692] AH00455: Apache/2.4.35 (Win64) PHP/7.2.10 configured -- resuming normal operations
[Tue Nov 13 08:39:42.663374 2018] [mpm_winnt:notice] [pid 12908:tid 692] AH00456: Apache Lounge VC15 Server built: Sep 19 2018 16:08:47
[Tue Nov 13 08:39:42.663374 2018] [core:notice] [pid 12908:tid 692] AH00094: Command line: 'c:\\wamp64\\bin\\apache\\apache2.4.35\\bin\\httpd.exe -d C:/wamp64/bin/apache/apache2.4.35'
[Tue Nov 13 08:39:42.669863 2018] [mpm_winnt:notice] [pid 12908:tid 692] AH00418: Parent: Created child process 13072
[Tue Nov 13 08:39:44.177496 2018] [mpm_winnt:notice] [pid 13072:tid 704] AH00354: Child: Starting 64 worker threads.
[Wed Nov 14 17:39:07.763915 2018] [mpm_winnt:notice] [pid 12908:tid 692] AH00422: Parent: Received shutdown signal -- Shutting down the server.
[Wed Nov 14 17:39:09.812376 2018] [mpm_winnt:notice] [pid 13072:tid 704] AH00364: Child: All worker threads have exited.
[Wed Nov 14 17:39:09.870764 2018] [mpm_winnt:notice] [pid 12908:tid 692] AH00430: Parent: Child process 13072 exited successfully.
[Wed Nov 14 19:07:06.475351 2018] [mpm_winnt:notice] [pid 6232:tid 700] AH00455: Apache/2.4.35 (Win64) PHP/7.2.10 configured -- resuming normal operations
[Wed Nov 14 19:07:06.476350 2018] [mpm_winnt:notice] [pid 6232:tid 700] AH00456: Apache Lounge VC15 Server built: Sep 19 2018 16:08:47
[Wed Nov 14 19:07:06.476350 2018] [core:notice] [pid 6232:tid 700] AH00094: Command line: 'c:\\wamp64\\bin\\apache\\apache2.4.35\\bin\\httpd.exe -d C:/wamp64/bin/apache/apache2.4.35'
[Wed Nov 14 19:07:06.483344 2018] [mpm_winnt:notice] [pid 6232:tid 700] AH00418: Parent: Created child process 9552
[Wed Nov 14 19:07:08.025394 2018] [mpm_winnt:notice] [pid 9552:tid 692] AH00354: Child: Starting 64 worker threads.
[Thu Nov 15 08:58:15.512923 2018] [core:warn] [pid 11136:tid 652] AH00098: pid file C:/wamp64/bin/apache/apache2.4.35/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Thu Nov 15 08:58:15.722794 2018] [mpm_winnt:notice] [pid 11136:tid 652] AH00455: Apache/2.4.35 (Win64) PHP/7.2.10 configured -- resuming normal operations
[Thu Nov 15 08:58:15.722794 2018] [mpm_winnt:notice] [pid 11136:tid 652] AH00456: Apache Lounge VC15 Server built: Sep 19 2018 16:08:47
[Thu Nov 15 08:58:15.722794 2018] [core:notice] [pid 11136:tid 652] AH00094: Command line: 'c:\\wamp64\\bin\\apache\\apache2.4.35\\bin\\httpd.exe -d C:/wamp64/bin/apache/apache2.4.35'
[Thu Nov 15 08:58:15.739784 2018] [mpm_winnt:notice] [pid 11136:tid 652] AH00418: Parent: Created child process 5156
[Thu Nov 15 08:58:17.645609 2018] [mpm_winnt:notice] [pid 5156:tid 576] AH00354: Child: Starting 64 worker threads.
[Thu Nov 15 09:32:41.617607 2018] [core:warn] [pid 11340:tid 660] AH00098: pid file C:/wamp64/bin/apache/apache2.4.35/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Thu Nov 15 09:32:41.753523 2018] [mpm_winnt:notice] [pid 11340:tid 660] AH00455: Apache/2.4.35 (Win64) PHP/7.2.10 configured -- resuming normal operations
[Thu Nov 15 09:32:41.754523 2018] [mpm_winnt:notice] [pid 11340:tid 660] AH00456: Apache Lounge VC15 Server built: Sep 19 2018 16:08:47
[Thu Nov 15 09:32:41.754523 2018] [core:notice] [pid 11340:tid 660] AH00094: Command line: 'c:\\wamp64\\bin\\apache\\apache2.4.35\\bin\\httpd.exe -d C:/wamp64/bin/apache/apache2.4.35'
[Thu Nov 15 09:32:41.761519 2018] [mpm_winnt:notice] [pid 11340:tid 660] AH00418: Parent: Created child process 11296
[Thu Nov 15 09:32:43.091698 2018] [mpm_winnt:notice] [pid 11296:tid 696] AH00354: Child: Starting 64 worker threads.
[Fri Nov 23 20:12:00.790177 2018] [core:alert] [pid 11296:tid 1208] [client ::1:55714] C:/wamp64/www/cockpit/.htaccess: Invalid command '<IfVersion', perhaps misspelled or defined by a module not included in the server configuration
[Fri Nov 23 20:12:37.366400 2018] [core:alert] [pid 11296:tid 1228] [client ::1:55805] C:/wamp64/www/cockpit/.htaccess: Invalid command '<IfVersion', perhaps misspelled or defined by a module not included in the server configuration
[Fri Nov 23 20:12:39.508256 2018] [core:alert] [pid 11296:tid 1208] [client ::1:55806] C:/wamp64/www/cockpit/.htaccess: Invalid command '<IfVersion', perhaps misspelled or defined by a module not included in the server configuration
[Fri Nov 23 20:13:07.508039 2018] [core:alert] [pid 11296:tid 1208] [client ::1:55865] C:/wamp64/www/cockpit/.htaccess: Invalid command '<IfVersion', perhaps misspelled or defined by a module not included in the server configuration
[Fri Nov 23 20:13:09.080556 2018] [core:alert] [pid 11296:tid 1244] [client ::1:55866] C:/wamp64/www/cockpit/.htaccess: Invalid command '<IfVersion', perhaps misspelled or defined by a module not included in the server configuration
[Fri Nov 23 20:17:16.894542 2018] [core:alert] [pid 11296:tid 1208] [client ::1:56269] C:/wamp64/www/cockpit/.htaccess: Invalid command '<IfVersion', perhaps misspelled or defined by a module not included in the server configuration
[Fri Nov 23 20:18:44.142157 2018] [authz_core:error] [pid 11296:tid 1244] [client ::1:56387] AH01630: client denied by server configuration: C:/wamp64/www/pagekit
[Fri Nov 23 20:20:07.030652 2018] [mpm_winnt:notice] [pid 11340:tid 660] AH00422: Parent: Received shutdown signal -- Shutting down the server.
[Fri Nov 23 20:20:09.033653 2018] [mpm_winnt:notice] [pid 11296:tid 696] AH00364: Child: All worker threads have exited.
[Fri Nov 23 20:20:09.220540 2018] [mpm_winnt:notice] [pid 11340:tid 660] AH00430: Parent: Child process 11296 exited successfully.
[Fri Nov 23 20:20:12.303209 2018] [mpm_winnt:notice] [pid 15436:tid 804] AH00455: Apache/2.4.35 (Win64) PHP/7.2.10 configured -- resuming normal operations
[Fri Nov 23 20:20:12.303209 2018] [mpm_winnt:notice] [pid 15436:tid 804] AH00456: Apache Lounge VC15 Server built: Sep 19 2018 16:08:47
[Fri Nov 23 20:20:12.303209 2018] [core:notice] [pid 15436:tid 804] AH00094: Command line: 'c:\\wamp64\\bin\\apache\\apache2.4.35\\bin\\httpd.exe -d C:/wamp64/bin/apache/apache2.4.35'
[Fri Nov 23 20:20:12.310203 2018] [mpm_winnt:notice] [pid 15436:tid 804] AH00418: Parent: Created child process 516
[Fri Nov 23 20:20:13.363555 2018] [mpm_winnt:notice] [pid 516:tid 700] AH00354: Child: Starting 64 worker threads.
[Sun Nov 25 21:02:51.617223 2018] [core:alert] [pid 516:tid 1208] [client ::1:60509] C:/wamp64/www/cockpit/.htaccess: Invalid command '<IfVersion', perhaps misspelled or defined by a module not included in the server configuration
[Sun Nov 25 21:06:58.245284 2018] [mpm_winnt:notice] [pid 15436:tid 804] AH00422: Parent: Received shutdown signal -- Shutting down the server.
[Sun Nov 25 21:07:00.248029 2018] [mpm_winnt:notice] [pid 516:tid 700] AH00364: Child: All worker threads have exited.
[Sun Nov 25 21:07:00.296999 2018] [mpm_winnt:notice] [pid 15436:tid 804] AH00430: Parent: Child process 516 exited successfully.
[Sun Nov 25 21:07:04.911908 2018] [mpm_winnt:notice] [pid 9440:tid 744] AH00455: Apache/2.4.35 (Win64) PHP/7.2.10 configured -- resuming normal operations
[Sun Nov 25 21:07:04.911908 2018] [mpm_winnt:notice] [pid 9440:tid 744] AH00456: Apache Lounge VC15 Server built: Sep 19 2018 16:08:47
[Sun Nov 25 21:07:04.911908 2018] [core:notice] [pid 9440:tid 744] AH00094: Command line: 'c:\\wamp64\\bin\\apache\\apache2.4.35\\bin\\httpd.exe -d C:/wamp64/bin/apache/apache2.4.35'
[Sun Nov 25 21:07:04.921902 2018] [mpm_winnt:notice] [pid 9440:tid 744] AH00418: Parent: Created child process 5928
[Sun Nov 25 21:07:06.002235 2018] [mpm_winnt:notice] [pid 5928:tid 700] AH00354: Child: Starting 64 worker threads.
[Sun Nov 25 21:08:12.543191 2018] [core:alert] [pid 5928:tid 1204] [client ::1:61042] C:/wamp64/www/cockpit/.htaccess: Invalid command '<IfVersion', perhaps misspelled or defined by a module not included in the server configuration
[Tue Nov 27 04:54:09.598310 2018] [core:alert] [pid 5928:tid 1240] [client ::1:50170] C:/wamp64/www/cockpit/.htaccess: Invalid command '<IfVersion', perhaps misspelled or defined by a module not included in the server configuration
[Tue Nov 27 04:56:14.935531 2018] [core:alert] [pid 5928:tid 1236] [client ::1:50246] C:/wamp64/www/cockpit/.htaccess: Invalid command '<IfVersion', perhaps misspelled or defined by a module not included in the server configuration
[Tue Nov 27 04:56:16.432595 2018] [core:alert] [pid 5928:tid 1236] [client ::1:50247] C:/wamp64/www/cockpit/.htaccess: Invalid command '<IfVersion', perhaps misspelled or defined by a module not included in the server configuration
`

**Comment by erkand-imeri** [comment]
Hi there, i just fixed the issue. Seeing the Apache error log i realized i need to enable mod_version in my Apache Server. I just uncommented the line in httpd.conf and now mod_version module is loaded and cockpit cms works.

Thank you.

**Comment by tektuts** [comment]
indeed i was able to replicate the issue and the above solved it. Kudos.

**Comment by nektobit** [comment]
> I just uncommented the line in httpd.conf and now mod_version module is loaded and cockpit cms works.
Wow! Thank you! Now cockpit works on Open Server WAMP

**Comment by B-Stewart** [comment]
Just ran into this issue as well. Perhaps we can add it to the requirements?
