### ISSUE TITLE
which cockpit version introduces webhook?

### ISSUE THREAD

**Issue by mraqueeb** [agentejo/cockpit#945]
Hi @aheinze, my organization is using the dev-legacy version of cockpit at the moment. We are interested in setting up webhooks which I believe comes with newer versions. Is it possible to use webhooks within the legacy version? What version of cockpit introduced webhooks? Is there any documentation for me to see what's new in every version?

Please let me know.
Thank you.

**Comment by raffaelj** [comment]
> What version of cockpit introduced webhooks?

Have a look at https://github.com/agentejo/cockpit/search?q=webhook&type=Commits
So webhooks were implemented in Aug 2016.

> Is there any documentation for me to see what's new in every version?

There is still no changelog, but the commits are well-named (most of the time): https://github.com/agentejo/cockpit/commits

I don't know, if the legacy version supports webhooks. I never used the outdated legacy branch.
