### ISSUE TITLE
[Help] Is it possible to filter with query other than equal?

### ISSUE THREAD

**Issue by joshuaavalon** [agentejo/cockpit#953]
Is it possible to filter with query other than equal? For example, greater than, contains and other common query other than equal. There is no documentation on this. I wonder if it is possible.

**Comment by DavidB137** [comment]
Hi!

Yes, it is possible. You can use "operators" or functions like:
- `$not` or `$ne`: not equal to
- `$lt`: less than
- `$lte`: less than or equal to
- `$gt`: greater than
- `$gte`: greater than or equal to
...

*See: [/lib/MongoLite/Database.php](https://github.com/agentejo/cockpit/blob/next/lib/MongoLite/Database.php#L322-L434)*

In action it looks like this:
```
https://example.com/admin/api/collections/get/animals/
   ?token=YOUR_SECRET_TOKEN
   &filter[age][$gte]=10
```
or you can combine them: e.g. to get only values in interval [8, 16):
```
https://example.com/admin/api/collections/get/animals/
   ?token=YOUR_SECRET_TOKEN
   &filter[age][$gte]=8
   &filter[age][$lt]=16
```

If you use JavaScript for accessing API:
```javascript
fetch('/api/collections/get/animals/?token=YOUR_SECRET_TOKEN', {
   method: 'post',
   headers: { 'Content-Type': 'application/json' },
   body: JSON.stringify({
      filter: {
         age: {
            $gte: 8,
            $lt: 16
         }
      }
   })
})
.then(res => res.json())
.then(res => console.log(res));
```

**Comment by joshuaavalon** [comment]
@DavidB137 Thank you very much
