### ISSUE TITLE
docker-init command fails with error checking for libzip... not found

### ISSUE THREAD

**Issue by Hughp135** [agentejo/cockpit#958]
I'm getting this error from docker-init on windows 10 with node 10.11.0 and docker 2.0.0

```
checking for libzip... not found
configure: error: Please reinstall the libzip distribution
```

This was fixed by adding this line to the Dockerfile:
`  libzip-dev \`

Workaround Dockerfile command:
```
RUN apt-get update \
    && apt-get install -y \
    wget zip unzip \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    sqlite3 libsqlite3-dev \
    libssl-dev \
    libzip-dev \
    && pecl install mongodb \
    && pecl install redis \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) iconv gd pdo zip opcache pdo_sqlite \
    && a2enmod rewrite expires
```

**Comment by aheinze** [comment]
should be fixed now. thanks for reporting!

**Comment by Blistok** [comment]
@aheinze This doesn't seem to be updated in either [next](https://github.com/agentejo/cockpit/blob/next/Dockerfile) or [master](https://github.com/agentejo/cockpit/blob/master/Dockerfile).
Also, confirming that adding `libzip-dev` solves the issue.

**Comment by vinnyfs89** [comment]
```sh
apt install php-zip
```

**Comment by tooheyc** [comment]
apt install libzip-dev

> E: Unable to locate package libzip-dev
