### ISSUE TITLE
Message "Saving failed" when saving an entry in a collection - but changes are saved

### ISSUE THREAD

**Issue by emdahlstrom** [agentejo/cockpit#971]
Hi I'm getting the message "Saving failed" when I try to save entries in some but not all of my collections, however the content is saved correctly. 

I saw the earlier issue where saving didn't work that was resolved by making the storage directory writable but that doesn't help. and is also a different issue since in my case the content is saved. 

There is no error message in the browser console and nothing in the php logs. 

I first thought that maybe it was due to a a webhook getting the wrong response but disabling the webhook doesn't change the result. 

I'm running Cockpit 0.8.7 with Detektivo, Groups and Logger

Any idea how to debug this?

**Comment by pauloamgomes** [comment]
Hey @emdahlstrom , using the network inspector what you have for the ajax save request?

**Comment by emdahlstrom** [comment]
Thanks @pauloamgomes! It seems to be Detektivo:

<b>Warning</b>:  mb_strtolower() expects parameter 1 to be string, array given in <b>/addons/Detektivo/vendor/teamtnt/tntsearch/src/Support/Tokenizer.php</b> on line <b>8</b><br />

**Comment by emdahlstrom** [comment]
Updating Detektivo to the latest master removed the error. Thanks for putting me on the right path!
