### ISSUE TITLE
Buddy.works Webhook

### ISSUE THREAD

**Issue by ColinTravis** [agentejo/cockpit#979]
I'm using Buddy.works for a deployment engine for one of my sites using Cockpit, and everything is working great save for triggering the webhook. Buddy supports all the usual POST, GET, HTTP requests, and the hook URL I'm using works great in everything from Github/Bitbucket/Navigating to it from a browser, but I can't for the life of me get Cockpit to trigger it. I tested a Netlify webhook, and that's triggering fine. 

Are there any logs where I can see what's happening with my webhook? Is there a way to specify if I'm sending a POST/GET/HTTP?

**Comment by aheinze** [comment]
Hi! You can try services like request bin - https://requestbin.fullcontact.com to test webhooks. hope it helps.
