### ISSUE TITLE
Exclude composer vendors and assets

### ISSUE THREAD

**Issue by Crease29** [agentejo/cockpit#984]
It would be really great to exclude composer vendors and assets. That would mean that we can throw away auto-generated files and external dependencies and fetch them during the build.

E.g.
* Add `lib/vendor/` to `.gitignore` ([Should I commit the dependencies in my vendor directory?](https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md) TL;DR **no.**)
* Add auto-generated files from the `assets` directory to `.gitignore`
* Integrate Travis CI to build release zips with the generated assets and fetched external dependencies

The benefits should be obvious:
* No more conflicts in pull requests because auto-generated files were changed
* Smaller repository footprint

**Comment by Crease29** [comment]
I would like to put that into a CR but that would need some effort so I'd like to know if it's worth the effort or if you would decline it anyways.

**Comment by Crease29** [comment]
@aheinze waiting for feedback here.

**Comment by aheinze** [comment]
No need for that right now. but might get relevant in the future...
