### ISSUE TITLE
Projection parameters in URL are not parsed as values (some versions of) MongoDB understands

### ISSUE THREAD

**Issue by gryphonmyers** [agentejo/cockpit#987]
Repro steps:

1) Configure a cockpit instance to use an AWS DocumentDB server (as of this writing, they are mongodb version 3.6). Note that other versions of MongoDB do not necessarily exhibit this problem.
2) Attempt to query a collection from this db using a projection on the cockpit rest api ("fields" parameter), e.g. `cockpit/api/collections/get/myCollection?token=myToken&fields[myField]=1`
3) Note that all fields except for "myField" are sent in the response document.
4) Try an exclusive projection: `cockpit/api/collections/get/myCollection?token=myToken&fields[myField]=0`
5) Note that the result is the same.
6) Try an explicit true value: `cockpit/api/collections/get/myCollection?token=myToken&fields[myField]=true`
7) Note that "myField" is now the only field sent in the response. 

Expected Results:

As indicated in the MongoDB documentation, 0 and false, 1 and true should be interchangeable for projection: https://docs.mongodb.com/manual/reference/method/db.collection.find/#db.collection.find

Observations:

It appears that certain versions of MongoDB (including the version used by AWS for their DocumentDB service) do not treat `.projection({"myField": "1"})` the same as `.projection({"myField": 1})`. The string representation of the truthy value is, for whatever reason, treated as a falsey value. We are handling parsing of bool values here: https://github.com/agentejo/cockpit/blob/aae6d8224db9854e1a200a1e62e1fbdd22df9ebf/modules/Collections/Controller/RestApi.php#L255 but this does not catch booleans sent in binary form, as we are explicitly checking for "true" and "false". We should make this a little less narrow so that we are sending values MongoDB will parse correctly when handling projection.

**Comment by aheinze** [comment]
this was once removed because of this: https://github.com/agentejo/cockpit/issues/779 ;-)

I think we need a dedicated fixNumericValues for the fields parameter

**Comment by gryphonmyers** [comment]
Ohh!!! Good catch. Yes maybe we need to only do this for fields. I can
amend my PR shortly
