### ISSUE TITLE
Redirects back to login screen after successful login

### ISSUE THREAD

**Issue by panosru** [agentejo/cockpit#989]
I got the exact same issue as in #415 

After installing cockpit, running /install page, I'm putting admin / admin in /auth/login and it redirects me back to /auth/login...

I noticed that when I'm submit the login form I'm receiving the following in the console:
![image](https://user-images.githubusercontent.com/400362/52092706-19022e80-25c1-11e9-93a7-5c125057849d.png)

**Comment by panosru** [comment]
It was a cloudflare setting (rocket loader) that was causing the problem. just turn it off.

**Comment by SueldoSales** [comment]
> It was a cloudflare setting (rocket loader) that was causing the problem. just turn it off.

Saved my day!!
