### ISSUE TITLE
System error on save for collection link inside a set

### ISSUE THREAD

**Issue by panosru** [agentejo/cockpit#990]
Hello,

when I try to save a repeater field with the following settings:

```json
{
  "fields": [
    {
      "type": "set",
      "label": "Important Person",
      "options": {
        "fields": [
          {
            "type": "collectionlink",
            "label": "Name",
            "options": {
              "link": "people",
              "display": "name",
              "multiple": false,
              "limit": false
            }
          },
          {
            "name": "role",
            "label": "Role",
            "type": "text"
          }
        ]
      }
    }
  ]
}
```

I'm getting a system error.

Ideally, I would like to be able on that field to select the `person` and from the `person` database to receive the `name` and `surname` which would populate the `full name` automatically in the form, next I would like to set the `role` of that person.

Thanks!

**Comment by Blistok** [comment]
@panosru Do you have _people_ collection created? (`"link": "people"`)

**Comment by panosru** [comment]
@Blistok of-course.... why would I post the issue without the collection? 😳

![image](https://user-images.githubusercontent.com/400362/52139504-03404800-2659-11e9-8f26-ce2725c2dbe6.png)

![image](https://user-images.githubusercontent.com/400362/52139550-20751680-2659-11e9-8208-10b8d25b21b3.png)

**Comment by Blistok** [comment]
This seems to break (unhandled) when trying to link to nonexistent collection.
FWIW, I can't replicate on my end (latest `next` + config object you've posted). What's the system error?

**Comment by panosru** [comment]
@Blistok it just says system error 

![image](https://user-images.githubusercontent.com/400362/52140404-63d08480-265b-11e9-98f6-f1e786ab035d.png)

Could you point me in the right direction how to enable debug mode on cockpit so I could get the root of the issue?

**Comment by panosru** [comment]
@Blistok Thanks! It wasn't documented :)

I got this:
![image](https://user-images.githubusercontent.com/400362/52141257-d5113700-265d-11e9-965a-8ec0a7a8e97d.png)


And that is what I was posting:
![image](https://user-images.githubusercontent.com/400362/52141456-7bf5d300-265e-11e9-9b88-b1792862f6ea.png)

**Comment by Blistok** [comment]
This seems to be connected with [mongo-php-driver](https://github.com/mongodb/mongo-php-driver), but I have no idea whether the error is on that side, or higher level in [MongoDB PHP Library](https://github.com/agentejo/cockpit/blob/next/lib/vendor/mongodb/mongodb/src/Operation/Update.php#L177).

In any case the issue is caused by trying to write empty key to db here:
<img width="319" alt="screen shot 2019-02-01 at 1 36 57 pm" src="https://user-images.githubusercontent.com/9505695/52142395-8bf1c080-2626-11e9-9573-3df2a3ba4c7e.png">

Sorry I can't help more.

**Comment by panosru** [comment]
@Blistok Thanks mate! You helped enough! 

I noticed the empty key, I'll have to debug it and find out why it is empty...

**Comment by Blistok** [comment]
@panosru I think the _name_ property is required (its value seems to be used as a key), so if it's not provided it's just gonna infer the empty string.
Try adding it wherever you have only _label_ (e.g. `"label": "Important Person"`, `"label": "Name"`) [it only needs to be unique if it's on the same level], and see if that fixes your issue.

**Comment by panosru** [comment]
@Blistok Don't you ever dare to say again "Sorry I can't help more"!

![image](https://user-images.githubusercontent.com/400362/52147026-232e3680-266e-11e9-9a44-b737e50c3bb4.png)

You're a genius! 

Thanks mate!

**Comment by pozylon** [comment]
Just hit this problem with GraphiQL which returns INTERNAL SERVER ERROR if a repeater with set returns an empty string.
