### ISSUE TITLE
Customize collection entries displayed fields

### ISSUE THREAD

**Issue by devron1n** [agentejo/cockpit#994]
Hello!
Tell me plz how can i customize collection entries displayed fields in the admin panel?

![image](https://user-images.githubusercontent.com/38067118/52228183-bd86b800-28c2-11e9-8c89-d7436de0526a.png)

I'd like to increase width of yellow field and hide red field
Thank you!

**Comment by raffaelj** [comment]
Have a look here:
https://discourse.getcockpit.com/t/new-addon-force-full-title-in-collection-overview/596

I didn't test it yet, but it seems to address your issue until the UI for sortable fields looks a bit better by default.
