### ISSUE TITLE
'Display' field shows old data and not fetching data from changed linked collection

### ISSUE THREAD

**Issue by andriipol** [agentejo/cockpit#996]
1. I created a collection and filed it with data.
2. I added other collection and created a collection link to the first collection. Filled it with data from the first collection.
3. Changed data in the first collection.
4. In 'display' field of the second collection it shows old data that was linked on the 2 step.

Could you please tell how to deal with this issue?

**Comment by aheinze** [comment]
this will be fixed for the next release

**Comment by andriipol** [comment]
Thanks, I saw it was fixed in the exact entry (when you open it), but it still shows old data in a collection (when you see all of them)
