### ISSUE TITLE
Return original image dimensions

### ISSUE THREAD

**Issue by ben-styling** [agentejo/cockpit#999]
Hi,

Is it possible for Cockpit to return the dimensions of the original uploaded image?

This is useful for ensuring there's no re-flow when the image loads in when I'm not requesting a specific height of an image.

If it's not currently possible, could someone direct me to where I should look to add this myself?

**Comment by aheinze** [comment]
I would recommend to use the field type `asset` to get all related meta information with a request

**Comment by ben-styling** [comment]
Thanks for the reply.

I tried this, but the response is still the just path, the only meta is the ones defined in the field.

For example:

```
fetch('/api/singletons/get/{singletonname}?token=xxtokenxx')
    .then(data => data.json())
    .then(data => console.log(data));
```

Will return:
```
{
    ...fields,
    image: {
        path: "/storage/uploads/etc",
        meta: {
            title: "",
            additional_predefined_fields: "",
        }
    }
}
```

I thought perhaps you meant to use `/api/cockpit/assets` to return data.

```
fetch('/api/cockpit/assets?token=xxtokenxx', {
    method: 'post',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
        filter: {
            path: data.image.path.replace('/storage/uploads', '')
        }
    })
})
.then(assets => assets.json())
.then(assets => console.log(assets));
```

But this isn't really an option anyway.
I'd like to build without a static site generator, so keeping the number of requests to a minimum would be ideal. Doing this for every image isn't practical for me.

**Comment by pauloamgomes** [comment]
Hey @ben-styling , maybe https://github.com/pauloamgomes/ImageStyles can help

**Comment by ben-styling** [comment]
Hi @pauloamgomes, thanks for the suggestion.

This is an interesting solution would work well for specific use-cases, for example art directed responsive images.

However, if the image is included in free-flow content, for example a blog or an article, I'd like the ratio of the image to be the same as the originally uploaded image.
I need the width and height to be able to either render a placeholder, or allow it to sit in a container the same ratio of the image to prevent content from jumping when the image loads in.

**Comment by pauloamgomes** [comment]
@ben-styling If you are using an asset field type as @aheinze suggested you should receive the original asset width/height attributes.

You also can give to your styles names like "Card_300x100" so on then JSON you have the size in the style name.

**Comment by ben-styling** [comment]
I'm so sorry, I must have done something wrong with my first test.
@aheinze is correct, the asset field does return what I'm looking for.

Thank you both for your time.
